if global.render = 0 { global.spr_thegreentie = sprite_add("group\thegreentie.png",2,1,1,0,0); sprite_index = global.spr_thegreentie; global.current = "thegreentie"; } 
if global.render = 1 { global.spr_businessbanana = sprite_add("group\businessbanana.png",2,1,1,0,0); sprite_index = global.spr_businessbanana; global.current = "businessbanana"; } 
if global.render = 2 { global.spr_dennot = sprite_add("group\dennot.png",2,1,1,0,0); sprite_index = global.spr_dennot; global.current = "dennot"; } 
if global.render = 3 { global.spr_mario = sprite_add("group\mario.png",2,1,1,0,0); sprite_index = global.spr_mario; global.current = "mario"; } 
if global.render = 4 { global.spr_luigi = sprite_add("group\luigi.png",2,1,1,0,0); sprite_index = global.spr_luigi; global.current = "luigi"; } 
if global.render = 5 { global.spr_bowser = sprite_add("group\bowser.png",2,1,1,0,0); sprite_index = global.spr_bowser; global.current = "bowser"; } 
if global.render = 6 { global.spr_peach = sprite_add("group\peach.png",2,1,1,0,0); sprite_index = global.spr_peach; global.current = "peach"; } 
if global.render = 7 { global.spr_drmario = sprite_add("group\drmario.png",2,1,1,0,0); sprite_index = global.spr_drmario; global.current = "drmario"; } 
if global.render = 8 { global.spr_yoshi = sprite_add("group\yoshi.png",2,1,1,0,0); sprite_index = global.spr_yoshi; global.current = "yoshi"; } 
if global.render = 9 { global.spr_pit = sprite_add("group\pit.png",2,1,1,0,0); sprite_index = global.spr_pit; global.current = "pit"; } 
if global.render = 10 { global.spr_captainfalcon = sprite_add("group\captainfalcon.png",2,1,1,0,0); sprite_index = global.spr_captainfalcon; global.current = "captainfalcon"; } 
if global.render = 11 { global.spr_mrgameandwatch = sprite_add("group\mrgameandwatch.png",2,1,1,0,0); sprite_index = global.spr_mrgameandwatch; global.current = "mrgameandwatch"; } 
if global.render = 12 { global.spr_rob = sprite_add("group\rob.png",2,1,1,0,0); sprite_index = global.spr_rob; global.current = "rob"; } 
if global.render = 13 { global.spr_pikachu = sprite_add("group\pikachu.png",2,1,1,0,0); sprite_index = global.spr_pikachu; global.current = "pikachu"; } 
if global.render = 14 { global.spr_bulbasaur = sprite_add("group\bulbasaur.png",2,1,1,0,0); sprite_index = global.spr_bulbasaur; global.current = "bulbasaur"; } 
if global.render = 15 { global.spr_ivysaur = sprite_add("group\ivysaur.png",2,1,1,0,0); sprite_index = global.spr_ivysaur; global.current = "ivysaur"; } 
if global.render = 16 { global.spr_venusaur = sprite_add("group\venusaur.png",2,1,1,0,0); sprite_index = global.spr_venusaur; global.current = "venusaur"; } 
if global.render = 17 { global.spr_charmander = sprite_add("group\charmander.png",2,1,1,0,0); sprite_index = global.spr_charmander; global.current = "charmander"; } 
if global.render = 18 { global.spr_charmeleon = sprite_add("group\charmeleon.png",2,1,1,0,0); sprite_index = global.spr_charmeleon; global.current = "charmeleon"; } 
if global.render = 19 { global.spr_charizard = sprite_add("group\charizard.png",2,1,1,0,0); sprite_index = global.spr_charizard; global.current = "charizard"; } 
if global.render = 20 { global.spr_link = sprite_add("group\link.png",2,1,1,0,0); sprite_index = global.spr_link; global.current = "link"; } 
if global.render = 21 { global.spr_zelda = sprite_add("group\zelda.png",2,1,1,0,0); sprite_index = global.spr_zelda; global.current = "zelda"; } 
if global.render = 22 { global.spr_sheik = sprite_add("group\sheik.png",2,1,1,0,0); sprite_index = global.spr_sheik; global.current = "sheik"; } 
if global.render = 23 { global.spr_ganondorf = sprite_add("group\ganondorf.png",2,1,1,0,0); sprite_index = global.spr_ganondorf; global.current = "ganondorf"; } 
if global.render = 24 { global.spr_sonic = sprite_add("group\sonic.png",2,1,1,0,0); sprite_index = global.spr_sonic; global.current = "sonic"; } 
if global.render = 25 { global.spr_wario = sprite_add("group\wario.png",2,1,1,0,0); sprite_index = global.spr_wario; global.current = "wario"; } 
if global.render = 26 { global.spr_pikminred = sprite_add("group\pikminred.png",2,1,1,0,0); sprite_index = global.spr_pikminred; global.current = "pikminred"; } 
if global.render = 27 { global.spr_pikminyellow = sprite_add("group\pikminyellow.png",2,1,1,0,0); sprite_index = global.spr_pikminyellow; global.current = "pikminyellow"; } 
if global.render = 28 { global.spr_pikminblue = sprite_add("group\pikminblue.png",2,1,1,0,0); sprite_index = global.spr_pikminblue; global.current = "pikminblue"; } 
if global.render = 29 { global.spr_pikminwhite = sprite_add("group\pikminwhite.png",2,1,1,0,0); sprite_index = global.spr_pikminwhite; global.current = "pikminwhite"; } 
if global.render = 30 { global.spr_pikminpurple = sprite_add("group\pikminpurple.png",2,1,1,0,0); sprite_index = global.spr_pikminpurple; global.current = "pikminpurple"; } 
if global.render = 31 { global.spr_engineer = sprite_add("group\engineer.png",2,1,1,0,0); sprite_index = global.spr_engineer; global.current = "engineer"; } 
if global.render = 32 { global.spr_steve = sprite_add("group\steve.png",2,1,1,0,0); sprite_index = global.spr_steve; global.current = "steve"; } 
if global.render = 33 { global.spr_magickared = sprite_add("group\magickared.png",2,1,1,0,0); sprite_index = global.spr_magickared; global.current = "magickared"; } 
if global.render = 34 { global.spr_magickablue = sprite_add("group\magickablue.png",2,1,1,0,0); sprite_index = global.spr_magickablue; global.current = "magickablue"; } 
if global.render = 35 { global.spr_magickayellow = sprite_add("group\magickayellow.png",2,1,1,0,0); sprite_index = global.spr_magickayellow; global.current = "magickayellow"; } 
if global.render = 36 { global.spr_magickagreen = sprite_add("group\magickagreen.png",2,1,1,0,0); sprite_index = global.spr_magickagreen; global.current = "magickagreen"; } 
if global.render = 37 { global.spr_santaclaus = sprite_add("group\santaclaus.png",2,1,1,0,0); sprite_index = global.spr_santaclaus; global.current = "santaclaus"; } 
if global.render = 38 { global.spr_blossom = sprite_add("group\blossom.png",2,1,1,0,0); sprite_index = global.spr_blossom; global.current = "blossom"; } 
if global.render = 39 { global.spr_bubbles = sprite_add("group\bubbles.png",2,1,1,0,0); sprite_index = global.spr_bubbles; global.current = "bubbles"; } 
if global.render = 40 { global.spr_buttercup = sprite_add("group\buttercup.png",2,1,1,0,0); sprite_index = global.spr_buttercup; global.current = "buttercup"; } 
if global.render = 41 { global.spr_eddy = sprite_add("group\eddy.png",2,1,1,0,0); sprite_index = global.spr_eddy; global.current = "eddy"; } 
if global.render = 42 { global.spr_edd = sprite_add("group\edd.png",2,1,1,0,0); sprite_index = global.spr_edd; global.current = "edd"; } 
if global.render = 43 { global.spr_ed = sprite_add("group\ed.png",2,1,1,0,0); sprite_index = global.spr_ed; global.current = "ed"; } 
if global.render = 44 { global.spr_courage = sprite_add("group\courage.png",2,1,1,0,0); sprite_index = global.spr_courage; global.current = "courage"; } 
if global.render = 45 { global.spr_gir = sprite_add("group\gir.png",2,1,1,0,0); sprite_index = global.spr_gir; global.current = "gir"; } 
if global.render = 46 { global.spr_spongebob = sprite_add("group\spongebob.png",2,1,1,0,0); sprite_index = global.spr_spongebob; global.current = "spongebob"; } 
if global.render = 47 { global.spr_captainknuckles = sprite_add("group\captainknuckles.png",2,1,1,0,0); sprite_index = global.spr_captainknuckles; global.current = "captainknuckles"; } 
if global.render = 48 { global.spr_flapjack = sprite_add("group\flapjack.png",2,1,1,0,0); sprite_index = global.spr_flapjack; global.current = "flapjack"; } 
if global.render = 49 { global.spr_chowder = sprite_add("group\chowder.png",2,1,1,0,0); sprite_index = global.spr_chowder; global.current = "chowder"; } 
if global.render = 50 { global.spr_shnitzel = sprite_add("group\shnitzel.png",2,1,1,0,0); sprite_index = global.spr_shnitzel; global.current = "shnitzel"; } 
if global.render = 51 { global.spr_waluigi = sprite_add("group\waluigi.png",2,1,1,0,0); sprite_index = global.spr_waluigi; global.current = "waluigi"; } 
if global.render = 52 { global.spr_galvantula = sprite_add("group\galvantula.png",2,1,1,0,0); sprite_index = global.spr_galvantula; global.current = "galvantula"; } 
if global.render = 53 { global.spr_electivire = sprite_add("group\electivire.png",2,1,1,0,0); sprite_index = global.spr_electivire; global.current = "electivire"; } 
if global.render = 54 { global.spr_reuniclus = sprite_add("group\reuniclus.png",2,1,1,0,0); sprite_index = global.spr_reuniclus; global.current = "reuniclus"; } 
if global.render = 55 { global.spr_pikminrock = sprite_add("group\pikminrock.png",2,1,1,0,0); sprite_index = global.spr_pikminrock; global.current = "pikminrock"; } 
if global.render = 56 { global.spr_pikminwinged = sprite_add("group\pikminwinged.png",2,1,1,0,0); sprite_index = global.spr_pikminwinged; global.current = "pikminwinged"; } 
if global.render = 57 { global.spr_spinda = sprite_add("group\spinda.png",2,1,1,0,0); sprite_index = global.spr_spinda; global.current = "spinda"; } 
if global.render = 58 { global.spr_mrdickens = sprite_add("group\mrdickens.png",2,1,1,0,0); sprite_index = global.spr_mrdickens; global.current = "mrdickens"; } 
if global.render = 59 { global.spr_castform = sprite_add("group\castform.png",2,1,1,0,0); sprite_index = global.spr_castform; global.current = "castform"; } 
if global.render = 60 { global.spr_castformsunny = sprite_add("group\castformsunny.png",2,1,1,0,0); sprite_index = global.spr_castformsunny; global.current = "castformsunny"; } 
if global.render = 61 { global.spr_castformrainy = sprite_add("group\castformrainy.png",2,1,1,0,0); sprite_index = global.spr_castformrainy; global.current = "castformrainy"; } 
if global.render = 62 { global.spr_castformsnowy = sprite_add("group\castformsnowy.png",2,1,1,0,0); sprite_index = global.spr_castformsnowy; global.current = "castformsnowy"; } 
if global.render = 63 { global.spr_beheeyem = sprite_add("group\beheeyem.png",2,1,1,0,0); sprite_index = global.spr_beheeyem; global.current = "beheeyem"; } 
if global.render = 64 { global.spr_celebi = sprite_add("group\celebi.png",2,1,1,0,0); sprite_index = global.spr_celebi; global.current = "celebi"; } 
if global.render = 65 { global.spr_deoxys = sprite_add("group\deoxys.png",2,1,1,0,0); sprite_index = global.spr_deoxys; global.current = "deoxys"; } 
if global.render = 66 { global.spr_deoxysattack = sprite_add("group\deoxysattack.png",2,1,1,0,0); sprite_index = global.spr_deoxysattack; global.current = "deoxysattack"; } 
if global.render = 67 { global.spr_deoxysdefense = sprite_add("group\deoxysdefense.png",2,1,1,0,0); sprite_index = global.spr_deoxysdefense; global.current = "deoxysdefense"; } 
if global.render = 68 { global.spr_deoxysspeed = sprite_add("group\deoxysspeed.png",2,1,1,0,0); sprite_index = global.spr_deoxysspeed; global.current = "deoxysspeed"; } 
if global.render = 69 { global.spr_diglet = sprite_add("group\diglet.png",2,1,1,0,0); sprite_index = global.spr_diglet; global.current = "diglet"; } 
if global.render = 70 { global.spr_ditto = sprite_add("group\ditto.png",2,1,1,0,0); sprite_index = global.spr_ditto; global.current = "ditto"; } 
if global.render = 71 { global.spr_drifloon = sprite_add("group\drifloon.png",2,1,1,0,0); sprite_index = global.spr_drifloon; global.current = "drifloon"; } 
if global.render = 72 { global.spr_electrode = sprite_add("group\electrode.png",2,1,1,0,0); sprite_index = global.spr_electrode; global.current = "electrode"; } 
if global.render = 73 { global.spr_escavalier = sprite_add("group\escavalier.png",2,1,1,0,0); sprite_index = global.spr_escavalier; global.current = "escavalier"; } 
if global.render = 74 { global.spr_froslass = sprite_add("group\froslass.png",2,1,1,0,0); sprite_index = global.spr_froslass; global.current = "froslass"; } 
if global.render = 75 { global.spr_genescect = sprite_add("group\genescect.png",2,1,1,0,0); sprite_index = global.spr_genescect; global.current = "genescect"; } 
if global.render = 76 { global.spr_geodude = sprite_add("group\geodude.png",2,1,1,0,0); sprite_index = global.spr_geodude; global.current = "geodude"; } 
if global.render = 77 { global.spr_gastly = sprite_add("group\gastly.png",2,1,1,0,0); sprite_index = global.spr_gastly; global.current = "gastly"; } 
if global.render = 78 { global.spr_giratinaorigin = sprite_add("group\giratinaorigin.png",2,1,1,0,0); sprite_index = global.spr_giratinaorigin; global.current = "giratinaorigin"; } 
if global.render = 79 { global.spr_golurk = sprite_add("group\golurk.png",2,1,1,0,0); sprite_index = global.spr_golurk; global.current = "golurk"; } 
if global.render = 80 { global.spr_hydreigon = sprite_add("group\hydreigon.png",2,1,1,0,0); sprite_index = global.spr_hydreigon; global.current = "hydreigon"; } 
if global.render = 81 { global.spr_kyurem = sprite_add("group\kyurem.png",2,1,1,0,0); sprite_index = global.spr_kyurem; global.current = "kyurem"; } 
if global.render = 82 { global.spr_lunatone = sprite_add("group\lunatone.png",2,1,1,0,0); sprite_index = global.spr_lunatone; global.current = "lunatone"; } 
if global.render = 83 { global.spr_solrock = sprite_add("group\solrock.png",2,1,1,0,0); sprite_index = global.spr_solrock; global.current = "solrock"; } 
if global.render = 84 { global.spr_magnemite = sprite_add("group\magnemite.png",2,1,1,0,0); sprite_index = global.spr_magnemite; global.current = "magnemite"; } 
if global.render = 85 { global.spr_metagross = sprite_add("group\metagross.png",2,1,1,0,0); sprite_index = global.spr_metagross; global.current = "metagross"; } 
if global.render = 86 { global.spr_ninjask = sprite_add("group\ninjask.png",2,1,1,0,0); sprite_index = global.spr_ninjask; global.current = "ninjask"; } 
if global.render = 87 { global.spr_poliwag = sprite_add("group\poliwag.png",2,1,1,0,0); sprite_index = global.spr_poliwag; global.current = "poliwag"; } 
if global.render = 88 { global.spr_psyduck = sprite_add("group\psyduck.png",2,1,1,0,0); sprite_index = global.spr_psyduck; global.current = "psyduck"; } 
if global.render = 89 { global.spr_regigigas = sprite_add("group\regigigas.png",2,1,1,0,0); sprite_index = global.spr_regigigas; global.current = "regigigas"; } 
if global.render = 90 { global.spr_rotom = sprite_add("group\rotom.png",2,1,1,0,0); sprite_index = global.spr_rotom; global.current = "rotom"; } 
if global.render = 91 { global.spr_rotomfan = sprite_add("group\rotomfan.png",2,1,1,0,0); sprite_index = global.spr_rotomfan; global.current = "rotomfan"; } 
if global.render = 92 { global.spr_rotomfrost = sprite_add("group\rotomfrost.png",2,1,1,0,0); sprite_index = global.spr_rotomfrost; global.current = "rotomfrost"; } 
if global.render = 93 { global.spr_rotomheat = sprite_add("group\rotomheat.png",2,1,1,0,0); sprite_index = global.spr_rotomheat; global.current = "rotomheat"; } 
if global.render = 94 { global.spr_rotomwash = sprite_add("group\rotomwash.png",2,1,1,0,0); sprite_index = global.spr_rotomwash; global.current = "rotomwash"; } 
if global.render = 95 { global.spr_rotommow = sprite_add("group\rotommow.png",2,1,1,0,0); sprite_index = global.spr_rotommow; global.current = "rotommow"; } 
if global.render = 96 { global.spr_sawk = sprite_add("group\sawk.png",2,1,1,0,0); sprite_index = global.spr_sawk; global.current = "sawk"; } 
if global.render = 97 { global.spr_scolipede = sprite_add("group\scolipede.png",2,1,1,0,0); sprite_index = global.spr_scolipede; global.current = "scolipede"; } 
if global.render = 98 { global.spr_shedinja = sprite_add("group\shedinja.png",2,1,1,0,0); sprite_index = global.spr_shedinja; global.current = "shedinja"; } 
if global.render = 99 { global.spr_simisage = sprite_add("group\simisage.png",2,1,1,0,0); sprite_index = global.spr_simisage; global.current = "simisage"; } 
if global.render = 100 { global.spr_sigilyph = sprite_add("group\sigilyph.png",2,1,1,0,0); sprite_index = global.spr_sigilyph; global.current = "sigilyph"; } 
if global.render = 101 { global.spr_tentacruel = sprite_add("group\tentacruel.png",2,1,1,0,0); sprite_index = global.spr_tentacruel; global.current = "tentacruel"; } 
if global.render = 102 { global.spr_angrybirdred = sprite_add("group\angrybirdred.png",2,1,1,0,0); sprite_index = global.spr_angrybirdred; global.current = "angrybirdred"; } 
if global.render = 103 { global.spr_angrybirdwhite = sprite_add("group\angrybirdwhite.png",2,1,1,0,0); sprite_index = global.spr_angrybirdwhite; global.current = "angrybirdwhite"; } 
if global.render = 104 { global.spr_angrybirdyellow = sprite_add("group\angrybirdyellow.png",2,1,1,0,0); sprite_index = global.spr_angrybirdyellow; global.current = "angrybirdyellow"; } 
if global.render = 105 { global.spr_frosty = sprite_add("group\frosty.png",2,1,1,0,0); sprite_index = global.spr_frosty; global.current = "frosty"; } 
if global.render = 106 { global.spr_professorlayton = sprite_add("group\professorlayton.png",2,1,1,0,0); sprite_index = global.spr_professorlayton; global.current = "professorlayton"; } 
if global.render = 107 { global.spr_navi = sprite_add("group\navi.png",2,1,1,0,0); sprite_index = global.spr_navi; global.current = "navi"; } 
if global.render = 108 { global.spr_nyancat = sprite_add("group\nyancat.png",2,1,1,0,0); sprite_index = global.spr_nyancat; global.current = "nyancat"; } 
if global.render = 109 { global.spr_squirtle = sprite_add("group\squirtle.png",2,1,1,0,0); sprite_index = global.spr_squirtle; global.current = "squirtle"; } 
if global.render = 110 { global.spr_volcarona = sprite_add("group\volcarona.png",2,1,1,0,0); sprite_index = global.spr_volcarona; global.current = "volcarona"; } 
if global.render = 111 { global.spr_voltorb = sprite_add("group\voltorb.png",2,1,1,0,0); sprite_index = global.spr_voltorb; global.current = "voltorb"; } 
if global.render = 112 { global.spr_wobbuffet = sprite_add("group\wobbuffet.png",2,1,1,0,0); sprite_index = global.spr_wobbuffet; global.current = "wobbuffet"; } 
if global.render = 113 { global.spr_tentacool = sprite_add("group\tentacool.png",2,1,1,0,0); sprite_index = global.spr_tentacool; global.current = "tentacool"; } 
if global.render = 114 { global.spr_shuckle = sprite_add("group\shuckle.png",2,1,1,0,0); sprite_index = global.spr_shuckle; global.current = "shuckle"; } 
if global.render = 115 { global.spr_sneakypebbles = sprite_add("group\sneakypebbles.png",2,1,1,0,0); sprite_index = global.spr_sneakypebbles; global.current = "sneakypebbles"; } 
if global.render = 116 { global.spr_natu = sprite_add("group\natu.png",2,1,1,0,0); sprite_index = global.spr_natu; global.current = "natu"; } 
if global.render = 117 { global.spr_trapinch = sprite_add("group\trapinch.png",2,1,1,0,0); sprite_index = global.spr_trapinch; global.current = "trapinch"; } 
if global.render = 118 { global.spr_cofagrigus = sprite_add("group\cofagrigus.png",2,1,1,0,0); sprite_index = global.spr_cofagrigus; global.current = "cofagrigus"; } 
if global.render = 119 { global.spr_mienshao = sprite_add("group\mienshao.png",2,1,1,0,0); sprite_index = global.spr_mienshao; global.current = "mienshao"; } 
if global.render = 120 { global.spr_baitfish = sprite_add("group\baitfish.png",2,1,1,0,0); sprite_index = global.spr_baitfish; global.current = "baitfish"; } 
if global.render = 121 { global.spr_mudkip = sprite_add("group\mudkip.png",2,1,1,0,0); sprite_index = global.spr_mudkip; global.current = "mudkip"; } 
if global.render = 122 { global.spr_zangoose = sprite_add("group\zangoose.png",2,1,1,0,0); sprite_index = global.spr_zangoose; global.current = "zangoose"; } 
if global.render = 123 { global.spr_audino = sprite_add("group\audino.png",2,1,1,0,0); sprite_index = global.spr_audino; global.current = "audino"; } 
if global.render = 124 { global.spr_vibrava = sprite_add("group\vibrava.png",2,1,1,0,0); sprite_index = global.spr_vibrava; global.current = "vibrava"; } 
if global.render = 125 { global.spr_insidetheflyingmachine = sprite_add("group\insidetheflyingmachine.png",2,1,1,0,0); sprite_index = global.spr_insidetheflyingmachine; global.current = "insidetheflyingmachine"; } 
if global.render = 126 { global.spr_azelf = sprite_add("group\azelf.png",2,1,1,0,0); sprite_index = global.spr_azelf; global.current = "azelf"; } 
if global.render = 127 { global.spr_cancer = sprite_add("group\cancer.png",2,1,1,0,0); sprite_index = global.spr_cancer; global.current = "cancer"; } 
if global.render = 128 { global.spr_cryogonal = sprite_add("group\cryogonal.png",2,1,1,0,0); sprite_index = global.spr_cryogonal; global.current = "cryogonal"; } 
if global.render = 129 { global.spr_flygon = sprite_add("group\flygon.png",2,1,1,0,0); sprite_index = global.spr_flygon; global.current = "flygon"; } 
if global.render = 130 { global.spr_pinkiepie = sprite_add("group\pinkiepie.png",2,1,1,0,0); sprite_index = global.spr_pinkiepie; global.current = "pinkiepie"; } 
if global.render = 131 { global.spr_uxie = sprite_add("group\uxie.png",2,1,1,0,0); sprite_index = global.spr_uxie; global.current = "uxie"; } 
if global.render = 132 { global.spr_throh = sprite_add("group\throh.png",2,1,1,0,0); sprite_index = global.spr_throh; global.current = "throh"; } 
if global.render = 133 { global.spr_swanna = sprite_add("group\swanna.png",2,1,1,0,0); sprite_index = global.spr_swanna; global.current = "swanna"; } 
if global.render = 134 { global.spr_geno = sprite_add("group\geno.png",2,1,1,0,0); sprite_index = global.spr_geno; global.current = "geno"; } 
if global.render = 135 { global.spr_mesprit = sprite_add("group\mesprit.png",2,1,1,0,0); sprite_index = global.spr_mesprit; global.current = "mesprit"; } 
if global.render = 136 { global.spr_marshtomp = sprite_add("group\marshtomp.png",2,1,1,0,0); sprite_index = global.spr_marshtomp; global.current = "marshtomp"; } 
if global.render = 137 { global.spr_pokemonegg = sprite_add("group\pokemonegg.png",2,1,1,0,0); sprite_index = global.spr_pokemonegg; global.current = "pokemonegg"; } 
if global.render = 138 { global.spr_pyramidhead = sprite_add("group\pyramidhead.png",2,1,1,0,0); sprite_index = global.spr_pyramidhead; global.current = "pyramidhead"; } 
if global.render = 139 { global.spr_absol = sprite_add("group\absol.png",2,1,1,0,0); sprite_index = global.spr_absol; global.current = "absol"; } 
if global.render = 140 { global.spr_sanic = sprite_add("group\sanic.png",2,1,1,0,0); sprite_index = global.spr_sanic; global.current = "sanic"; } 
if global.render = 141 { global.spr_saniclil = sprite_add("group\saniclil.png",2,1,1,0,0); sprite_index = global.spr_saniclil; global.current = "saniclil"; } 
if global.render = 142 { global.spr_poisonmushroom = sprite_add("group\poisonmushroom.png",2,1,1,0,0); sprite_index = global.spr_poisonmushroom; global.current = "poisonmushroom"; } 
if global.render = 143 { global.spr_druddigon = sprite_add("group\druddigon.png",2,1,1,0,0); sprite_index = global.spr_druddigon; global.current = "druddigon"; } 
if global.render = 144 { global.spr_gardevoir = sprite_add("group\gardevoir.png",2,1,1,0,0); sprite_index = global.spr_gardevoir; global.current = "gardevoir"; } 
if global.render = 145 { global.spr_twilightsparkle = sprite_add("group\twilightsparkle.png",2,1,1,0,0); sprite_index = global.spr_twilightsparkle; global.current = "twilightsparkle"; } 
if global.render = 146 { global.spr_doge = sprite_add("group\doge.png",2,1,1,0,0); sprite_index = global.spr_doge; global.current = "doge"; } 
if global.render = 147 { global.spr_nito = sprite_add("group\nito.png",2,1,1,0,0); sprite_index = global.spr_nito; global.current = "nito"; } 
if global.render = 148 { global.spr_seaththescaleless = sprite_add("group\seaththescaleless.png",2,1,1,0,0); sprite_index = global.spr_seaththescaleless; global.current = "seaththescaleless"; } 
if global.render = 149 { global.spr_uboa = sprite_add("group\uboa.png",2,1,1,0,0); sprite_index = global.spr_uboa; global.current = "uboa"; } 
if global.render = 150 { global.spr_penetrator = sprite_add("group\penetrator.png",2,1,1,0,0); sprite_index = global.spr_penetrator; global.current = "penetrator"; } 
if global.render = 151 { global.spr_towerknight = sprite_add("group\towerknight.png",2,1,1,0,0); sprite_index = global.spr_towerknight; global.current = "towerknight"; } 
if global.render = 152 { global.spr_rainbowdash = sprite_add("group\rainbowdash.png",2,1,1,0,0); sprite_index = global.spr_rainbowdash; global.current = "rainbowdash"; } 
if global.render = 153 { global.spr_zerotwo = sprite_add("group\zerotwo.png",2,1,1,0,0); sprite_index = global.spr_zerotwo; global.current = "zerotwo"; } 
if global.render = 154 { global.spr_adjudicator = sprite_add("group\adjudicator.png",2,1,1,0,0); sprite_index = global.spr_adjudicator; global.current = "adjudicator"; } 
if global.render = 155 { global.spr_smough = sprite_add("group\smough.png",2,1,1,0,0); sprite_index = global.spr_smough; global.current = "smough"; } 
if global.render = 156 { global.spr_ornstein = sprite_add("group\ornstein.png",2,1,1,0,0); sprite_index = global.spr_ornstein; global.current = "ornstein"; } 
if global.render = 157 { global.spr_madotsuki = sprite_add("group\madotsuki.png",2,1,1,0,0); sprite_index = global.spr_madotsuki; global.current = "madotsuki"; } 
if global.render = 158 { global.spr_kirby = sprite_add("group\kirby.png",2,1,1,0,0); sprite_index = global.spr_kirby; global.current = "kirby"; } 
if global.render = 159 { global.spr_luvdisc = sprite_add("group\luvdisc.png",2,1,1,0,0); sprite_index = global.spr_luvdisc; global.current = "luvdisc"; } 
if global.render = 160 { global.spr_honedge = sprite_add("group\honedge.png",2,1,1,0,0); sprite_index = global.spr_honedge; global.current = "honedge"; } 
if global.render = 161 { global.spr_trevenant = sprite_add("group\trevenant.png",2,1,1,0,0); sprite_index = global.spr_trevenant; global.current = "trevenant"; } 
if global.render = 162 { global.spr_xerneas = sprite_add("group\xerneas.png",2,1,1,0,0); sprite_index = global.spr_xerneas; global.current = "xerneas"; } 
if global.render = 163 { global.spr_slenderman = sprite_add("group\slenderman.png",2,1,1,0,0); sprite_index = global.spr_slenderman; global.current = "slenderman"; } 
if global.render = 164 { global.spr_chikorita = sprite_add("group\chikorita.png",2,1,1,0,0); sprite_index = global.spr_chikorita; global.current = "chikorita"; } 
if global.render = 165 { global.spr_honchkrow = sprite_add("group\honchkrow.png",2,1,1,0,0); sprite_index = global.spr_honchkrow; global.current = "honchkrow"; } 
if global.render = 166 { global.spr_applejack = sprite_add("group\applejack.png",2,1,1,0,0); sprite_index = global.spr_applejack; global.current = "applejack"; } 
if global.render = 167 { global.spr_muricaneagle = sprite_add("group\muricaneagle.png",2,1,1,0,0); sprite_index = global.spr_muricaneagle; global.current = "muricaneagle"; } 
if global.render = 168 { global.spr_duckhunt = sprite_add("group\duckhunt.png",2,1,1,0,0); sprite_index = global.spr_duckhunt; global.current = "duckhunt"; } 
if global.render = 169 { global.spr_duckhunt2 = sprite_add("group\duckhunt2.png",2,1,1,0,0); sprite_index = global.spr_duckhunt2; global.current = "duckhunt2"; } 
if global.render = 170 { global.spr_duckhunt3 = sprite_add("group\duckhunt3.png",2,1,1,0,0); sprite_index = global.spr_duckhunt3; global.current = "duckhunt3"; } 
if global.render = 171 { global.spr_wacky = sprite_add("group\wacky.png",2,1,1,0,0); sprite_index = global.spr_wacky; global.current = "wacky"; } 
if global.render = 172 { global.spr_rarity = sprite_add("group\rarity.png",2,1,1,0,0); sprite_index = global.spr_rarity; global.current = "rarity"; } 
if global.render = 173 { global.spr_wooper = sprite_add("group\wooper.png",2,1,1,0,0); sprite_index = global.spr_wooper; global.current = "wooper"; } 
if global.render = 174 { global.spr_hypno = sprite_add("group\hypno.png",2,1,1,0,0); sprite_index = global.spr_hypno; global.current = "hypno"; } 
if global.render = 175 { global.spr_talonflame = sprite_add("group\talonflame.png",2,1,1,0,0); sprite_index = global.spr_talonflame; global.current = "talonflame"; } 
if global.render = 176 { global.spr_isaac = sprite_add("group\isaac.png",2,1,1,0,0); sprite_index = global.spr_isaac; global.current = "isaac"; } 
if global.render = 177 { global.spr_crustle = sprite_add("group\crustle.png",2,1,1,0,0); sprite_index = global.spr_crustle; global.current = "crustle"; } 
if global.render = 178 { global.spr_gigalith = sprite_add("group\gigalith.png",2,1,1,0,0); sprite_index = global.spr_gigalith; global.current = "gigalith"; } 
if global.render = 179 { global.spr_meatboy = sprite_add("group\meatboy.png",2,1,1,0,0); sprite_index = global.spr_meatboy; global.current = "meatboy"; } 
if global.render = 180 { global.spr_fluttershy = sprite_add("group\fluttershy.png",2,1,1,0,0); sprite_index = global.spr_fluttershy; global.current = "fluttershy"; } 
if global.render = 181 { global.spr_geralt = sprite_add("group\geralt.png",2,1,1,0,0); sprite_index = global.spr_geralt; global.current = "geralt"; } 
if global.render = 182 { global.spr_megaampharos = sprite_add("group\megaampharos.png",2,1,1,0,0); sprite_index = global.spr_megaampharos; global.current = "megaampharos"; } 
if global.render = 183 { global.spr_nosepass = sprite_add("group\nosepass.png",2,1,1,0,0); sprite_index = global.spr_nosepass; global.current = "nosepass"; } 
if global.render = 184 { global.spr_mew = sprite_add("group\mew.png",2,1,1,0,0); sprite_index = global.spr_mew; global.current = "mew"; } 
if global.render = 185 { global.spr_dialga = sprite_add("group\dialga.png",2,1,1,0,0); sprite_index = global.spr_dialga; global.current = "dialga"; } 
if global.render = 186 { global.spr_ampharos = sprite_add("group\ampharos.png",2,1,1,0,0); sprite_index = global.spr_ampharos; global.current = "ampharos"; } 
if global.render = 187 { global.spr_nyarlathoep = sprite_add("group\nyarlathoep.png",2,1,1,0,0); sprite_index = global.spr_nyarlathoep; global.current = "nyarlathoep"; } 
if global.render = 188 { global.spr_latias = sprite_add("group\latias.png",2,1,1,0,0); sprite_index = global.spr_latias; global.current = "latias"; } 
if global.render = 189 { global.spr_cthulhu = sprite_add("group\cthulhu.png",2,1,1,0,0); sprite_index = global.spr_cthulhu; global.current = "cthulhu"; } 
if global.render = 190 { global.spr_latios = sprite_add("group\latios.png",2,1,1,0,0); sprite_index = global.spr_latios; global.current = "latios"; } 
if global.render = 191 { global.spr_stantler = sprite_add("group\stantler.png",2,1,1,0,0); sprite_index = global.spr_stantler; global.current = "stantler"; } 
if global.render = 192 { global.spr_yogsothoth = sprite_add("group\yogsothoth.png",2,1,1,0,0); sprite_index = global.spr_yogsothoth; global.current = "yogsothoth"; } 
if global.render = 193 { global.spr_pingu = sprite_add("group\pingu.png",2,1,1,0,0); sprite_index = global.spr_pingu; global.current = "pingu"; } 
if global.render = 194 { global.spr_palkia = sprite_add("group\palkia.png",2,1,1,0,0); sprite_index = global.spr_palkia; global.current = "palkia"; } 
if global.render = 195 { global.spr_shoggoth = sprite_add("group\shoggoth.png",2,1,1,0,0); sprite_index = global.spr_shoggoth; global.current = "shoggoth"; } 
if global.render = 196 { global.spr_smeargle = sprite_add("group\smeargle.png",2,1,1,0,0); sprite_index = global.spr_smeargle; global.current = "smeargle"; } 
if global.render = 197 { global.spr_bayleaf = sprite_add("group\bayleaf.png",2,1,1,0,0); sprite_index = global.spr_bayleaf; global.current = "bayleaf"; } 
if global.render = 198 { global.spr_megablaziken = sprite_add("group\megablaziken.png",2,1,1,0,0); sprite_index = global.spr_megablaziken; global.current = "megablaziken"; } 
if global.render = 199 { global.spr_ghroth = sprite_add("group\ghroth.png",2,1,1,0,0); sprite_index = global.spr_ghroth; global.current = "ghroth"; } 
if global.render = 200 { global.spr_megamawile = sprite_add("group\megamawile.png",2,1,1,0,0); sprite_index = global.spr_megamawile; global.current = "megamawile"; } 
if global.render = 201 { global.spr_tailow = sprite_add("group\tailow.png",2,1,1,0,0); sprite_index = global.spr_tailow; global.current = "tailow"; } 
if global.render = 202 { global.spr_weedle = sprite_add("group\weedle.png",2,1,1,0,0); sprite_index = global.spr_weedle; global.current = "weedle"; } 
if global.render = 203 { global.spr_swellow = sprite_add("group\swellow.png",2,1,1,0,0); sprite_index = global.spr_swellow; global.current = "swellow"; } 
if global.render = 204 { global.spr_koffing = sprite_add("group\koffing.png",2,1,1,0,0); sprite_index = global.spr_koffing; global.current = "koffing"; } 
if global.render = 205 { global.spr_snorunt = sprite_add("group\snorunt.png",2,1,1,0,0); sprite_index = global.spr_snorunt; global.current = "snorunt"; } 
if global.render = 206 { global.spr_linux = sprite_add("group\linux.png",2,1,1,0,0); sprite_index = global.spr_linux; global.current = "linux"; } 
if global.render = 207 { global.spr_sableye = sprite_add("group\sableye.png",2,1,1,0,0); sprite_index = global.spr_sableye; global.current = "sableye"; } 
if global.render = 208 { global.spr_spike = sprite_add("group\spike.png",2,1,1,0,0); sprite_index = global.spr_spike; global.current = "spike"; } 
if global.render = 209 { global.spr_elderthing = sprite_add("group\elderthing.png",2,1,1,0,0); sprite_index = global.spr_elderthing; global.current = "elderthing"; } 
if global.render = 210 { global.spr_shadowlurkerm = sprite_add("group\shadowlurkerm.png",2,1,1,0,0); sprite_index = global.spr_shadowlurkerm; global.current = "shadowlurkerm"; } 
if global.render = 211 { global.spr_ostrava = sprite_add("group\ostrava.png",2,1,1,0,0); sprite_index = global.spr_ostrava; global.current = "ostrava"; } 
if global.render = 212 { global.spr_havel = sprite_add("group\havel.png",2,1,1,0,0); sprite_index = global.spr_havel; global.current = "havel"; } 
if global.render = 213 { global.spr_ferroseed = sprite_add("group\ferroseed.png",2,1,1,0,0); sprite_index = global.spr_ferroseed; global.current = "ferroseed"; } 
if global.render = 214 { global.spr_meganium = sprite_add("group\meganium.png",2,1,1,0,0); sprite_index = global.spr_meganium; global.current = "meganium"; } 
if global.render = 215 { global.spr_sudowoodo = sprite_add("group\sudowoodo.png",2,1,1,0,0); sprite_index = global.spr_sudowoodo; global.current = "sudowoodo"; } 
if global.render = 216 { global.spr_gulpin = sprite_add("group\gulpin.png",2,1,1,0,0); sprite_index = global.spr_gulpin; global.current = "gulpin"; } 
if global.render = 217 { global.spr_rambi = sprite_add("group\rambi.png",2,1,1,0,0); sprite_index = global.spr_rambi; global.current = "rambi"; } 
if global.render = 218 { global.spr_princesscelestia = sprite_add("group\princesscelestia.png",2,1,1,0,0); sprite_index = global.spr_princesscelestia; global.current = "princesscelestia"; } 
if global.render = 219 { global.spr_marvelouschester = sprite_add("group\marvelouschester.png",2,1,1,0,0); sprite_index = global.spr_marvelouschester; global.current = "marvelouschester"; } 
if global.render = 220 { global.spr_snover = sprite_add("group\snover.png",2,1,1,0,0); sprite_index = global.spr_snover; global.current = "snover"; } 
if global.render = 221 { global.spr_artorias = sprite_add("group\artorias.png",2,1,1,0,0); sprite_index = global.spr_artorias; global.current = "artorias"; } 
if global.render = 222 { global.spr_abomasnow = sprite_add("group\abomasnow.png",2,1,1,0,0); sprite_index = global.spr_abomasnow; global.current = "abomasnow"; } 
if global.render = 223 { global.spr_tangrowth = sprite_add("group\tangrowth.png",2,1,1,0,0); sprite_index = global.spr_tangrowth; global.current = "tangrowth"; } 
if global.render = 224 { global.spr_haxorus = sprite_add("group\haxorus.png",2,1,1,0,0); sprite_index = global.spr_haxorus; global.current = "haxorus"; } 
if global.render = 225 { global.spr_surskit = sprite_add("group\surskit.png",2,1,1,0,0); sprite_index = global.spr_surskit; global.current = "surskit"; } 
if global.render = 226 { global.spr_oneofthefourwings = sprite_add("group\oneofthefourwings.png",2,1,1,0,0); sprite_index = global.spr_oneofthefourwings; global.current = "oneofthefourwings"; } 
if global.render = 227 { global.spr_maneatermildred = sprite_add("group\maneatermildred.png",2,1,1,0,0); sprite_index = global.spr_maneatermildred; global.current = "maneatermildred"; } 
if global.render = 228 { global.spr_megaman = sprite_add("group\megaman.png",2,1,1,0,0); sprite_index = global.spr_megaman; global.current = "megaman"; } 
if global.render = 229 { global.spr_squiddle = sprite_add("group\squiddle.png",2,1,1,0,0); sprite_index = global.spr_squiddle; global.current = "squiddle"; } 
if global.render = 230 { global.spr_sawsbuckwinter = sprite_add("group\sawsbuckwinter.png",2,1,1,0,0); sprite_index = global.spr_sawsbuckwinter; global.current = "sawsbuckwinter"; } 
if global.render = 231 { global.spr_porygonz = sprite_add("group\porygonz.png",2,1,1,0,0); sprite_index = global.spr_porygonz; global.current = "porygonz"; } 
if global.render = 232 { global.spr_ciarin = sprite_add("group\ciarin.png",2,1,1,0,0); sprite_index = global.spr_ciarin; global.current = "ciarin"; } 
if global.render = 233 { global.spr_sawsbuckspring = sprite_add("group\sawsbuckspring.png",2,1,1,0,0); sprite_index = global.spr_sawsbuckspring; global.current = "sawsbuckspring"; } 
if global.render = 234 { global.spr_sawsbucksummer = sprite_add("group\sawsbucksummer.png",2,1,1,0,0); sprite_index = global.spr_sawsbucksummer; global.current = "sawsbucksummer"; } 
if global.render = 235 { global.spr_sawsbuckautumn = sprite_add("group\sawsbuckautumn.png",2,1,1,0,0); sprite_index = global.spr_sawsbuckautumn; global.current = "sawsbuckautumn"; } 
if global.render = 236 { global.spr_stunfisk = sprite_add("group\stunfisk.png",2,1,1,0,0); sprite_index = global.spr_stunfisk; global.current = "stunfisk"; } 
if global.render = 237 { global.spr_starly = sprite_add("group\starly.png",2,1,1,0,0); sprite_index = global.spr_starly; global.current = "starly"; } 
if global.render = 238 { global.spr_lautrec = sprite_add("group\lautrec.png",2,1,1,0,0); sprite_index = global.spr_lautrec; global.current = "lautrec"; } 
if global.render = 239 { global.spr_musharna = sprite_add("group\musharna.png",2,1,1,0,0); sprite_index = global.spr_musharna; global.current = "musharna"; } 
if global.render = 240 { global.spr_munna = sprite_add("group\munna.png",2,1,1,0,0); sprite_index = global.spr_munna; global.current = "munna"; } 
if global.render = 241 { global.spr_porygon2 = sprite_add("group\porygon2.png",2,1,1,0,0); sprite_index = global.spr_porygon2; global.current = "porygon2"; } 
if global.render = 242 { global.spr_doran = sprite_add("group\doran.png",2,1,1,0,0); sprite_index = global.spr_doran; global.current = "doran"; } 
if global.render = 243 { global.spr_sunkern = sprite_add("group\sunkern.png",2,1,1,0,0); sprite_index = global.spr_sunkern; global.current = "sunkern"; } 
if global.render = 244 { global.spr_porygon = sprite_add("group\porygon.png",2,1,1,0,0); sprite_index = global.spr_porygon; global.current = "porygon"; } 
if global.render = 245 { global.spr_sunflora = sprite_add("group\sunflora.png",2,1,1,0,0); sprite_index = global.spr_sunflora; global.current = "sunflora"; } 
if global.render = 246 { global.spr_scizor = sprite_add("group\scizor.png",2,1,1,0,0); sprite_index = global.spr_scizor; global.current = "scizor"; } 
if global.render = 247 { global.spr_foongus = sprite_add("group\foongus.png",2,1,1,0,0); sprite_index = global.spr_foongus; global.current = "foongus"; } 
if global.render = 248 { global.spr_amoongus = sprite_add("group\amoongus.png",2,1,1,0,0); sprite_index = global.spr_amoongus; global.current = "amoongus"; } 
if global.render = 249 { global.spr_silcoon = sprite_add("group\silcoon.png",2,1,1,0,0); sprite_index = global.spr_silcoon; global.current = "silcoon"; } 
if global.render = 250 { global.spr_cascoon = sprite_add("group\cascoon.png",2,1,1,0,0); sprite_index = global.spr_cascoon; global.current = "cascoon"; } 
if global.render = 251 { global.spr_duskull = sprite_add("group\duskull.png",2,1,1,0,0); sprite_index = global.spr_duskull; global.current = "duskull"; } 
if global.render = 252 { global.spr_probopass = sprite_add("group\probopass.png",2,1,1,0,0); sprite_index = global.spr_probopass; global.current = "probopass"; } 
if global.render = 253 { global.spr_lampent = sprite_add("group\lampent.png",2,1,1,0,0); sprite_index = global.spr_lampent; global.current = "lampent"; } 
if global.render = 254 { global.spr_girafarig = sprite_add("group\girafarig.png",2,1,1,0,0); sprite_index = global.spr_girafarig; global.current = "girafarig"; } 
if global.render = 255 { global.spr_murkrow = sprite_add("group\murkrow.png",2,1,1,0,0); sprite_index = global.spr_murkrow; global.current = "murkrow"; } 
if global.render = 256 { global.spr_maractus = sprite_add("group\maractus.png",2,1,1,0,0); sprite_index = global.spr_maractus; global.current = "maractus"; } 
if global.render = 257 { global.spr_jellyfish = sprite_add("group\jellyfish.png",2,1,1,0,0); sprite_index = global.spr_jellyfish; global.current = "jellyfish"; } 
if global.render = 258 { global.spr_rapidash = sprite_add("group\rapidash.png",2,1,1,0,0); sprite_index = global.spr_rapidash; global.current = "rapidash"; } 
if global.render = 259 { global.spr_rufflet = sprite_add("group\rufflet.png",2,1,1,0,0); sprite_index = global.spr_rufflet; global.current = "rufflet"; } 
if global.render = 260 { global.spr_peliper = sprite_add("group\peliper.png",2,1,1,0,0); sprite_index = global.spr_peliper; global.current = "peliper"; } 
if global.render = 261 { global.spr_quote = sprite_add("group\quote.png",2,1,1,0,0); sprite_index = global.spr_quote; global.current = "quote"; } 
if global.render = 262 { global.spr_curlybrace = sprite_add("group\curlybrace.png",2,1,1,0,0); sprite_index = global.spr_curlybrace; global.current = "curlybrace"; } 
if global.render = 263 { global.spr_cyndaquil = sprite_add("group\cyndaquil.png",2,1,1,0,0); sprite_index = global.spr_cyndaquil; global.current = "cyndaquil"; } 
if global.render = 264 { global.spr_piranhaplant = sprite_add("group\piranhaplant.png",2,1,1,0,0); sprite_index = global.spr_piranhaplant; global.current = "piranhaplant"; } 
if global.render = 265 { global.spr_braviary = sprite_add("group\braviary.png",2,1,1,0,0); sprite_index = global.spr_braviary; global.current = "braviary"; } 
if global.render = 266 { global.spr_conkeldurr = sprite_add("group\conkeldurr.png",2,1,1,0,0); sprite_index = global.spr_conkeldurr; global.current = "conkeldurr"; } 
if global.render = 267 { global.spr_yamask = sprite_add("group\yamask.png",2,1,1,0,0); sprite_index = global.spr_yamask; global.current = "yamask"; } 
if global.render = 268 { global.spr_croagunk = sprite_add("group\croagunk.png",2,1,1,0,0); sprite_index = global.spr_croagunk; global.current = "croagunk"; } 
if global.render = 269 { global.spr_lumineon = sprite_add("group\lumineon.png",2,1,1,0,0); sprite_index = global.spr_lumineon; global.current = "lumineon"; } 
if global.render = 270 { global.spr_scraggy = sprite_add("group\scraggy.png",2,1,1,0,0); sprite_index = global.spr_scraggy; global.current = "scraggy"; } 
if global.render = 271 { global.spr_toxicroak = sprite_add("group\toxicroak.png",2,1,1,0,0); sprite_index = global.spr_toxicroak; global.current = "toxicroak"; } 
if global.render = 272 { global.spr_vanillish = sprite_add("group\vanillish.png",2,1,1,0,0); sprite_index = global.spr_vanillish; global.current = "vanillish"; } 
if global.render = 273 { global.spr_princessluna = sprite_add("group\princessluna.png",2,1,1,0,0); sprite_index = global.spr_princessluna; global.current = "princessluna"; } 
if global.render = 274 { global.spr_staryu = sprite_add("group\staryu.png",2,1,1,0,0); sprite_index = global.spr_staryu; global.current = "staryu"; } 
if global.render = 275 { global.spr_scrafty = sprite_add("group\scrafty.png",2,1,1,0,0); sprite_index = global.spr_scrafty; global.current = "scrafty"; } 
if global.render = 276 { global.spr_raven = sprite_add("group\raven.png",2,1,1,0,0); sprite_index = global.spr_raven; global.current = "raven"; } 
if global.render = 277 { global.spr_starmie = sprite_add("group\starmie.png",2,1,1,0,0); sprite_index = global.spr_starmie; global.current = "starmie"; } 
if global.render = 278 { global.spr_sneasel = sprite_add("group\sneasel.png",2,1,1,0,0); sprite_index = global.spr_sneasel; global.current = "sneasel"; } 
if global.render = 279 { global.spr_vanilluxe = sprite_add("group\vanilluxe.png",2,1,1,0,0); sprite_index = global.spr_vanilluxe; global.current = "vanilluxe"; } 
if global.render = 280 { global.spr_zoroark = sprite_add("group\zoroark.png",2,1,1,0,0); sprite_index = global.spr_zoroark; global.current = "zoroark"; } 
if global.render = 281 { global.spr_dusknoir = sprite_add("group\dusknoir.png",2,1,1,0,0); sprite_index = global.spr_dusknoir; global.current = "dusknoir"; } 
if global.render = 282 { global.spr_tentaquil = sprite_add("group\tentaquil.png",2,1,1,0,0); sprite_index = global.spr_tentaquil; global.current = "tentaquil"; } 
if global.render = 283 { global.spr_mienfoo = sprite_add("group\mienfoo.png",2,1,1,0,0); sprite_index = global.spr_mienfoo; global.current = "mienfoo"; } 
if global.render = 284 { global.spr_strongbad = sprite_add("group\strongbad.png",2,1,1,0,0); sprite_index = global.spr_strongbad; global.current = "strongbad"; } 
if global.render = 285 { global.spr_dante = sprite_add("group\dante.png",2,1,1,0,0); sprite_index = global.spr_dante; global.current = "dante"; } 
if global.render = 286 { global.spr_torchic = sprite_add("group\torchic.png",2,1,1,0,0); sprite_index = global.spr_torchic; global.current = "torchic"; } 
if global.render = 287 { global.spr_cradily = sprite_add("group\cradily.png",2,1,1,0,0); sprite_index = global.spr_cradily; global.current = "cradily"; } 
if global.render = 288 { global.spr_catinthehat = sprite_add("group\catinthehat.png",2,1,1,0,0); sprite_index = global.spr_catinthehat; global.current = "catinthehat"; } 
if global.render = 289 { global.spr_homestar = sprite_add("group\homestar.png",2,1,1,0,0); sprite_index = global.spr_homestar; global.current = "homestar"; } 
if global.render = 290 { global.spr_foliat = sprite_add("group\foliat.png",2,1,1,0,0); sprite_index = global.spr_foliat; global.current = "foliat"; } 
if global.render = 291 { global.spr_lileep = sprite_add("group\lileep.png",2,1,1,0,0); sprite_index = global.spr_lileep; global.current = "lileep"; } 
if global.render = 292 { global.spr_trogdor = sprite_add("group\trogdor.png",2,1,1,0,0); sprite_index = global.spr_trogdor; global.current = "trogdor"; } 
if global.render = 293 { global.spr_florabri = sprite_add("group\florabri.png",2,1,1,0,0); sprite_index = global.spr_florabri; global.current = "florabri"; } 
if global.render = 294 { global.spr_timburr = sprite_add("group\timburr.png",2,1,1,0,0); sprite_index = global.spr_timburr; global.current = "timburr"; } 
if global.render = 295 { global.spr_florresum = sprite_add("group\florresum.png",2,1,1,0,0); sprite_index = global.spr_florresum; global.current = "florresum"; } 
if global.render = 296 { global.spr_omanyte = sprite_add("group\omanyte.png",2,1,1,0,0); sprite_index = global.spr_omanyte; global.current = "omanyte"; } 
if global.render = 297 { global.spr_masquerain = sprite_add("group\masquerain.png",2,1,1,0,0); sprite_index = global.spr_masquerain; global.current = "masquerain"; } 
if global.render = 298 { global.spr_registeel = sprite_add("group\registeel.png",2,1,1,0,0); sprite_index = global.spr_registeel; global.current = "registeel"; } 
if global.render = 299 { global.spr_swampert = sprite_add("group\swampert.png",2,1,1,0,0); sprite_index = global.spr_swampert; global.current = "swampert"; } 
if global.render = 300 { global.spr_spiritomb = sprite_add("group\spiritomb.png",2,1,1,0,0); sprite_index = global.spr_spiritomb; global.current = "spiritomb"; } 
if global.render = 301 { global.spr_regice = sprite_add("group\regice.png",2,1,1,0,0); sprite_index = global.spr_regice; global.current = "regice"; } 
if global.render = 302 { global.spr_sonichu = sprite_add("group\sonichu.png",2,1,1,0,0); sprite_index = global.spr_sonichu; global.current = "sonichu"; } 
if global.render = 303 { global.spr_regirock = sprite_add("group\regirock.png",2,1,1,0,0); sprite_index = global.spr_regirock; global.current = "regirock"; } 
if global.render = 304 { global.spr_ferrothorn = sprite_add("group\ferrothorn.png",2,1,1,0,0); sprite_index = global.spr_ferrothorn; global.current = "ferrothorn"; } 
if global.render = 305 { global.spr_substitute = sprite_add("group\substitute.png",2,1,1,0,0); sprite_index = global.spr_substitute; global.current = "substitute"; } 
if global.render = 306 { global.spr_rosechu = sprite_add("group\rosechu.png",2,1,1,0,0); sprite_index = global.spr_rosechu; global.current = "rosechu"; } 
if global.render = 307 { global.spr_leghorse = sprite_add("group\leghorse.png",2,1,1,0,0); sprite_index = global.spr_leghorse; global.current = "leghorse"; } 
if global.render = 308 { global.spr_vanillite = sprite_add("group\vanillite.png",2,1,1,0,0); sprite_index = global.spr_vanillite; global.current = "vanillite"; } 
if global.render = 309 { global.spr_ghostpokemon = sprite_add("group\ghostpokemon.png",2,1,1,0,0); sprite_index = global.spr_ghostpokemon; global.current = "ghostpokemon"; } 
if global.render = 310 { global.spr_gurdurr = sprite_add("group\gurdurr.png",2,1,1,0,0); sprite_index = global.spr_gurdurr; global.current = "gurdurr"; } 
if global.render = 311 { global.spr_creeper = sprite_add("group\creeper.png",2,1,1,0,0); sprite_index = global.spr_creeper; global.current = "creeper"; } 
if global.render = 312 { global.spr_enderman = sprite_add("group\enderman.png",2,1,1,0,0); sprite_index = global.spr_enderman; global.current = "enderman"; } 
if global.render = 313 { global.spr_silverfish = sprite_add("group\silverfish.png",2,1,1,0,0); sprite_index = global.spr_silverfish; global.current = "silverfish"; } 
if global.render = 314 { global.spr_slimecube = sprite_add("group\slimecube.png",2,1,1,0,0); sprite_index = global.spr_slimecube; global.current = "slimecube"; } 
if global.render = 315 { global.spr_magmacube = sprite_add("group\magmacube.png",2,1,1,0,0); sprite_index = global.spr_magmacube; global.current = "magmacube"; } 
if global.render = 316 { global.spr_wither = sprite_add("group\wither.png",2,1,1,0,0); sprite_index = global.spr_wither; global.current = "wither"; } 
if global.render = 317 { global.spr_beholder = sprite_add("group\beholder.png",2,1,1,0,0); sprite_index = global.spr_beholder; global.current = "beholder"; } 
if global.render = 318 { global.spr_beholdereyeoffrost = sprite_add("group\beholdereyeoffrost.png",2,1,1,0,0); sprite_index = global.spr_beholdereyeoffrost; global.current = "beholdereyeoffrost"; } 
if global.render = 319 { global.spr_beholdereyeofchaos = sprite_add("group\beholdereyeofchaos.png",2,1,1,0,0); sprite_index = global.spr_beholdereyeofchaos; global.current = "beholdereyeofchaos"; } 
if global.render = 320 { global.spr_swablu = sprite_add("group\swablu.png",2,1,1,0,0); sprite_index = global.spr_swablu; global.current = "swablu"; } 
if global.render = 321 { global.spr_vivillionmeadow = sprite_add("group\vivillionmeadow.png",2,1,1,0,0); sprite_index = global.spr_vivillionmeadow; global.current = "vivillionmeadow"; } 
if global.render = 322 { global.spr_missingno = sprite_add("group\missingno.png",2,1,1,0,0); sprite_index = global.spr_missingno; global.current = "missingno"; } 
if global.render = 323 { global.spr_unowna = sprite_add("group\unowna.png",2,1,1,0,0); sprite_index = global.spr_unowna; global.current = "unowna"; } 
if global.render = 324 { global.spr_unownb = sprite_add("group\unownb.png",2,1,1,0,0); sprite_index = global.spr_unownb; global.current = "unownb"; } 
if global.render = 325 { global.spr_unownc = sprite_add("group\unownc.png",2,1,1,0,0); sprite_index = global.spr_unownc; global.current = "unownc"; } 
if global.render = 326 { global.spr_unownd = sprite_add("group\unownd.png",2,1,1,0,0); sprite_index = global.spr_unownd; global.current = "unownd"; } 
if global.render = 327 { global.spr_unowne = sprite_add("group\unowne.png",2,1,1,0,0); sprite_index = global.spr_unowne; global.current = "unowne"; } 
if global.render = 328 { global.spr_unownf = sprite_add("group\unownf.png",2,1,1,0,0); sprite_index = global.spr_unownf; global.current = "unownf"; } 
if global.render = 329 { global.spr_unowng = sprite_add("group\unowng.png",2,1,1,0,0); sprite_index = global.spr_unowng; global.current = "unowng"; } 
if global.render = 330 { global.spr_unownh = sprite_add("group\unownh.png",2,1,1,0,0); sprite_index = global.spr_unownh; global.current = "unownh"; } 
if global.render = 331 { global.spr_unowni = sprite_add("group\unowni.png",2,1,1,0,0); sprite_index = global.spr_unowni; global.current = "unowni"; } 
if global.render = 332 { global.spr_unownj = sprite_add("group\unownj.png",2,1,1,0,0); sprite_index = global.spr_unownj; global.current = "unownj"; } 
if global.render = 333 { global.spr_unownk = sprite_add("group\unownk.png",2,1,1,0,0); sprite_index = global.spr_unownk; global.current = "unownk"; } 
if global.render = 334 { global.spr_unownl = sprite_add("group\unownl.png",2,1,1,0,0); sprite_index = global.spr_unownl; global.current = "unownl"; } 
if global.render = 335 { global.spr_unownm = sprite_add("group\unownm.png",2,1,1,0,0); sprite_index = global.spr_unownm; global.current = "unownm"; } 
if global.render = 336 { global.spr_unownn = sprite_add("group\unownn.png",2,1,1,0,0); sprite_index = global.spr_unownn; global.current = "unownn"; } 
if global.render = 337 { global.spr_unowno = sprite_add("group\unowno.png",2,1,1,0,0); sprite_index = global.spr_unowno; global.current = "unowno"; } 
if global.render = 338 { global.spr_unownp = sprite_add("group\unownp.png",2,1,1,0,0); sprite_index = global.spr_unownp; global.current = "unownp"; } 
if global.render = 339 { global.spr_unownq = sprite_add("group\unownq.png",2,1,1,0,0); sprite_index = global.spr_unownq; global.current = "unownq"; } 
if global.render = 340 { global.spr_unownr = sprite_add("group\unownr.png",2,1,1,0,0); sprite_index = global.spr_unownr; global.current = "unownr"; } 
if global.render = 341 { global.spr_unowns = sprite_add("group\unowns.png",2,1,1,0,0); sprite_index = global.spr_unowns; global.current = "unowns"; } 
if global.render = 342 { global.spr_unownt = sprite_add("group\unownt.png",2,1,1,0,0); sprite_index = global.spr_unownt; global.current = "unownt"; } 
if global.render = 343 { global.spr_unownu = sprite_add("group\unownu.png",2,1,1,0,0); sprite_index = global.spr_unownu; global.current = "unownu"; } 
if global.render = 344 { global.spr_unownv = sprite_add("group\unownv.png",2,1,1,0,0); sprite_index = global.spr_unownv; global.current = "unownv"; } 
if global.render = 345 { global.spr_unownw = sprite_add("group\unownw.png",2,1,1,0,0); sprite_index = global.spr_unownw; global.current = "unownw"; } 
if global.render = 346 { global.spr_unownx = sprite_add("group\unownx.png",2,1,1,0,0); sprite_index = global.spr_unownx; global.current = "unownx"; } 
if global.render = 347 { global.spr_unowny = sprite_add("group\unowny.png",2,1,1,0,0); sprite_index = global.spr_unowny; global.current = "unowny"; } 
if global.render = 348 { global.spr_unownz = sprite_add("group\unownz.png",2,1,1,0,0); sprite_index = global.spr_unownz; global.current = "unownz"; } 
if global.render = 349 { global.spr_unownexclamation = sprite_add("group\unownexclamation.png",2,1,1,0,0); sprite_index = global.spr_unownexclamation; global.current = "unownexclamation"; } 
if global.render = 350 { global.spr_unownquestion = sprite_add("group\unownquestion.png",2,1,1,0,0); sprite_index = global.spr_unownquestion; global.current = "unownquestion"; } 
if global.render = 351 { global.spr_avion = sprite_add("group\avion.png",2,1,1,0,0); sprite_index = global.spr_avion; global.current = "avion"; } 
if global.render = 352 { global.spr_gwyn = sprite_add("group\gwyn.png",2,1,1,0,0); sprite_index = global.spr_gwyn; global.current = "gwyn"; } 
if global.render = 353 { global.spr_manus = sprite_add("group\manus.png",2,1,1,0,0); sprite_index = global.spr_manus; global.current = "manus"; } 
if global.render = 354 { global.spr_quelaag = sprite_add("group\quelaag.png",2,1,1,0,0); sprite_index = global.spr_quelaag; global.current = "quelaag"; } 
if global.render = 355 { global.spr_shadowlurkerf = sprite_add("group\shadowlurkerf.png",2,1,1,0,0); sprite_index = global.spr_shadowlurkerf; global.current = "shadowlurkerf"; } 
if global.render = 356 { global.spr_agumon = sprite_add("group\agumon.png",2,1,1,0,0); sprite_index = global.spr_agumon; global.current = "agumon"; } 
if global.render = 357 { global.spr_kingallant = sprite_add("group\kingallant.png",2,1,1,0,0); sprite_index = global.spr_kingallant; global.current = "kingallant"; } 
if global.render = 358 { global.spr_blissey = sprite_add("group\blissey.png",2,1,1,0,0); sprite_index = global.spr_blissey; global.current = "blissey"; } 
if global.render = 359 { global.spr_oldmonk = sprite_add("group\oldmonk.png",2,1,1,0,0); sprite_index = global.spr_oldmonk; global.current = "oldmonk"; } 
if global.render = 360 { global.spr_gengar = sprite_add("group\gengar.png",2,1,1,0,0); sprite_index = global.spr_gengar; global.current = "gengar"; } 
if global.render = 361 { global.spr_stormking = sprite_add("group\stormking.png",2,1,1,0,0); sprite_index = global.spr_stormking; global.current = "stormking"; } 
if global.render = 362 { global.spr_leechmoger = sprite_add("group\leechmoger.png",2,1,1,0,0); sprite_index = global.spr_leechmoger; global.current = "leechmoger"; } 
if global.render = 363 { global.spr_maideninblack = sprite_add("group\maideninblack.png",2,1,1,0,0); sprite_index = global.spr_maideninblack; global.current = "maideninblack"; } 
if global.render = 364 { global.spr_xatu = sprite_add("group\xatu.png",2,1,1,0,0); sprite_index = global.spr_xatu; global.current = "xatu"; } 
if global.render = 365 { global.spr_boneclaw = sprite_add("group\boneclaw.png",2,1,1,0,0); sprite_index = global.spr_boneclaw; global.current = "boneclaw"; } 
if global.render = 366 { global.spr_troutmaskreplica = sprite_add("group\troutmaskreplica.png",2,1,1,0,0); sprite_index = global.spr_troutmaskreplica; global.current = "troutmaskreplica"; } 
if global.render = 367 { global.spr_satori = sprite_add("group\satori.png",2,1,1,0,0); sprite_index = global.spr_satori; global.current = "satori"; } 
if global.render = 368 { global.spr_demoman = sprite_add("group\demoman.png",2,1,1,0,0); sprite_index = global.spr_demoman; global.current = "demoman"; } 
if global.render = 369 { global.spr_pyro = sprite_add("group\pyro.png",2,1,1,0,0); sprite_index = global.spr_pyro; global.current = "pyro"; } 
if global.render = 370 { global.spr_spy = sprite_add("group\spy.png",2,1,1,0,0); sprite_index = global.spr_spy; global.current = "spy"; } 
if global.render = 371 { global.spr_medic = sprite_add("group\medic.png",2,1,1,0,0); sprite_index = global.spr_medic; global.current = "medic"; } 
if global.render = 372 { global.spr_skout = sprite_add("group\skout.png",2,1,1,0,0); sprite_index = global.spr_skout; global.current = "skout"; } 
if global.render = 373 { global.spr_soldier = sprite_add("group\soldier.png",2,1,1,0,0); sprite_index = global.spr_soldier; global.current = "soldier"; } 
if global.render = 374 { global.spr_heavy = sprite_add("group\heavy.png",2,1,1,0,0); sprite_index = global.spr_heavy; global.current = "heavy"; } 
if global.render = 375 { global.spr_isaacclarke = sprite_add("group\isaacclarke.png",2,1,1,0,0); sprite_index = global.spr_isaacclarke; global.current = "isaacclarke"; } 
if global.render = 376 { global.spr_limbokid = sprite_add("group\limbokid.png",2,1,1,0,0); sprite_index = global.spr_limbokid; global.current = "limbokid"; } 
if global.render = 377 { global.spr_magnezone = sprite_add("group\magnezone.png",2,1,1,0,0); sprite_index = global.spr_magnezone; global.current = "magnezone"; } 
if global.render = 378 { global.spr_cj = sprite_add("group\cj.png",2,1,1,0,0); sprite_index = global.spr_cj; global.current = "cj"; } 
if global.render = 379 { global.spr_sven = sprite_add("group\sven.png",2,1,1,0,0); sprite_index = global.spr_sven; global.current = "sven"; } 
if global.render = 380 { global.spr_vivec = sprite_add("group\vivec.png",2,1,1,0,0); sprite_index = global.spr_vivec; global.current = "vivec"; } 
if global.render = 381 { global.spr_dagothur = sprite_add("group\dagothur.png",2,1,1,0,0); sprite_index = global.spr_dagothur; global.current = "dagothur"; } 
if global.render = 382 { global.spr_biker = sprite_add("group\biker.png",2,1,1,0,0); sprite_index = global.spr_biker; global.current = "biker"; } 
if global.render = 383 { global.spr_jacket = sprite_add("group\jacket.png",2,1,1,0,0); sprite_index = global.spr_jacket; global.current = "jacket"; } 
if global.render = 384 { global.spr_slugma = sprite_add("group\slugma.png",2,1,1,0,0); sprite_index = global.spr_slugma; global.current = "slugma"; } 
if global.render = 385 { global.spr_haunter = sprite_add("group\haunter.png",2,1,1,0,0); sprite_index = global.spr_haunter; global.current = "haunter"; } 
if global.render = 386 { global.spr_weepinbell = sprite_add("group\weepinbell.png",2,1,1,0,0); sprite_index = global.spr_weepinbell; global.current = "weepinbell"; } 
if global.render = 387 { global.spr_maxwell = sprite_add("group\maxwell.png",2,1,1,0,0); sprite_index = global.spr_maxwell; global.current = "maxwell"; } 
if global.render = 388 { global.spr_aboleth = sprite_add("group\aboleth.png",2,1,1,0,0); sprite_index = global.spr_aboleth; global.current = "aboleth"; } 
if global.render = 389 { global.spr_astralstalker = sprite_add("group\astralstalker.png",2,1,1,0,0); sprite_index = global.spr_astralstalker; global.current = "astralstalker"; } 
if global.render = 390 { global.spr_runeknight = sprite_add("group\runeknight.png",2,1,1,0,0); sprite_index = global.spr_runeknight; global.current = "runeknight"; } 
if global.render = 391 { global.spr_eagleman = sprite_add("group\eagleman.png",2,1,1,0,0); sprite_index = global.spr_eagleman; global.current = "eagleman"; } 
if global.render = 392 { global.spr_bigdaddy = sprite_add("group\bigdaddy.png",2,1,1,0,0); sprite_index = global.spr_bigdaddy; global.current = "bigdaddy"; } 
if global.render = 393 { global.spr_garbodor = sprite_add("group\garbodor.png",2,1,1,0,0); sprite_index = global.spr_garbodor; global.current = "garbodor"; } 
if global.render = 394 { global.spr_johnnybravo = sprite_add("group\johnnybravo.png",2,1,1,0,0); sprite_index = global.spr_johnnybravo; global.current = "johnnybravo"; } 
if global.render = 395 { global.spr_reimu = sprite_add("group\reimu.png",2,1,1,0,0); sprite_index = global.spr_reimu; global.current = "reimu"; } 
if global.render = 396 { global.spr_clefairy = sprite_add("group\clefairy.png",2,1,1,0,0); sprite_index = global.spr_clefairy; global.current = "clefairy"; } 
if global.render = 397 { global.spr_mima = sprite_add("group\mima.png",2,1,1,0,0); sprite_index = global.spr_mima; global.current = "mima"; } 
if global.render = 398 { global.spr_arcanine = sprite_add("group\arcanine.png",2,1,1,0,0); sprite_index = global.spr_arcanine; global.current = "arcanine"; } 
if global.render = 399 { global.spr_zatchbell = sprite_add("group\zatchbell.png",2,1,1,0,0); sprite_index = global.spr_zatchbell; global.current = "zatchbell"; } 
if global.render = 400 { global.spr_sanicthingkenoffast = sprite_add("group\sanicthingkenoffast.png",2,1,1,0,0); sprite_index = global.spr_sanicthingkenoffast; global.current = "sanicthingkenoffast"; } 
if global.render = 401 { global.spr_plaguedoctor = sprite_add("group\plaguedoctor.png",2,1,1,0,0); sprite_index = global.spr_plaguedoctor; global.current = "plaguedoctor"; } 
if global.render = 402 { global.spr_tia = sprite_add("group\tia.png",2,1,1,0,0); sprite_index = global.spr_tia; global.current = "tia"; } 
if global.render = 403 { global.spr_kanchome = sprite_add("group\kanchome.png",2,1,1,0,0); sprite_index = global.spr_kanchome; global.current = "kanchome"; } 
if global.render = 404 { global.spr_mayorofcantown = sprite_add("group\mayorofcantown.png",2,1,1,0,0); sprite_index = global.spr_mayorofcantown; global.current = "mayorofcantown"; } 
if global.render = 405 { global.spr_umagon = sprite_add("group\umagon.png",2,1,1,0,0); sprite_index = global.spr_umagon; global.current = "umagon"; } 
if global.render = 406 { global.spr_honeydew = sprite_add("group\honeydew.png",2,1,1,0,0); sprite_index = global.spr_honeydew; global.current = "honeydew"; } 
if global.render = 407 { global.spr_mrkrabs = sprite_add("group\mrkrabs.png",2,1,1,0,0); sprite_index = global.spr_mrkrabs; global.current = "mrkrabs"; } 
if global.render = 408 { global.spr_sissel = sprite_add("group\sissel.png",2,1,1,0,0); sprite_index = global.spr_sissel; global.current = "sissel"; } 
if global.render = 409 { global.spr_orangestarinfintry = sprite_add("group\orangestarinfintry.png",2,1,1,0,0); sprite_index = global.spr_orangestarinfintry; global.current = "orangestarinfintry"; } 
if global.render = 410 { global.spr_fawful = sprite_add("group\fawful.png",2,1,1,0,0); sprite_index = global.spr_fawful; global.current = "fawful"; } 
if global.render = 411 { global.spr_constanza = sprite_add("group\constanza.png",2,1,1,0,0); sprite_index = global.spr_constanza; global.current = "constanza"; } 
if global.render = 412 { global.spr_brago = sprite_add("group\brago.png",2,1,1,0,0); sprite_index = global.spr_brago; global.current = "brago"; } 
if global.render = 413 { global.spr_blu = sprite_add("group\blu.png",2,1,1,0,0); sprite_index = global.spr_blu; global.current = "blu"; } 
if global.render = 414 { global.spr_jingitaxias = sprite_add("group\jingitaxias.png",2,1,1,0,0); sprite_index = global.spr_jingitaxias; global.current = "jingitaxias"; } 
if global.render = 415 { global.spr_roadrunner = sprite_add("group\roadrunner.png",2,1,1,0,0); sprite_index = global.spr_roadrunner; global.current = "roadrunner"; } 
if global.render = 416 { global.spr_dragonite = sprite_add("group\dragonite.png",2,1,1,0,0); sprite_index = global.spr_dragonite; global.current = "dragonite"; } 
if global.render = 417 { global.spr_umagonshudoruk = sprite_add("group\umagonshudoruk.png",2,1,1,0,0); sprite_index = global.spr_umagonshudoruk; global.current = "umagonshudoruk"; } 
if global.render = 418 { global.spr_umagongoshudoruk = sprite_add("group\umagongoshudoruk.png",2,1,1,0,0); sprite_index = global.spr_umagongoshudoruk; global.current = "umagongoshudoruk"; } 
if global.render = 419 { global.spr_umagondioemuru = sprite_add("group\umagondioemuru.png",2,1,1,0,0); sprite_index = global.spr_umagondioemuru; global.current = "umagondioemuru"; } 
if global.render = 420 { global.spr_roggenrola = sprite_add("group\roggenrola.png",2,1,1,0,0); sprite_index = global.spr_roggenrola; global.current = "roggenrola"; } 
if global.render = 421 { global.spr_zeon = sprite_add("group\zeon.png",2,1,1,0,0); sprite_index = global.spr_zeon; global.current = "zeon"; } 
if global.render = 422 { global.spr_solosis = sprite_add("group\solosis.png",2,1,1,0,0); sprite_index = global.spr_solosis; global.current = "solosis"; } 
if global.render = 423 { global.spr_duosion = sprite_add("group\duosion.png",2,1,1,0,0); sprite_index = global.spr_duosion; global.current = "duosion"; } 
if global.render = 424 { global.spr_spoink = sprite_add("group\spoink.png",2,1,1,0,0); sprite_index = global.spr_spoink; global.current = "spoink"; } 
if global.render = 425 { global.spr_billcipher = sprite_add("group\billcipher.png",2,1,1,0,0); sprite_index = global.spr_billcipher; global.current = "billcipher"; } 
if global.render = 426 { global.spr_skipper = sprite_add("group\skipper.png",2,1,1,0,0); sprite_index = global.spr_skipper; global.current = "skipper"; } 
if global.render = 427 { global.spr_private = sprite_add("group\private.png",2,1,1,0,0); sprite_index = global.spr_private; global.current = "private"; } 
if global.render = 428 { global.spr_rico = sprite_add("group\rico.png",2,1,1,0,0); sprite_index = global.spr_rico; global.current = "rico"; } 
if global.render = 429 { global.spr_kowalski = sprite_add("group\kowalski.png",2,1,1,0,0); sprite_index = global.spr_kowalski; global.current = "kowalski"; } 
if global.render = 430 { global.spr_hans = sprite_add("group\hans.png",2,1,1,0,0); sprite_index = global.spr_hans; global.current = "hans"; } 
if global.render = 431 { global.spr_drsloth = sprite_add("group\drsloth.png",2,1,1,0,0); sprite_index = global.spr_drsloth; global.current = "drsloth"; } 
if global.render = 432 { global.spr_owl = sprite_add("group\owl.png",2,1,1,0,0); sprite_index = global.spr_owl; global.current = "owl"; } 
if global.render = 433 { global.spr_masterchief = sprite_add("group\masterchief.png",2,1,1,0,0); sprite_index = global.spr_masterchief; global.current = "masterchief"; } 
if global.render = 434 { global.spr_crobat = sprite_add("group\crobat.png",2,1,1,0,0); sprite_index = global.spr_crobat; global.current = "crobat"; } 
if global.render = 435 { global.spr_zubat = sprite_add("group\zubat.png",2,1,1,0,0); sprite_index = global.spr_zubat; global.current = "zubat"; } 
if global.render = 436 { global.spr_jcdenton = sprite_add("group\jcdenton.png",2,1,1,0,0); sprite_index = global.spr_jcdenton; global.current = "jcdenton"; } 
if global.render = 437 { global.spr_bomberman = sprite_add("group\bomberman.png",2,1,1,0,0); sprite_index = global.spr_bomberman; global.current = "bomberman"; } 
if global.render = 438 { global.spr_coolspot = sprite_add("group\coolspot.png",2,1,1,0,0); sprite_index = global.spr_coolspot; global.current = "coolspot"; } 
if global.render = 439 { global.spr_panty = sprite_add("group\panty.png",2,1,1,0,0); sprite_index = global.spr_panty; global.current = "panty"; } 
if global.render = 440 { global.spr_stocking = sprite_add("group\stocking.png",2,1,1,0,0); sprite_index = global.spr_stocking; global.current = "stocking"; } 
if global.render = 441 { global.spr_frankerz = sprite_add("group\frankerz.png",2,1,1,0,0); sprite_index = global.spr_frankerz; global.current = "frankerz"; } 
if global.render = 442 { global.spr_rance = sprite_add("group\rance.png",2,1,1,0,0); sprite_index = global.spr_rance; global.current = "rance"; } 
if global.render = 443 { global.spr_chie = sprite_add("group\chie.png",2,1,1,0,0); sprite_index = global.spr_chie; global.current = "chie"; } 
if global.render = 444 { global.spr_cormano = sprite_add("group\cormano.png",2,1,1,0,0); sprite_index = global.spr_cormano; global.current = "cormano"; } 
if global.render = 445 { global.spr_shake = sprite_add("group\shake.png",2,1,1,0,0); sprite_index = global.spr_shake; global.current = "shake"; } 
if global.render = 446 { global.spr_sweetbro = sprite_add("group\sweetbro.png",2,1,1,0,0); sprite_index = global.spr_sweetbro; global.current = "sweetbro"; } 
if global.render = 447 { global.spr_midna = sprite_add("group\midna.png",2,1,1,0,0); sprite_index = global.spr_midna; global.current = "midna"; } 
if global.render = 448 { global.spr_hellajeff = sprite_add("group\hellajeff.png",2,1,1,0,0); sprite_index = global.spr_hellajeff; global.current = "hellajeff"; } 
if global.render = 449 { global.spr_meatwad = sprite_add("group\meatwad.png",2,1,1,0,0); sprite_index = global.spr_meatwad; global.current = "meatwad"; } 
if global.render = 450 { global.spr_raiden = sprite_add("group\raiden.png",2,1,1,0,0); sprite_index = global.spr_raiden; global.current = "raiden"; } 
if global.render = 451 { global.spr_emi = sprite_add("group\emi.png",2,1,1,0,0); sprite_index = global.spr_emi; global.current = "emi"; } 
if global.render = 452 { global.spr_gerome = sprite_add("group\gerome.png",2,1,1,0,0); sprite_index = global.spr_gerome; global.current = "gerome"; } 
if global.render = 453 { global.spr_gordonfreeman = sprite_add("group\gordonfreeman.png",2,1,1,0,0); sprite_index = global.spr_gordonfreeman; global.current = "gordonfreeman"; } 
if global.render = 454 { global.spr_pacman = sprite_add("group\pacman.png",2,1,1,0,0); sprite_index = global.spr_pacman; global.current = "pacman"; } 
if global.render = 455 { global.spr_beckett = sprite_add("group\beckett.png",2,1,1,0,0); sprite_index = global.spr_beckett; global.current = "beckett"; } 
if global.render = 456 { global.spr_blackrose = sprite_add("group\blackrose.png",2,1,1,0,0); sprite_index = global.spr_blackrose; global.current = "blackrose"; } 
if global.render = 457 { global.spr_met = sprite_add("group\met.png",2,1,1,0,0); sprite_index = global.spr_met; global.current = "met"; } 
if global.render = 458 { global.spr_spaceinvader = sprite_add("group\spaceinvader.png",2,1,1,0,0); sprite_index = global.spr_spaceinvader; global.current = "spaceinvader"; } 
if global.render = 459 { global.spr_litwick = sprite_add("group\litwick.png",2,1,1,0,0); sprite_index = global.spr_litwick; global.current = "litwick"; } 
if global.render = 460 { global.spr_solaire = sprite_add("group\solaire.png",2,1,1,0,0); sprite_index = global.spr_solaire; global.current = "solaire"; } 
if global.render = 461 { global.spr_zekedunbar = sprite_add("group\zekedunbar.png",2,1,1,0,0); sprite_index = global.spr_zekedunbar; global.current = "zekedunbar"; } 
if global.render = 462 { global.spr_malkavian = sprite_add("group\malkavian.png",2,1,1,0,0); sprite_index = global.spr_malkavian; global.current = "malkavian"; } 
if global.render = 463 { global.spr_peashooter = sprite_add("group\peashooter.png",2,1,1,0,0); sprite_index = global.spr_peashooter; global.current = "peashooter"; } 
if global.render = 464 { global.spr_pumkin = sprite_add("group\pumkin.png",2,1,1,0,0); sprite_index = global.spr_pumkin; global.current = "pumkin"; } 
if global.render = 465 { global.spr_phoenixwright = sprite_add("group\phoenixwright.png",2,1,1,0,0); sprite_index = global.spr_phoenixwright; global.current = "phoenixwright"; } 
if global.render = 466 { global.spr_scoobywerkstat = sprite_add("group\scoobywerkstat.png",2,1,1,0,0); sprite_index = global.spr_scoobywerkstat; global.current = "scoobywerkstat"; } 
if global.render = 467 { global.spr_armordarmadillo = sprite_add("group\armordarmadillo.png",2,1,1,0,0); sprite_index = global.spr_armordarmadillo; global.current = "armordarmadillo"; } 
if global.render = 468 { global.spr_megamanx = sprite_add("group\megamanx.png",2,1,1,0,0); sprite_index = global.spr_megamanx; global.current = "megamanx"; } 
if global.render = 469 { global.spr_jetstreamsam = sprite_add("group\jetstreamsam.png",2,1,1,0,0); sprite_index = global.spr_jetstreamsam; global.current = "jetstreamsam"; } 
if global.render = 470 { global.spr_gene = sprite_add("group\gene.png",2,1,1,0,0); sprite_index = global.spr_gene; global.current = "gene"; } 
if global.render = 471 { global.spr_jotarokujo = sprite_add("group\jotarokujo.png",2,1,1,0,0); sprite_index = global.spr_jotarokujo; global.current = "jotarokujo"; } 
if global.render = 472 { global.spr_megamanexe = sprite_add("group\megamanexe.png",2,1,1,0,0); sprite_index = global.spr_megamanexe; global.current = "megamanexe"; } 
if global.render = 473 { global.spr_leila = sprite_add("group\leila.png",2,1,1,0,0); sprite_index = global.spr_leila; global.current = "leila"; } 
if global.render = 474 { global.spr_danmandel = sprite_add("group\danmandel.png",2,1,1,0,0); sprite_index = global.spr_danmandel; global.current = "danmandel"; } 
if global.render = 475 { global.spr_elisepearson = sprite_add("group\elisepearson.png",2,1,1,0,0); sprite_index = global.spr_elisepearson; global.current = "elisepearson"; } 
if global.render = 476 { global.spr_chrispearson = sprite_add("group\chrispearson.png",2,1,1,0,0); sprite_index = global.spr_chrispearson; global.current = "chrispearson"; } 
if global.render = 477 { global.spr_sif = sprite_add("group\sif.png",2,1,1,0,0); sprite_index = global.spr_sif; global.current = "sif"; } 
if global.render = 478 { global.spr_strayhumanity = sprite_add("group\strayhumanity.png",2,1,1,0,0); sprite_index = global.spr_strayhumanity; global.current = "strayhumanity"; } 
if global.render = 479 { global.spr_crestfallenwarrior = sprite_add("group\crestfallenwarrior.png",2,1,1,0,0); sprite_index = global.spr_crestfallenwarrior; global.current = "crestfallenwarrior"; } 
if global.render = 480 { global.spr_caprademon = sprite_add("group\caprademon.png",2,1,1,0,0); sprite_index = global.spr_caprademon; global.current = "caprademon"; } 
if global.render = 481 { global.spr_gwyndolin = sprite_add("group\gwyndolin.png",2,1,1,0,0); sprite_index = global.spr_gwyndolin; global.current = "gwyndolin"; } 
if global.render = 482 { global.spr_nier = sprite_add("group\nier.png",2,1,1,0,0); sprite_index = global.spr_nier; global.current = "nier"; } 
if global.render = 483 { global.spr_weiss = sprite_add("group\weiss.png",2,1,1,0,0); sprite_index = global.spr_weiss; global.current = "weiss"; } 
if global.render = 484 { global.spr_ryu = sprite_add("group\ryu.png",2,1,1,0,0); sprite_index = global.spr_ryu; global.current = "ryu"; } 
if global.render = 485 { global.spr_zangief = sprite_add("group\zangief.png",2,1,1,0,0); sprite_index = global.spr_zangief; global.current = "zangief"; } 
if global.render = 486 { global.spr_monokuma = sprite_add("group\monokuma.png",2,1,1,0,0); sprite_index = global.spr_monokuma; global.current = "monokuma"; } 
if global.render = 487 { global.spr_shade = sprite_add("group\shade.png",2,1,1,0,0); sprite_index = global.spr_shade; global.current = "shade"; } 
if global.render = 488 { global.spr_chacha = sprite_add("group\chacha.png",2,1,1,0,0); sprite_index = global.spr_chacha; global.current = "chacha"; } 
if global.render = 489 { global.spr_lucas = sprite_add("group\lucas.png",2,1,1,0,0); sprite_index = global.spr_lucas; global.current = "lucas"; } 
if global.render = 490 { global.spr_kenmasters = sprite_add("group\kenmasters.png",2,1,1,0,0); sprite_index = global.spr_kenmasters; global.current = "kenmasters"; } 
if global.render = 491 { global.spr_aigis = sprite_add("group\aigis.png",2,1,1,0,0); sprite_index = global.spr_aigis; global.current = "aigis"; } 
if global.render = 492 { global.spr_sniper = sprite_add("group\sniper.png",2,1,1,0,0); sprite_index = global.spr_sniper; global.current = "sniper"; } 
if global.render = 493 { global.spr_rikafurude = sprite_add("group\rikafurude.png",2,1,1,0,0); sprite_index = global.spr_rikafurude; global.current = "rikafurude"; } 
if global.render = 494 { global.spr_chernoalpha = sprite_add("group\chernoalpha.png",2,1,1,0,0); sprite_index = global.spr_chernoalpha; global.current = "chernoalpha"; } 
if global.render = 495 { global.spr_strikereureka = sprite_add("group\strikereureka.png",2,1,1,0,0); sprite_index = global.spr_strikereureka; global.current = "strikereureka"; } 
if global.render = 496 { global.spr_burmyplant = sprite_add("group\burmyplant.png",2,1,1,0,0); sprite_index = global.spr_burmyplant; global.current = "burmyplant"; } 
if global.render = 497 { global.spr_wormadamplant = sprite_add("group\wormadamplant.png",2,1,1,0,0); sprite_index = global.spr_wormadamplant; global.current = "wormadamplant"; } 
if global.render = 498 { global.spr_wormadamtrash = sprite_add("group\wormadamtrash.png",2,1,1,0,0); sprite_index = global.spr_wormadamtrash; global.current = "wormadamtrash"; } 
if global.render = 499 { global.spr_wormadamsand = sprite_add("group\wormadamsand.png",2,1,1,0,0); sprite_index = global.spr_wormadamsand; global.current = "wormadamsand"; } 
if global.render = 500 { global.spr_yotsuba = sprite_add("group\yotsuba.png",2,1,1,0,0); sprite_index = global.spr_yotsuba; global.current = "yotsuba"; } 
if global.render = 501 { global.spr_cubone = sprite_add("group\cubone.png",2,1,1,0,0); sprite_index = global.spr_cubone; global.current = "cubone"; } 
if global.render = 502 { global.spr_meowth = sprite_add("group\meowth.png",2,1,1,0,0); sprite_index = global.spr_meowth; global.current = "meowth"; } 
if global.render = 503 { global.spr_beat = sprite_add("group\beat.png",2,1,1,0,0); sprite_index = global.spr_beat; global.current = "beat"; } 
if global.render = 504 { global.spr_isabelle = sprite_add("group\isabelle.png",2,1,1,0,0); sprite_index = global.spr_isabelle; global.current = "isabelle"; } 
if global.render = 505 { global.spr_balrog = sprite_add("group\balrog.png",2,1,1,0,0); sprite_index = global.spr_balrog; global.current = "balrog"; } 
if global.render = 506 { global.spr_takamaru = sprite_add("group\takamaru.png",2,1,1,0,0); sprite_index = global.spr_takamaru; global.current = "takamaru"; } 

