spr_thegreentie = sprite_add("thegreentie.png", 2, 1,1,0,0);
global.added = "thegreentie" 
spr_businessbanana = sprite_add("businessbanana.png", 2, 1,1,0,0);
global.added = "businessbanana" 
spr_dennot = sprite_add("dennot.png", 2, 1,1,0,0);
global.added = "dennot" 
spr_mario = sprite_add("mario.png", 2, 1,1,0,0);
global.added = "mario" 
spr_luigi = sprite_add("luigi.png", 2, 1,1,0,0);
global.added = "luigi" 
spr_bowser = sprite_add("bowser.png", 2, 1,1,0,0);
global.added = "bowser" 
spr_peach = sprite_add("peach.png", 2, 1,1,0,0);
global.added = "peach" 
spr_drmario = sprite_add("drmario.png", 2, 1,1,0,0);
global.added = "drmario" 
spr_yoshi = sprite_add("yoshi.png", 2, 1,1,0,0);
global.added = "yoshi" 
spr_pit = sprite_add("pit.png", 2, 1,1,0,0);
global.added = "pit" 
spr_captainfalcon = sprite_add("captainfalcon.png", 2, 1,1,0,0);
global.added = "captainfalcon" 
spr_mrgameandwatch = sprite_add("mrgameandwatch.png", 2, 1,1,0,0);
global.added = "mrgameandwatch" 
spr_rob = sprite_add("rob.png", 2, 1,1,0,0);
global.added = "rob" 
spr_pikachu = sprite_add("pikachu.png", 2, 1,1,0,0);
global.added = "pikachu" 
spr_bulbasaur = sprite_add("bulbasaur.png", 2, 1,1,0,0);
global.added = "bulbasaur" 
spr_ivysaur = sprite_add("ivysaur.png", 2, 1,1,0,0);
global.added = "ivysaur" 
spr_venusaur = sprite_add("venusaur.png", 2, 1,1,0,0);
global.added = "venusaur" 
spr_charmander = sprite_add("charmander.png", 2, 1,1,0,0);
global.added = "charmander" 
spr_charmeleon = sprite_add("charmeleon.png", 2, 1,1,0,0);
global.added = "charmeleon" 
spr_charizard = sprite_add("charizard.png", 2, 1,1,0,0);
global.added = "charizard" 
spr_link = sprite_add("link.png", 2, 1,1,0,0);
global.added = "link" 
spr_zelda = sprite_add("zelda.png", 2, 1,1,0,0);
global.added = "zelda" 
spr_sheik = sprite_add("sheik.png", 2, 1,1,0,0);
global.added = "sheik" 
spr_ganondorf = sprite_add("ganondorf.png", 2, 1,1,0,0);
global.added = "ganondorf" 
spr_sonic = sprite_add("sonic.png", 2, 1,1,0,0);
global.added = "sonic" 
spr_wario = sprite_add("wario.png", 2, 1,1,0,0);
global.added = "wario" 
spr_pikminred = sprite_add("pikminred.png", 2, 1,1,0,0);
global.added = "pikminred" 
spr_pikminyellow = sprite_add("pikminyellow.png", 2, 1,1,0,0);
global.added = "pikminyellow" 
spr_pikminblue = sprite_add("pikminblue.png", 2, 1,1,0,0);
global.added = "pikminblue" 
spr_pikminwhite = sprite_add("pikminwhite.png", 2, 1,1,0,0);
global.added = "pikminwhite" 
spr_pikminpurple = sprite_add("pikminpurple.png", 2, 1,1,0,0);
global.added = "pikminpurple" 
spr_engineer = sprite_add("engineer.png", 2, 1,1,0,0);
global.added = "engineer" 
spr_steve = sprite_add("steve.png", 2, 1,1,0,0);
global.added = "steve" 
spr_magickared = sprite_add("magickared.png", 2, 1,1,0,0);
global.added = "magickared" 
spr_magickablue = sprite_add("magickablue.png", 2, 1,1,0,0);
global.added = "magickablue" 
spr_magickayellow = sprite_add("magickayellow.png", 2, 1,1,0,0);
global.added = "magickayellow" 
spr_magickagreen = sprite_add("magickagreen.png", 2, 1,1,0,0);
global.added = "magickagreen" 
spr_santaclaus = sprite_add("santaclaus.png", 2, 1,1,0,0);
global.added = "santaclaus" 
spr_blossom = sprite_add("blossom.png", 2, 1,1,0,0);
global.added = "blossom" 
spr_bubbles = sprite_add("bubbles.png", 2, 1,1,0,0);
global.added = "bubbles" 
spr_buttercup = sprite_add("buttercup.png", 2, 1,1,0,0);
global.added = "buttercup" 
spr_eddy = sprite_add("eddy.png", 2, 1,1,0,0);
global.added = "eddy" 
spr_edd = sprite_add("edd.png", 2, 1,1,0,0);
global.added = "edd" 
spr_ed = sprite_add("ed.png", 2, 1,1,0,0);
global.added = "ed" 
spr_courage = sprite_add("courage.png", 2, 1,1,0,0);
global.added = "courage" 
spr_gir = sprite_add("gir.png", 2, 1,1,0,0);
global.added = "gir" 
spr_spongebob = sprite_add("spongebob.png", 2, 1,1,0,0);
global.added = "spongebob" 
spr_captainknuckles = sprite_add("captainknuckles.png", 2, 1,1,0,0);
global.added = "captainknuckles" 
spr_flapjack = sprite_add("flapjack.png", 2, 1,1,0,0);
global.added = "flapjack" 
spr_chowder = sprite_add("chowder.png", 2, 1,1,0,0);
global.added = "chowder" 
spr_shnitzel = sprite_add("shnitzel.png", 2, 1,1,0,0);
global.added = "shnitzel" 
spr_waluigi = sprite_add("waluigi.png", 2, 1,1,0,0);
global.added = "waluigi" 
spr_galvantula = sprite_add("galvantula.png", 2, 1,1,0,0);
global.added = "galvantula" 
spr_electivire = sprite_add("electivire.png", 2, 1,1,0,0);
global.added = "electivire" 
spr_reuniclus = sprite_add("reuniclus.png", 2, 1,1,0,0);
global.added = "reuniclus" 
spr_pikminrock = sprite_add("pikminrock.png", 2, 1,1,0,0);
global.added = "pikminrock" 
spr_pikminwinged = sprite_add("pikminwinged.png", 2, 1,1,0,0);
global.added = "pikminwinged" 
spr_spinda = sprite_add("spinda.png", 2, 1,1,0,0);
global.added = "spinda" 
spr_mrdickens = sprite_add("mrdickens.png", 2, 1,1,0,0);
global.added = "mrdickens" 
spr_castform = sprite_add("castform.png", 2, 1,1,0,0);
global.added = "castform" 
spr_castformsunny = sprite_add("castformsunny.png", 2, 1,1,0,0);
global.added = "castformsunny" 
spr_castformrainy = sprite_add("castformrainy.png", 2, 1,1,0,0);
global.added = "castformrainy" 
spr_castformsnowy = sprite_add("castformsnowy.png", 2, 1,1,0,0);
global.added = "castformsnowy" 
spr_beheeyem = sprite_add("beheeyem.png", 2, 1,1,0,0);
global.added = "beheeyem" 
spr_celebi = sprite_add("celebi.png", 2, 1,1,0,0);
global.added = "celebi" 
spr_deoxys = sprite_add("deoxys.png", 2, 1,1,0,0);
global.added = "deoxys" 
spr_deoxysattack = sprite_add("deoxysattack.png", 2, 1,1,0,0);
global.added = "deoxysattack" 
spr_deoxysdefense = sprite_add("deoxysdefense.png", 2, 1,1,0,0);
global.added = "deoxysdefense" 
spr_deoxysspeed = sprite_add("deoxysspeed.png", 2, 1,1,0,0);
global.added = "deoxysspeed" 
spr_diglet = sprite_add("diglet.png", 2, 1,1,0,0);
global.added = "diglet" 
spr_ditto = sprite_add("ditto.png", 2, 1,1,0,0);
global.added = "ditto" 
spr_drifloon = sprite_add("drifloon.png", 2, 1,1,0,0);
global.added = "drifloon" 
spr_electrode = sprite_add("electrode.png", 2, 1,1,0,0);
global.added = "electrode" 
spr_escavalier = sprite_add("escavalier.png", 2, 1,1,0,0);
global.added = "escavalier" 
spr_froslass = sprite_add("froslass.png", 2, 1,1,0,0);
global.added = "froslass" 
spr_genescect = sprite_add("genescect.png", 2, 1,1,0,0);
global.added = "genescect" 
spr_geodude = sprite_add("geodude.png", 2, 1,1,0,0);
global.added = "geodude" 
spr_gastly = sprite_add("gastly.png", 2, 1,1,0,0);
global.added = "gastly" 
spr_giratinaorigin = sprite_add("giratinaorigin.png", 2, 1,1,0,0);
global.added = "giratinaorigin" 
spr_golurk = sprite_add("golurk.png", 2, 1,1,0,0);
global.added = "golurk" 
spr_hydreigon = sprite_add("hydreigon.png", 2, 1,1,0,0);
global.added = "hydreigon" 
spr_kyurem = sprite_add("kyurem.png", 2, 1,1,0,0);
global.added = "kyurem" 
spr_lunatone = sprite_add("lunatone.png", 2, 1,1,0,0);
global.added = "lunatone" 
spr_solrock = sprite_add("solrock.png", 2, 1,1,0,0);
global.added = "solrock" 
spr_magnemite = sprite_add("magnemite.png", 2, 1,1,0,0);
global.added = "magnemite" 
spr_metagross = sprite_add("metagross.png", 2, 1,1,0,0);
global.added = "metagross" 
spr_ninjask = sprite_add("ninjask.png", 2, 1,1,0,0);
global.added = "ninjask" 
spr_poliwag = sprite_add("poliwag.png", 2, 1,1,0,0);
global.added = "poliwag" 
spr_psyduck = sprite_add("psyduck.png", 2, 1,1,0,0);
global.added = "psyduck" 
spr_regigigas = sprite_add("regigigas.png", 2, 1,1,0,0);
global.added = "regigigas" 
spr_rotom = sprite_add("rotom.png", 2, 1,1,0,0);
global.added = "rotom" 
spr_rotomfan = sprite_add("rotomfan.png", 2, 1,1,0,0);
global.added = "rotomfan" 
spr_rotomfrost = sprite_add("rotomfrost.png", 2, 1,1,0,0);
global.added = "rotomfrost" 
spr_rotomheat = sprite_add("rotomheat.png", 2, 1,1,0,0);
global.added = "rotomheat" 
spr_rotomwash = sprite_add("rotomwash.png", 2, 1,1,0,0);
global.added = "rotomwash" 
spr_rotommow = sprite_add("rotommow.png", 2, 1,1,0,0);
global.added = "rotommow" 
spr_sawk = sprite_add("sawk.png", 2, 1,1,0,0);
global.added = "sawk" 
spr_scolipede = sprite_add("scolipede.png", 2, 1,1,0,0);
global.added = "scolipede" 
spr_shedinja = sprite_add("shedinja.png", 2, 1,1,0,0);
global.added = "shedinja" 
spr_simisage = sprite_add("simisage.png", 2, 1,1,0,0);
global.added = "simisage" 
spr_sigilyph = sprite_add("sigilyph.png", 2, 1,1,0,0);
global.added = "sigilyph" 
spr_tentacruel = sprite_add("tentacruel.png", 2, 1,1,0,0);
global.added = "tentacruel" 
spr_angrybirdred = sprite_add("angrybirdred.png", 2, 1,1,0,0);
global.added = "angrybirdred" 
spr_angrybirdwhite = sprite_add("angrybirdwhite.png", 2, 1,1,0,0);
global.added = "angrybirdwhite" 
spr_angrybirdyellow = sprite_add("angrybirdyellow.png", 2, 1,1,0,0);
global.added = "angrybirdyellow" 
spr_frosty = sprite_add("frosty.png", 2, 1,1,0,0);
global.added = "frosty" 
spr_professorlayton = sprite_add("professorlayton.png", 2, 1,1,0,0);
global.added = "professorlayton" 
spr_navi = sprite_add("navi.png", 2, 1,1,0,0);
global.added = "navi" 
spr_nyancat = sprite_add("nyancat.png", 2, 1,1,0,0);
global.added = "nyancat" 
spr_squirtle = sprite_add("squirtle.png", 2, 1,1,0,0);
global.added = "squirtle" 
spr_volcarona = sprite_add("volcarona.png", 2, 1,1,0,0);
global.added = "volcarona" 
spr_voltorb = sprite_add("voltorb.png", 2, 1,1,0,0);
global.added = "voltorb" 
spr_wobbuffet = sprite_add("wobbuffet.png", 2, 1,1,0,0);
global.added = "wobbuffet" 
spr_tentacool = sprite_add("tentacool.png", 2, 1,1,0,0);
global.added = "tentacool" 
spr_shuckle = sprite_add("shuckle.png", 2, 1,1,0,0);
global.added = "shuckle" 
spr_sneakypebbles = sprite_add("sneakypebbles.png", 2, 1,1,0,0);
global.added = "sneakypebbles" 
spr_natu = sprite_add("natu.png", 2, 1,1,0,0);
global.added = "natu" 
spr_trapinch = sprite_add("trapinch.png", 2, 1,1,0,0);
global.added = "trapinch" 
spr_cofagrigus = sprite_add("cofagrigus.png", 2, 1,1,0,0);
global.added = "cofagrigus" 
spr_mienshao = sprite_add("mienshao.png", 2, 1,1,0,0);
global.added = "mienshao" 
spr_baitfish = sprite_add("baitfish.png", 2, 1,1,0,0);
global.added = "baitfish" 
spr_mudkip = sprite_add("mudkip.png", 2, 1,1,0,0);
global.added = "mudkip" 
spr_zangoose = sprite_add("zangoose.png", 2, 1,1,0,0);
global.added = "zangoose" 
spr_audino = sprite_add("audino.png", 2, 1,1,0,0);
global.added = "audino" 
spr_vibrava = sprite_add("vibrava.png", 2, 1,1,0,0);
global.added = "vibrava" 
spr_insidetheflyingmachine = sprite_add("insidetheflyingmachine.png", 2, 1,1,0,0);
global.added = "insidetheflyingmachine" 
spr_azelf = sprite_add("azelf.png", 2, 1,1,0,0);
global.added = "azelf" 
spr_cancer = sprite_add("cancer.png", 2, 1,1,0,0);
global.added = "cancer" 
spr_cryogonal = sprite_add("cryogonal.png", 2, 1,1,0,0);
global.added = "cryogonal" 
spr_flygon = sprite_add("flygon.png", 2, 1,1,0,0);
global.added = "flygon" 
spr_pinkiepie = sprite_add("pinkiepie.png", 2, 1,1,0,0);
global.added = "pinkiepie" 
spr_uxie = sprite_add("uxie.png", 2, 1,1,0,0);
global.added = "uxie" 
spr_throh = sprite_add("throh.png", 2, 1,1,0,0);
global.added = "throh" 
spr_swanna = sprite_add("swanna.png", 2, 1,1,0,0);
global.added = "swanna" 
spr_geno = sprite_add("geno.png", 2, 1,1,0,0);
global.added = "geno" 
spr_mesprit = sprite_add("mesprit.png", 2, 1,1,0,0);
global.added = "mesprit" 
spr_marshtomp = sprite_add("marshtomp.png", 2, 1,1,0,0);
global.added = "marshtomp" 
spr_pokemonegg = sprite_add("pokemonegg.png", 2, 1,1,0,0);
global.added = "pokemonegg" 
spr_pyramidhead = sprite_add("pyramidhead.png", 2, 1,1,0,0);
global.added = "pyramidhead" 
spr_absol = sprite_add("absol.png", 2, 1,1,0,0);
global.added = "absol" 
spr_sanic = sprite_add("sanic.png", 2, 1,1,0,0);
global.added = "sanic" 
spr_saniclil = sprite_add("saniclil.png", 2, 1,1,0,0);
global.added = "saniclil" 
spr_poisonmushroom = sprite_add("poisonmushroom.png", 2, 1,1,0,0);
global.added = "poisonmushroom" 
spr_druddigon = sprite_add("druddigon.png", 2, 1,1,0,0);
global.added = "druddigon" 
spr_gardevoir = sprite_add("gardevoir.png", 2, 1,1,0,0);
global.added = "gardevoir" 
spr_twilightsparkle = sprite_add("twilightsparkle.png", 2, 1,1,0,0);
global.added = "twilightsparkle" 
spr_doge = sprite_add("doge.png", 2, 1,1,0,0);
global.added = "doge" 
spr_nito = sprite_add("nito.png", 2, 1,1,0,0);
global.added = "nito" 
spr_seaththescaleless = sprite_add("seaththescaleless.png", 2, 1,1,0,0);
global.added = "seaththescaleless" 
spr_uboa = sprite_add("uboa.png", 2, 1,1,0,0);
global.added = "uboa" 
spr_penetrator = sprite_add("penetrator.png", 2, 1,1,0,0);
global.added = "penetrator" 
spr_towerknight = sprite_add("towerknight.png", 2, 1,1,0,0);
global.added = "towerknight" 
spr_rainbowdash = sprite_add("rainbowdash.png", 2, 1,1,0,0);
global.added = "rainbowdash" 
spr_zerotwo = sprite_add("zerotwo.png", 2, 1,1,0,0);
global.added = "zerotwo" 
spr_adjudicator = sprite_add("adjudicator.png", 2, 1,1,0,0);
global.added = "adjudicator" 
spr_smough = sprite_add("smough.png", 2, 1,1,0,0);
global.added = "smough" 
spr_ornstein = sprite_add("ornstein.png", 2, 1,1,0,0);
global.added = "ornstein" 
spr_madotsuki = sprite_add("madotsuki.png", 2, 1,1,0,0);
global.added = "madotsuki" 
spr_kirby = sprite_add("kirby.png", 2, 1,1,0,0);
global.added = "kirby" 
spr_luvdisc = sprite_add("luvdisc.png", 2, 1,1,0,0);
global.added = "luvdisc" 
spr_honedge = sprite_add("honedge.png", 2, 1,1,0,0);
global.added = "honedge" 
spr_oorotto = sprite_add("oorotto.png", 2, 1,1,0,0);
global.added = "oorotto" 
spr_xerneas = sprite_add("xerneas.png", 2, 1,1,0,0);
global.added = "xerneas" 
spr_slenderman = sprite_add("slenderman.png", 2, 1,1,0,0);
global.added = "slenderman" 
spr_chikorita = sprite_add("chikorita.png", 2, 1,1,0,0);
global.added = "chikorita" 
spr_honchkrow = sprite_add("honchkrow.png", 2, 1,1,0,0);
global.added = "honchkrow" 
spr_applejack = sprite_add("applejack.png", 2, 1,1,0,0);
global.added = "applejack" 
spr_muricaneagle = sprite_add("muricaneagle.png", 2, 1,1,0,0);
global.added = "muricaneagle" 
spr_duckhunt = sprite_add("duckhunt.png", 2, 1,1,0,0);
global.added = "duckhunt" 
spr_duckhunt2 = sprite_add("duckhunt2.png", 2, 1,1,0,0);
global.added = "duckhunt2" 
spr_duckhunt3 = sprite_add("duckhunt3.png", 2, 1,1,0,0);
global.added = "duckhunt3" 
spr_wacky = sprite_add("wacky.png", 2, 1,1,0,0);
global.added = "wacky" 
spr_rarity = sprite_add("rarity.png", 2, 1,1,0,0);
global.added = "rarity" 
spr_wooper = sprite_add("wooper.png", 2, 1,1,0,0);
global.added = "wooper" 
spr_hypno = sprite_add("hypno.png", 2, 1,1,0,0);
global.added = "hypno" 
spr_talonflame = sprite_add("talonflame.png", 2, 1,1,0,0);
global.added = "talonflame" 
spr_isaac = sprite_add("isaac.png", 2, 1,1,0,0);
global.added = "isaac" 
spr_crustle = sprite_add("crustle.png", 2, 1,1,0,0);
global.added = "crustle" 
spr_gigalith = sprite_add("gigalith.png", 2, 1,1,0,0);
global.added = "gigalith" 
spr_meatboy = sprite_add("meatboy.png", 2, 1,1,0,0);
global.added = "meatboy" 
spr_fluttershy = sprite_add("fluttershy.png", 2, 1,1,0,0);
global.added = "fluttershy" 
spr_geralt = sprite_add("geralt.png", 2, 1,1,0,0);
global.added = "geralt" 
spr_megaampharos = sprite_add("megaampharos.png", 2, 1,1,0,0);
global.added = "megaampharos" 
spr_nosepass = sprite_add("nosepass.png", 2, 1,1,0,0);
global.added = "nosepass" 
spr_mew = sprite_add("mew.png", 2, 1,1,0,0);
global.added = "mew" 
spr_dialga = sprite_add("dialga.png", 2, 1,1,0,0);
global.added = "dialga" 
spr_ampharos = sprite_add("ampharos.png", 2, 1,1,0,0);
global.added = "ampharos" 
spr_nyarlathoep = sprite_add("nyarlathoep.png", 2, 1,1,0,0);
global.added = "nyarlathoep" 
spr_latias = sprite_add("latias.png", 2, 1,1,0,0);
global.added = "latias" 
spr_cthulhu = sprite_add("cthulhu.png", 2, 1,1,0,0);
global.added = "cthulhu" 
spr_latios = sprite_add("latios.png", 2, 1,1,0,0);
global.added = "latios" 
spr_stantler = sprite_add("stantler.png", 2, 1,1,0,0);
global.added = "stantler" 
spr_yogsothoth = sprite_add("yogsothoth.png", 2, 1,1,0,0);
global.added = "yogsothoth" 
spr_pingu = sprite_add("pingu.png", 2, 1,1,0,0);
global.added = "pingu" 
spr_palkia = sprite_add("palkia.png", 2, 1,1,0,0);
global.added = "palkia" 
spr_shoggoth = sprite_add("shoggoth.png", 2, 1,1,0,0);
global.added = "shoggoth" 
spr_smeargle = sprite_add("smeargle.png", 2, 1,1,0,0);
global.added = "smeargle" 
spr_bayleaf = sprite_add("bayleaf.png", 2, 1,1,0,0);
global.added = "bayleaf" 
spr_megablaziken = sprite_add("megablaziken.png", 2, 1,1,0,0);
global.added = "megablaziken" 
spr_ghroth = sprite_add("ghroth.png", 2, 1,1,0,0);
global.added = "ghroth" 
spr_megamawile = sprite_add("megamawile.png", 2, 1,1,0,0);
global.added = "megamawile" 
spr_tailow = sprite_add("tailow.png", 2, 1,1,0,0);
global.added = "tailow" 
spr_weedle = sprite_add("weedle.png", 2, 1,1,0,0);
global.added = "weedle" 
spr_swellow = sprite_add("swellow.png", 2, 1,1,0,0);
global.added = "swellow" 
spr_koffing = sprite_add("koffing.png", 2, 1,1,0,0);
global.added = "koffing" 
spr_snorunt = sprite_add("snorunt.png", 2, 1,1,0,0);
global.added = "snorunt" 
spr_linux = sprite_add("linux.png", 2, 1,1,0,0);
global.added = "linux" 
spr_sableye = sprite_add("sableye.png", 2, 1,1,0,0);
global.added = "sableye" 
spr_spike = sprite_add("spike.png", 2, 1,1,0,0);
global.added = "spike" 
spr_elderthing = sprite_add("elderthing.png", 2, 1,1,0,0);
global.added = "elderthing" 
spr_shadowlurkerm = sprite_add("shadowlurkerm.png", 2, 1,1,0,0);
global.added = "shadowlurkerm" 
spr_ostrava = sprite_add("ostrava.png", 2, 1,1,0,0);
global.added = "ostrava" 
spr_havel = sprite_add("havel.png", 2, 1,1,0,0);
global.added = "havel" 
spr_ferroseed = sprite_add("ferroseed.png", 2, 1,1,0,0);
global.added = "ferroseed" 
spr_meganium = sprite_add("meganium.png", 2, 1,1,0,0);
global.added = "meganium" 
spr_jeremiah = sprite_add("jeremiah.png", 2, 1,1,0,0);
global.added = "jeremiah" 
spr_sudowoodo = sprite_add("sudowoodo.png", 2, 1,1,0,0);
global.added = "sudowoodo" 
spr_gulpin = sprite_add("gulpin.png", 2, 1,1,0,0);
global.added = "gulpin" 
spr_rambi = sprite_add("rambi.png", 2, 1,1,0,0);
global.added = "rambi" 
spr_princesscelestia = sprite_add("princesscelestia.png", 2, 1,1,0,0);
global.added = "princesscelestia" 
spr_marvelouschester = sprite_add("marvelouschester.png", 2, 1,1,0,0);
global.added = "marvelouschester" 
spr_snover = sprite_add("snover.png", 2, 1,1,0,0);
global.added = "snover" 
spr_artorias = sprite_add("artorias.png", 2, 1,1,0,0);
global.added = "artorias" 
spr_abomasnow = sprite_add("abomasnow.png", 2, 1,1,0,0);
global.added = "abomasnow" 
spr_tangrowth = sprite_add("tangrowth.png", 2, 1,1,0,0);
global.added = "tangrowth" 
spr_haxorus = sprite_add("haxorus.png", 2, 1,1,0,0);
global.added = "haxorus" 
spr_surskit = sprite_add("surskit.png", 2, 1,1,0,0);
global.added = "surskit" 
spr_oneofthefourwings = sprite_add("oneofthefourwings.png", 2, 1,1,0,0);
global.added = "oneofthefourwings" 
spr_maneatermildred = sprite_add("maneatermildred.png", 2, 1,1,0,0);
global.added = "maneatermildred" 
spr_megaman = sprite_add("megaman.png", 2, 1,1,0,0);
global.added = "megaman" 
spr_squiddle = sprite_add("squiddle.png", 2, 1,1,0,0);
global.added = "squiddle" 
spr_sawsbuckwinter = sprite_add("sawsbuckwinter.png", 2, 1,1,0,0);
global.added = "sawsbuckwinter" 
spr_porygonz = sprite_add("porygonz.png", 2, 1,1,0,0);
global.added = "porygonz" 
spr_ciarin = sprite_add("ciarin.png", 2, 1,1,0,0);
global.added = "ciarin" 
spr_sawsbuckspring = sprite_add("sawsbuckspring.png", 2, 1,1,0,0);
global.added = "sawsbuckspring" 
spr_sawsbucksummer = sprite_add("sawsbucksummer.png", 2, 1,1,0,0);
global.added = "sawsbucksummer" 
spr_sawsbuckautumn = sprite_add("sawsbuckautumn.png", 2, 1,1,0,0);
global.added = "sawsbuckautumn" 
spr_stunfisk = sprite_add("stunfisk.png", 2, 1,1,0,0);
global.added = "stunfisk" 
spr_starly = sprite_add("starly.png", 2, 1,1,0,0);
global.added = "starly" 
spr_lautrec = sprite_add("lautrec.png", 2, 1,1,0,0);
global.added = "lautrec" 
spr_musharna = sprite_add("musharna.png", 2, 1,1,0,0);
global.added = "musharna" 
spr_munna = sprite_add("munna.png", 2, 1,1,0,0);
global.added = "munna" 
spr_porygon2 = sprite_add("porygon2.png", 2, 1,1,0,0);
global.added = "porygon2" 
spr_doran = sprite_add("doran.png", 2, 1,1,0,0);
global.added = "doran" 
spr_sunkern = sprite_add("sunkern.png", 2, 1,1,0,0);
global.added = "sunkern" 
spr_porygon = sprite_add("porygon.png", 2, 1,1,0,0);
global.added = "porygon" 
spr_sunflora = sprite_add("sunflora.png", 2, 1,1,0,0);
global.added = "sunflora" 
spr_scizor = sprite_add("scizor.png", 2, 1,1,0,0);
global.added = "scizor" 
spr_foongus = sprite_add("foongus.png", 2, 1,1,0,0);
global.added = "foongus" 
spr_amoongus = sprite_add("amoongus.png", 2, 1,1,0,0);
global.added = "amoongus" 
spr_silcoon = sprite_add("silcoon.png", 2, 1,1,0,0);
global.added = "silcoon" 
spr_cascoon = sprite_add("cascoon.png", 2, 1,1,0,0);
global.added = "cascoon" 
spr_duskull = sprite_add("duskull.png", 2, 1,1,0,0);
global.added = "duskull" 
spr_probopass = sprite_add("probopass.png", 2, 1,1,0,0);
global.added = "probopass" 
spr_lampent = sprite_add("lampent.png", 2, 1,1,0,0);
global.added = "lampent" 
spr_girafarig = sprite_add("girafarig.png", 2, 1,1,0,0);
global.added = "girafarig" 
spr_murkrow = sprite_add("murkrow.png", 2, 1,1,0,0);
global.added = "murkrow" 
spr_maractus = sprite_add("maractus.png", 2, 1,1,0,0);
global.added = "maractus" 
spr_jellyfish = sprite_add("jellyfish.png", 2, 1,1,0,0);
global.added = "jellyfish" 
spr_rapidash = sprite_add("rapidash.png", 2, 1,1,0,0);
global.added = "rapidash" 
spr_rufflet = sprite_add("rufflet.png", 2, 1,1,0,0);
global.added = "rufflet" 
spr_pelliper = sprite_add("pelliper.png", 2, 1,1,0,0);
global.added = "pelliper" 
spr_quote = sprite_add("quote.png", 2, 1,1,0,0);
global.added = "quote" 
spr_curlybrace = sprite_add("curlybrace.png", 2, 1,1,0,0);
global.added = "curlybrace" 
spr_cyndaquil = sprite_add("cyndaquil.png", 2, 1,1,0,0);
global.added = "cyndaquil" 
spr_piranhaplant = sprite_add("piranhaplant.png", 2, 1,1,0,0);
global.added = "piranhaplant" 
spr_braviary = sprite_add("braviary.png", 2, 1,1,0,0);
global.added = "braviary" 
spr_conkeldurr = sprite_add("conkeldurr.png", 2, 1,1,0,0);
global.added = "conkeldurr" 
spr_yamask = sprite_add("yamask.png", 2, 1,1,0,0);
global.added = "yamask" 
spr_croagunk = sprite_add("croagunk.png", 2, 1,1,0,0);
global.added = "croagunk" 
spr_lumineon = sprite_add("lumineon.png", 2, 1,1,0,0);
global.added = "lumineon" 
spr_scraggy = sprite_add("scraggy.png", 2, 1,1,0,0);
global.added = "scraggy" 
spr_toxicroak = sprite_add("toxicroak.png", 2, 1,1,0,0);
global.added = "toxicroak" 
spr_vanillish = sprite_add("vanillish.png", 2, 1,1,0,0);
global.added = "vanillish" 
spr_princessluna = sprite_add("princessluna.png", 2, 1,1,0,0);
global.added = "princessluna" 
spr_staryu = sprite_add("staryu.png", 2, 1,1,0,0);
global.added = "staryu" 
spr_scrafty = sprite_add("scrafty.png", 2, 1,1,0,0);
global.added = "scrafty" 
spr_raven = sprite_add("raven.png", 2, 1,1,0,0);
global.added = "raven" 
spr_starmie = sprite_add("starmie.png", 2, 1,1,0,0);
global.added = "starmie" 
spr_sneasel = sprite_add("sneasel.png", 2, 1,1,0,0);
global.added = "sneasel" 
spr_vanilluxe = sprite_add("vanilluxe.png", 2, 1,1,0,0);
global.added = "vanilluxe" 
spr_zoroark = sprite_add("zoroark.png", 2, 1,1,0,0);
global.added = "zoroark" 
spr_dusknoir = sprite_add("dusknoir.png", 2, 1,1,0,0);
global.added = "dusknoir" 
spr_tentaquil = sprite_add("tentaquil.png", 2, 1,1,0,0);
global.added = "tentaquil" 
spr_mienfoo = sprite_add("mienfoo.png", 2, 1,1,0,0);
global.added = "mienfoo" 
spr_strongbad = sprite_add("strongbad.png", 2, 1,1,0,0);
global.added = "strongbad" 
spr_dante = sprite_add("dante.png", 2, 1,1,0,0);
global.added = "dante" 
spr_torchic = sprite_add("torchic.png", 2, 1,1,0,0);
global.added = "torchic" 
spr_cradily = sprite_add("cradily.png", 2, 1,1,0,0);
global.added = "cradily" 
spr_catinthehat = sprite_add("catinthehat.png", 2, 1,1,0,0);
global.added = "catinthehat" 
spr_homestar = sprite_add("homestar.png", 2, 1,1,0,0);
global.added = "homestar" 
spr_foliat = sprite_add("foliat.png", 2, 1,1,0,0);
global.added = "foliat" 
spr_lileep = sprite_add("lileep.png", 2, 1,1,0,0);
global.added = "lileep" 
spr_trogdor = sprite_add("trogdor.png", 2, 1,1,0,0);
global.added = "trogdor" 
spr_florabri = sprite_add("florabri.png", 2, 1,1,0,0);
global.added = "florabri" 
spr_timburr = sprite_add("timburr.png", 2, 1,1,0,0);
global.added = "timburr" 
spr_florresum = sprite_add("florresum.png", 2, 1,1,0,0);
global.added = "florresum" 
spr_omanyte = sprite_add("omanyte.png", 2, 1,1,0,0);
global.added = "omanyte" 
spr_masquerain = sprite_add("masquerain.png", 2, 1,1,0,0);
global.added = "masquerain" 
spr_registeel = sprite_add("registeel.png", 2, 1,1,0,0);
global.added = "registeel" 
spr_swampert = sprite_add("swampert.png", 2, 1,1,0,0);
global.added = "swampert" 
spr_spiritomb = sprite_add("spiritomb.png", 2, 1,1,0,0);
global.added = "spiritomb" 
spr_regice = sprite_add("regice.png", 2, 1,1,0,0);
global.added = "regice" 
spr_sonichu = sprite_add("sonichu.png", 2, 1,1,0,0);
global.added = "sonichu" 
spr_regirock = sprite_add("regirock.png", 2, 1,1,0,0);
global.added = "regirock" 
spr_ferrothorn = sprite_add("ferrothorn.png", 2, 1,1,0,0);
global.added = "ferrothorn" 
spr_substitute = sprite_add("substitute.png", 2, 1,1,0,0);
global.added = "substitute" 
spr_rosechu = sprite_add("rosechu.png", 2, 1,1,0,0);
global.added = "rosechu" 
spr_leghorse = sprite_add("leghorse.png", 2, 1,1,0,0);
global.added = "leghorse" 
spr_vanillite = sprite_add("vanillite.png", 2, 1,1,0,0);
global.added = "vanillite" 
spr_ghostpokemon = sprite_add("ghostpokemon.png", 2, 1,1,0,0);
global.added = "ghostpokemon" 
spr_gurdurr = sprite_add("gurdurr.png", 2, 1,1,0,0);
global.added = "gurdurr" 
spr_creeper = sprite_add("creeper.png", 2, 1,1,0,0);
global.added = "creeper" 
spr_enderman = sprite_add("enderman.png", 2, 1,1,0,0);
global.added = "enderman" 
spr_silverfish = sprite_add("silverfish.png", 2, 1,1,0,0);
global.added = "silverfish" 
spr_slimecube = sprite_add("slimecube.png", 2, 1,1,0,0);
global.added = "slimecube" 
spr_magmacube = sprite_add("magmacube.png", 2, 1,1,0,0);
global.added = "magmacube" 
spr_wither = sprite_add("wither.png", 2, 1,1,0,0);
global.added = "wither" 
spr_beholder = sprite_add("beholder.png", 2, 1,1,0,0);
global.added = "beholder" 
spr_beholdereyeoffrost = sprite_add("beholdereyeoffrost.png", 2, 1,1,0,0);
global.added = "beholdereyeoffrost" 
spr_beholdereyeofchaos = sprite_add("beholdereyeofchaos.png", 2, 1,1,0,0);
global.added = "beholdereyeofchaos" 
spr_swablu = sprite_add("swablu.png", 2, 1,1,0,0);
global.added = "swablu" 
spr_vivillion = sprite_add("vivillion.png", 2, 1,1,0,0);
global.added = "vivillion" 
spr_missingno = sprite_add("missingno.png", 2, 1,1,0,0);
global.added = "missingno" 
spr_unowna = sprite_add("unowna.png", 2, 1,1,0,0);
global.added = "unowna" 
spr_unownb = sprite_add("unownb.png", 2, 1,1,0,0);
global.added = "unownb" 
spr_unownc = sprite_add("unownc.png", 2, 1,1,0,0);
global.added = "unownc" 
spr_unownd = sprite_add("unownd.png", 2, 1,1,0,0);
global.added = "unownd" 
spr_unowne = sprite_add("unowne.png", 2, 1,1,0,0);
global.added = "unowne" 
spr_unownf = sprite_add("unownf.png", 2, 1,1,0,0);
global.added = "unownf" 
spr_unowng = sprite_add("unowng.png", 2, 1,1,0,0);
global.added = "unowng" 
spr_unownh = sprite_add("unownh.png", 2, 1,1,0,0);
global.added = "unownh" 
spr_unowni = sprite_add("unowni.png", 2, 1,1,0,0);
global.added = "unowni" 
spr_unownj = sprite_add("unownj.png", 2, 1,1,0,0);
global.added = "unownj" 
spr_unownk = sprite_add("unownk.png", 2, 1,1,0,0);
global.added = "unownk" 
spr_unownl = sprite_add("unownl.png", 2, 1,1,0,0);
global.added = "unownl" 
spr_unownm = sprite_add("unownm.png", 2, 1,1,0,0);
global.added = "unownm" 
spr_unownn = sprite_add("unownn.png", 2, 1,1,0,0);
global.added = "unownn" 
spr_unowno = sprite_add("unowno.png", 2, 1,1,0,0);
global.added = "unowno" 
spr_unownp = sprite_add("unownp.png", 2, 1,1,0,0);
global.added = "unownp" 
spr_unownq = sprite_add("unownq.png", 2, 1,1,0,0);
global.added = "unownq" 
spr_unownr = sprite_add("unownr.png", 2, 1,1,0,0);
global.added = "unownr" 
spr_unowns = sprite_add("unowns.png", 2, 1,1,0,0);
global.added = "unowns" 
spr_unownt = sprite_add("unownt.png", 2, 1,1,0,0);
global.added = "unownt" 
spr_unownu = sprite_add("unownu.png", 2, 1,1,0,0);
global.added = "unownu" 
spr_unownv = sprite_add("unownv.png", 2, 1,1,0,0);
global.added = "unownv" 
spr_unownw = sprite_add("unownw.png", 2, 1,1,0,0);
global.added = "unownw" 
spr_unownx = sprite_add("unownx.png", 2, 1,1,0,0);
global.added = "unownx" 
spr_unowny = sprite_add("unowny.png", 2, 1,1,0,0);
global.added = "unowny" 
spr_unownz = sprite_add("unownz.png", 2, 1,1,0,0);
global.added = "unownz" 
spr_unownexclamation = sprite_add("unownexclamation.png", 2, 1,1,0,0);
global.added = "unownexclamation" 
spr_unownquestion = sprite_add("unownquestion.png", 2, 1,1,0,0);
global.added = "unownquestion" 
spr_hoppip = sprite_add("hoppip.png", 2, 1,1,0,0);
global.added = "hoppip" 
spr_ralts = sprite_add("ralts.png", 2, 1,1,0,0);
global.added = "ralts" 
spr_avion = sprite_add("avion.png", 2, 1,1,0,0);
global.added = "avion" 
spr_gwyn = sprite_add("gwyn.png", 2, 1,1,0,0);
global.added = "gwyn" 
spr_manus = sprite_add("manus.png", 2, 1,1,0,0);
global.added = "manus" 
spr_quelaag = sprite_add("quelaag.png", 2, 1,1,0,0);
global.added = "quelaag" 
spr_shadowlurkerf = sprite_add("shadowlurkerf.png", 2, 1,1,0,0);
global.added = "shadowlurkerf" 
spr_falsekingallant = sprite_add("falsekingallant.png", 2, 1,1,0,0);
global.added = "falsekingallant" 
spr_agumon = sprite_add("agumon.png", 2, 1,1,0,0);
global.added = "agumon" 
spr_kingallant = sprite_add("kingallant.png", 2, 1,1,0,0);
global.added = "kingallant" 
spr_blissey = sprite_add("blissey.png", 2, 1,1,0,0);
global.added = "blissey" 
spr_oldmonk = sprite_add("oldmonk.png", 2, 1,1,0,0);
global.added = "oldmonk" 
spr_gengar = sprite_add("gengar.png", 2, 1,1,0,0);
global.added = "gengar" 
spr_stormking = sprite_add("stormking.png", 2, 1,1,0,0);
global.added = "stormking" 
spr_leechmoger = sprite_add("leechmoger.png", 2, 1,1,0,0);
global.added = "leechmoger" 
spr_maideninblack = sprite_add("maideninblack.png", 2, 1,1,0,0);
global.added = "maideninblack" 
spr_xatu = sprite_add("xatu.png", 2, 1,1,0,0);
global.added = "xatu" 
spr_boneclaw = sprite_add("boneclaw.png", 2, 1,1,0,0);
global.added = "boneclaw" 
spr_troutmaskreplica = sprite_add("troutmaskreplica.png", 2, 1,1,0,0);
global.added = "troutmaskreplica" 
spr_satori = sprite_add("satori.png", 2, 1,1,0,0);
global.added = "satori" 
spr_shelgon = sprite_add("shelgon.png", 2, 1,1,0,0);
global.added = "shelgon" 
spr_demoman = sprite_add("demoman.png", 2, 1,1,0,0);
global.added = "demoman" 
spr_pyro = sprite_add("pyro.png", 2, 1,1,0,0);
global.added = "pyro" 
spr_spy = sprite_add("spy.png", 2, 1,1,0,0);
global.added = "spy" 
spr_medic = sprite_add("medic.png", 2, 1,1,0,0);
global.added = "medic" 
spr_scout = sprite_add("scout.png", 2, 1,1,0,0);
global.added = "scout" 
spr_soldier = sprite_add("soldier.png", 2, 1,1,0,0);
global.added = "soldier" 
spr_heavy = sprite_add("heavy.png", 2, 1,1,0,0);
global.added = "heavy" 
spr_isaacclarke = sprite_add("isaacclarke.png", 2, 1,1,0,0);
global.added = "isaacclarke" 
spr_limbokid = sprite_add("limbokid.png", 2, 1,1,0,0);
global.added = "limbokid" 
spr_magnezone = sprite_add("magnezone.png", 2, 1,1,0,0);
global.added = "magnezone" 
spr_cj = sprite_add("cj.png", 2, 1,1,0,0);
global.added = "cj" 
spr_sven = sprite_add("sven.png", 2, 1,1,0,0);
global.added = "sven" 
spr_vivec = sprite_add("vivec.png", 2, 1,1,0,0);
global.added = "vivec" 
spr_dagothur = sprite_add("dagothur.png", 2, 1,1,0,0);
global.added = "dagothur" 
spr_biker = sprite_add("biker.png", 2, 1,1,0,0);
global.added = "biker" 
spr_jacket = sprite_add("jacket.png", 2, 1,1,0,0);
global.added = "jacket" 
spr_slugma = sprite_add("slugma.png", 2, 1,1,0,0);
global.added = "slugma" 
spr_meditite = sprite_add("meditite.png", 2, 1,1,0,0);
global.added = "meditite" 
spr_fletchling = sprite_add("fletchling.png", 2, 1,1,0,0);
global.added = "fletchling" 
spr_haunter = sprite_add("haunter.png", 2, 1,1,0,0);
global.added = "haunter" 
spr_weepinbell = sprite_add("weepinbell.png", 2, 1,1,0,0);
global.added = "weepinbell" 
spr_maxwell = sprite_add("maxwell.png", 2, 1,1,0,0);
global.added = "maxwell" 
spr_shantosian = sprite_add("shantosian.png", 2, 1,1,0,0);
global.added = "shantosian" 
spr_aboleth = sprite_add("aboleth.png", 2, 1,1,0,0);
global.added = "aboleth" 
spr_astralstalker = sprite_add("astralstalker.png", 2, 1,1,0,0);
global.added = "astralstalker" 
spr_phantosian = sprite_add("phantosian.png", 2, 1,1,0,0);
global.added = "phantosian" 
spr_runeknight = sprite_add("runeknight.png", 2, 1,1,0,0);
global.added = "runeknight" 
spr_eagleman = sprite_add("eagleman.png", 2, 1,1,0,0);
global.added = "eagleman" 
spr_bigdaddy = sprite_add("bigdaddy.png", 2, 1,1,0,0);
global.added = "bigdaddy" 
spr_garbodor = sprite_add("garbodor.png", 2, 1,1,0,0);
global.added = "garbodor" 
spr_jirachi = sprite_add("jirachi.png", 2, 1,1,0,0);
global.added = "jirachi" 
spr_johnnybravo = sprite_add("johnnybravo.png", 2, 1,1,0,0);
global.added = "johnnybravo" 
spr_reimu = sprite_add("reimu.png", 2, 1,1,0,0);
global.added = "reimu" 
spr_clefairy = sprite_add("clefairy.png", 2, 1,1,0,0);
global.added = "clefairy" 
spr_mima = sprite_add("mima.png", 2, 1,1,0,0);
global.added = "mima" 
spr_arcanine = sprite_add("arcanine.png", 2, 1,1,0,0);
global.added = "arcanine" 
spr_zatchbell = sprite_add("zatchbell.png", 2, 1,1,0,0);
global.added = "zatchbell" 
spr_sanicthingkenoffast = sprite_add("sanicthingkenoffast.png", 2, 1,1,0,0);
global.added = "sanicthingkenoffast" 
spr_plaguedoctor = sprite_add("plaguedoctor.png", 2, 1,1,0,0);
global.added = "plaguedoctor" 
spr_tia = sprite_add("tia.png", 2, 1,1,0,0);
global.added = "tia" 
spr_gipsydanger = sprite_add("gipsydanger.png", 2, 1,1,0,0);
global.added = "gipsydanger" 
spr_kanchome = sprite_add("kanchome.png", 2, 1,1,0,0);
global.added = "kanchome" 
spr_mayorofcantown = sprite_add("mayorofcantown.png", 2, 1,1,0,0);
global.added = "mayorofcantown" 
spr_umagon = sprite_add("umagon.png", 2, 1,1,0,0);
global.added = "umagon" 
spr_honeydew = sprite_add("honeydew.png", 2, 1,1,0,0);
global.added = "honeydew" 
spr_mrkrabs = sprite_add("mrkrabs.png", 2, 1,1,0,0);
global.added = "mrkrabs" 
spr_sissel = sprite_add("sissel.png", 2, 1,1,0,0);
global.added = "sissel" 
spr_orangestarinfintry = sprite_add("orangestarinfintry.png", 2, 1,1,0,0);
global.added = "orangestarinfintry" 
spr_fawful = sprite_add("fawful.png", 2, 1,1,0,0);
global.added = "fawful" 
spr_constanza = sprite_add("constanza.png", 2, 1,1,0,0);
global.added = "constanza" 
spr_battletoad = sprite_add("battletoad.png", 2, 1,1,0,0);
global.added = "battletoad" 
spr_skelletor = sprite_add("skelletor.png", 2, 1,1,0,0);
global.added = "skelletor" 
spr_brago = sprite_add("brago.png", 2, 1,1,0,0);
global.added = "brago" 
spr_blu = sprite_add("blu.png", 2, 1,1,0,0);
global.added = "blu" 
spr_jingitaxias = sprite_add("jingitaxias.png", 2, 1,1,0,0);
global.added = "jingitaxias" 
spr_roadrunner = sprite_add("roadrunner.png", 2, 1,1,0,0);
global.added = "roadrunner" 
spr_dragonite = sprite_add("dragonite.png", 2, 1,1,0,0);
global.added = "dragonite" 
spr_umagonshudoruk = sprite_add("umagonshudoruk.png", 2, 1,1,0,0);
global.added = "umagonshudoruk" 
spr_umagongoshudoruk = sprite_add("umagongoshudoruk.png", 2, 1,1,0,0);
global.added = "umagongoshudoruk" 
spr_umagondioemuru = sprite_add("umagondioemuru.png", 2, 1,1,0,0);
global.added = "umagondioemuru" 
spr_roggenrola = sprite_add("roggenrola.png", 2, 1,1,0,0);
global.added = "roggenrola" 
spr_zeon = sprite_add("zeon.png", 2, 1,1,0,0);
global.added = "zeon" 
spr_solosis = sprite_add("solosis.png", 2, 1,1,0,0);
global.added = "solosis" 
spr_duosion = sprite_add("duosion.png", 2, 1,1,0,0);
global.added = "duosion" 
spr_spoink = sprite_add("spoink.png", 2, 1,1,0,0);
global.added = "spoink" 
spr_billcipher = sprite_add("billcipher.png", 2, 1,1,0,0);
global.added = "billcipher" 
spr_skipper = sprite_add("skipper.png", 2, 1,1,0,0);
global.added = "skipper" 
spr_private = sprite_add("private.png", 2, 1,1,0,0);
global.added = "private" 
spr_rico = sprite_add("rico.png", 2, 1,1,0,0);
global.added = "rico" 
spr_kowalski = sprite_add("kowalski.png", 2, 1,1,0,0);
global.added = "kowalski" 
spr_hans = sprite_add("hans.png", 2, 1,1,0,0);
global.added = "hans" 
spr_drsloth = sprite_add("drsloth.png", 2, 1,1,0,0);
global.added = "drsloth" 
spr_owl = sprite_add("owl.png", 2, 1,1,0,0);
global.added = "owl" 
spr_masterchief = sprite_add("masterchief.png", 2, 1,1,0,0);
global.added = "masterchief" 
spr_crobat = sprite_add("crobat.png", 2, 1,1,0,0);
global.added = "crobat" 
spr_zubat = sprite_add("zubat.png", 2, 1,1,0,0);
global.added = "zubat" 
spr_jcdenton = sprite_add("jcdenton.png", 2, 1,1,0,0);
global.added = "jcdenton" 
spr_bomberman = sprite_add("bomberman.png", 2, 1,1,0,0);
global.added = "bomberman" 
spr_coolspot = sprite_add("coolspot.png", 2, 1,1,0,0);
global.added = "coolspot" 
spr_panty = sprite_add("panty.png", 2, 1,1,0,0);
global.added = "panty" 
spr_stocking = sprite_add("stocking.png", 2, 1,1,0,0);
global.added = "stocking" 
spr_frankerz = sprite_add("frankerz.png", 2, 1,1,0,0);
global.added = "frankerz" 
spr_rance = sprite_add("rance.png", 2, 1,1,0,0);
global.added = "rance" 
spr_chie = sprite_add("chie.png", 2, 1,1,0,0);
global.added = "chie" 
spr_cormano = sprite_add("cormano.png", 2, 1,1,0,0);
global.added = "cormano" 
spr_shake = sprite_add("shake.png", 2, 1,1,0,0);
global.added = "shake" 
spr_sweetbro = sprite_add("sweetbro.png", 2, 1,1,0,0);
global.added = "sweetbro" 
spr_midna = sprite_add("midna.png", 2, 1,1,0,0);
global.added = "midna" 
spr_hellajeff = sprite_add("hellajeff.png", 2, 1,1,0,0);
global.added = "hellajeff" 
spr_meatwaf = sprite_add("meatwaf.png", 2, 1,1,0,0);
global.added = "meatwaf" 
spr_raiden = sprite_add("raiden.png", 2, 1,1,0,0);
global.added = "raiden" 
spr_emi = sprite_add("emi.png", 2, 1,1,0,0);
global.added = "emi" 
spr_geromy = sprite_add("geromy.png", 2, 1,1,0,0);
global.added = "geromy" 
spr_gordonfreeman = sprite_add("gordonfreeman.png", 2, 1,1,0,0);
global.added = "gordonfreeman" 
spr_pacman = sprite_add("pacman.png", 2, 1,1,0,0);
global.added = "pacman" 
spr_beckett = sprite_add("beckett.png", 2, 1,1,0,0);
global.added = "beckett" 
spr_blackrose = sprite_add("blackrose.png", 2, 1,1,0,0);
global.added = "blackrose" 
spr_met = sprite_add("met.png", 2, 1,1,0,0);
global.added = "met" 
spr_spaceinvader = sprite_add("spaceinvader.png", 2, 1,1,0,0);
global.added = "spaceinvader" 
spr_litwick = sprite_add("litwick.png", 2, 1,1,0,0);
global.added = "litwick" 
spr_solaire = sprite_add("solaire.png", 2, 1,1,0,0);
global.added = "solaire" 
spr_zekedunbar = sprite_add("zekedunbar.png", 2, 1,1,0,0);
global.added = "zekedunbar" 
spr_malkavian = sprite_add("malkavian.png", 2, 1,1,0,0);
global.added = "malkavian" 
spr_peashooter = sprite_add("peashooter.png", 2, 1,1,0,0);
global.added = "peashooter" 
spr_pumkin = sprite_add("pumkin.png", 2, 1,1,0,0);
global.added = "pumkin" 
spr_phoenixwright = sprite_add("phoenixwright.png", 2, 1,1,0,0);
global.added = "phoenixwright" 
spr_scoobywerkstat = sprite_add("scoobywerkstat.png", 2, 1,1,0,0);
global.added = "scoobywerkstat" 
spr_armoredarmadillo = sprite_add("armoredarmadillo.png", 2, 1,1,0,0);
global.added = "armoredarmadillo" 
spr_megamanx = sprite_add("megamanx.png", 2, 1,1,0,0);
global.added = "megamanx" 
spr_jetstreamsam = sprite_add("jetstreamsam.png", 2, 1,1,0,0);
global.added = "jetstreamsam" 
spr_gene = sprite_add("gene.png", 2, 1,1,0,0);
global.added = "gene" 
spr_jotarokujo = sprite_add("jotarokujo.png", 2, 1,1,0,0);
global.added = "jotarokujo" 
spr_megamanexe = sprite_add("megamanexe.png", 2, 1,1,0,0);
global.added = "megamanexe" 
spr_leila = sprite_add("leila.png", 2, 1,1,0,0);
global.added = "leila" 
spr_danmandel = sprite_add("danmandel.png", 2, 1,1,0,0);
global.added = "danmandel" 
spr_elisepearson = sprite_add("elisepearson.png", 2, 1,1,0,0);
global.added = "elisepearson" 
spr_chrispearson = sprite_add("chrispearson.png", 2, 1,1,0,0);
global.added = "chrispearson" 
spr_sif = sprite_add("sif.png", 2, 1,1,0,0);
global.added = "sif" 
spr_strayhumanity = sprite_add("strayhumanity.png", 2, 1,1,0,0);
global.added = "strayhumanity" 
spr_crestfallenwarrior = sprite_add("crestfallenwarrior.png", 2, 1,1,0,0);
global.added = "crestfallenwarrior" 
spr_caprademon = sprite_add("caprademon.png", 2, 1,1,0,0);
global.added = "caprademon" 
spr_gwyndolin = sprite_add("gwyndolin.png", 2, 1,1,0,0);
global.added = "gwyndolin" 
spr_nier = sprite_add("nier.png", 2, 1,1,0,0);
global.added = "nier" 
spr_weiss = sprite_add("weiss.png", 2, 1,1,0,0);
global.added = "weiss" 
spr_ryu = sprite_add("ryu.png", 2, 1,1,0,0);
global.added = "ryu" 
spr_zangief = sprite_add("zangief.png", 2, 1,1,0,0);
global.added = "zangief" 
spr_yotsuba = sprite_add("yotsuba.png", 2, 1,1,0,0);
global.added = "yotsuba" 
spr_monokuma = sprite_add("monokuma.png", 2, 1,1,0,0);
global.added = "monokuma" 
spr_shade = sprite_add("shade.png", 2, 1,1,0,0);
global.added = "shade" 
spr_chacha = sprite_add("chacha.png", 2, 1,1,0,0);
global.added = "chacha" 
spr_lucas = sprite_add("lucas.png", 2, 1,1,0,0);
global.added = "lucas" 
spr_kenmasters = sprite_add("kenmasters.png", 2, 1,1,0,0);
global.added = "kenmasters" 
spr_aigis = sprite_add("aigis.png", 2, 1,1,0,0);
global.added = "aigis" 
spr_sniper = sprite_add("sniper.png", 2, 1,1,0,0);
global.added = "sniper" 
spr_rikafurude = sprite_add("rikafurude.png", 2, 1,1,0,0);
global.added = "rikafurude" 
spr_chernoalpha = sprite_add("chernoalpha.png", 2, 1,1,0,0);
global.added = "chernoalpha" 
spr_strikereureka = sprite_add("strikereureka.png", 2, 1,1,0,0);
global.added = "strikereureka" 
spr_burmyplant = sprite_add("burmyplant.png", 2, 1,1,0,0);
global.added = "burmyplant" 
spr_wormadamplant = sprite_add("wormadamplant.png", 2, 1,1,0,0);
global.added = "wormadamplant" 
spr_wormadamtrash = sprite_add("wormadamtrash.png", 2, 1,1,0,0);
global.added = "wormadamtrash" 
spr_wormadamsand = sprite_add("wormadamsand.png", 2, 1,1,0,0);
global.added = "wormadamsand" 
spr_cubone = sprite_add("cubone.png", 2, 1,1,0,0);
global.added = "cubone" 
spr_meowth = sprite_add("meowth.png", 2, 1,1,0,0);
global.added = "meowth" 
spr_beat = sprite_add("beat.png", 2, 1,1,0,0);
global.added = "beat" 
spr_isabelle = sprite_add("isabelle.png", 2, 1,1,0,0);
global.added = "isabelle" 
spr_balrog = sprite_add("balrog.png", 2, 1,1,0,0);
global.added = "balrog" 
spr_takamaru = sprite_add("takamaru.png", 2, 1,1,0,0);
global.added = "takamaru" 


