global.attack = "shoot"
global.stamp = "orb"
global.color = "red"

numb = floor(random(180));

if numb = 0 {{sprite_index = thegreentie;} {name = "thegreentie"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 1 {{sprite_index = businessbanana;} {name = "businessbanana"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 2 {{sprite_index = dennot;} {name = "dennot"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 3 {{sprite_index = mario;} {name = "mario"} {global.attack = "shoot"} {global.stamp = "fire"}  { global.color = "orange"}} 
if numb = 4 {{sprite_index = luigi;} {name = "luigi"} {global.attack = "shoot"} {global.stamp = "fire"}  { global.color = "green"}} 
if numb = 5 {{sprite_index = bowser;} {name = "bowser"} {global.attack = "trap"} {global.stamp = "fire"}  { global.color = "red"}} 
if numb = 6 {{sprite_index = peach;} {name = "peach"} {global.attack = "hit"} {global.stamp = "stick"}  { global.color = "pink"}} 
if numb = 7 {{sprite_index = drmario;} {name = "drmario"} {global.attack = "shoot"} {global.stamp = "orb"}  { global.color = "random"}} 
if numb = 8 {{sprite_index = yoshi;} {name = "yoshi"} {global.attack = "hit"} {global.stamp = "whip"}  { global.color = "pink"}} 
if numb = 9 {{sprite_index = pit;} {name = "pit"} {global.attack = "shoot"} {global.stamp = "arrow"}  { global.color = "yellow"}} 
if numb = 10 {{sprite_index = captainfalcon;} {name = "captainfalcon"} {global.attack = "hit"} {global.stamp = "fist"}  { global.color = "red"}} 
if numb = 11 {{sprite_index = mrgameandwatch;} {name = "mrgameandwatch"} {global.attack = "shoot"} {global.stamp = "orb"}  { global.color = "black"}} 
if numb = 12 {{sprite_index = rob;} {name = "rob"} {global.attack = "shoot"} {global.stamp = "beam"}  { global.color = "pink"}} 
if numb = 13 {{sprite_index = pikachu;} {name = "pikachu"} {global.attack = "hit"} {global.stamp = "spark"}  { global.color = "yellow"}} 
if numb = 14 {{sprite_index = bulbasaur;} {name = "bulbasaur"} {global.attack = "hit"} {global.stamp = "whip"}  { global.color = "green"}} 
if numb = 15 {{sprite_index = ivysaur;} {name = "ivysaur"} {global.attack = "hit"} {global.stamp = "whip"}  { global.color = "green"}} 
if numb = 16 {{sprite_index = venusaur;} {name = "venusaur"} {global.attack = "hit"} {global.stamp = "whip"}  { global.color = "green"}} 
if numb = 17 {{sprite_index = charmander;} {name = "charmander"} {global.attack = "trap"} {global.stamp = "fire"}  { global.color = "orange"}} 
if numb = 18 {{sprite_index = charmeleon;} {name = "charmeleon"} {global.attack = "trap"} {global.stamp = "fire"}  { global.color = "orange"}} 
if numb = 19 {{sprite_index = charizard;} {name = "charizard"} {global.attack = "trap"} {global.stamp = "fire"}  { global.color = "orange"}} 
if numb = 20 {{sprite_index = link;} {name = "link"} {global.attack = "hit"} {global.stamp = "sword"}  { global.color = "silver"}} 
if numb = 21 {{sprite_index = zelda;} {name = "zelda"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 22 {{sprite_index = sheik;} {name = "sheik"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 23 {{sprite_index = ganondorf;} {name = "ganondorf"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 24 {{sprite_index = sonic;} {name = "sonic"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "blue"}} 
if numb = 25 {{sprite_index = wario;} {name = "wario"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "gold"}} 
if numb = 26 {{sprite_index = pikminred;} {name = "pikminred"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 27 {{sprite_index = pikminyellow;} {name = "pikminyellow"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 28 {{sprite_index = pikminblue;} {name = "pikminblue"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 29 {{sprite_index = pikminwhite;} {name = "pikminwhite"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 30 {{sprite_index = pikminpurple;} {name = "pikminpurple"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 31 {{sprite_index = engineer;} {name = "engineer"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 32 {{sprite_index = steve;} {name = "steve"} {global.attack = "hit"} {global.stamp = "sword"}  { global.color = "blue"}} 
if numb = 33 {{sprite_index = magickared;} {name = "magickared"} {global.attack = "trap"} {global.stamp = "fire"}  { global.color = "red"}} 
if numb = 34 {{sprite_index = magickablue;} {name = "magickablue"} {global.attack = "shoot"} {global.stamp = "beam"}  { global.color = "blue"}} 
if numb = 35 {{sprite_index = magickayellow;} {name = "magickayellow"} {global.attack = "bomb"} {global.stamp = "mine"}  { global.color = "yellow"}} 
if numb = 36 {{sprite_index = magickagreen;} {name = "magickagreen"} {global.attack = "shoot"} {global.stamp = "beam"}  { global.color = "green"}} 
if numb = 37 {{sprite_index = santaclaus;} {name = "santaclaus"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 38 {{sprite_index = blossom;} {name = "blossom"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 39 {{sprite_index = bubbles;} {name = "bubbles"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 40 {{sprite_index = buttercup;} {name = "buttercup"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 41 {{sprite_index = eddy;} {name = "eddy"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 42 {{sprite_index = edd;} {name = "edd"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 43 {{sprite_index = ed;} {name = "ed"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 44 {{sprite_index = courage;} {name = "courage"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 45 {{sprite_index = gir;} {name = "gir"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 46 {{sprite_index = spongebob;} {name = "spongebob"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 47 {{sprite_index = captainknuckles;} {name = "captainknuckles"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 48 {{sprite_index = flapjack;} {name = "flapjack"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 49 {{sprite_index = chowder;} {name = "chowder"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 50 {{sprite_index = shnitzel;} {name = "shnitzel"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 51 {{sprite_index = waluigi;} {name = "waluigi"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 52 {{sprite_index = galvantula;} {name = "galvantula"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 53 {{sprite_index = electivire;} {name = "electivire"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 54 {{sprite_index = reuniclus;} {name = "reuniclus"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 55 {{sprite_index = pikminrock;} {name = "pikminrock"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 56 {{sprite_index = pikminwinged;} {name = "pikminwinged"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 57 {{sprite_index = spinda;} {name = "spinda"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 58 {{sprite_index = mrdickens;} {name = "mrdickens"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 59 {{sprite_index = castform;} {name = "castform"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 60 {{sprite_index = castformsunny;} {name = "castformsunny"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 61 {{sprite_index = castformrainy;} {name = "castformrainy"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 62 {{sprite_index = castformsnowy;} {name = "castformsnowy"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 63 {{sprite_index = beheeyem;} {name = "beheeyem"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 64 {{sprite_index = celebi;} {name = "celebi"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 65 {{sprite_index = deoxys;} {name = "deoxys"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 66 {{sprite_index = deoxysglobal.attack;} {name = "deoxysattack"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 67 {{sprite_index = deoxysdefense;} {name = "deoxysdefense"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 68 {{sprite_index = deoxysspeed;} {name = "deoxysspeed"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 69 {{sprite_index = diglet;} {name = "diglet"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 70 {{sprite_index = ditto;} {name = "ditto"} {global.attack = "copycat"} {global.stamp = "hand"}  { global.color = "pink"}} 
if numb = 71 {{sprite_index = drifloon;} {name = "drifloon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 72 {{sprite_index = electrode;} {name = "electrode"} {global.attack = "explosion"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 73 {{sprite_index = escavalier;} {name = "escavalier"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 74 {{sprite_index = froslass;} {name = "froslass"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 75 {{sprite_index = genescect;} {name = "genescect"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 76 {{sprite_index = geodude;} {name = "geodude"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 77 {{sprite_index = gastly;} {name = "gastly"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 78 {{sprite_index = giratinaorigin;} {name = "giratinaorigin"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 79 {{sprite_index = golurk;} {name = "golurk"} {global.attack = "hit"} {global.stamp = "fist"}  { global.color = "blue"}} 
if numb = 80 {{sprite_index = hydreigon;} {name = "hydreigon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 81 {{sprite_index = kyurem;} {name = "kyurem"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 82 {{sprite_index = lunatone;} {name = "lunatone"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 83 {{sprite_index = solrock;} {name = "solrock"} {global.attack = "trap"} {global.stamp = "fire"}  { global.color = "orange"}} 
if numb = 84 {{sprite_index = magnemite;} {name = "magnemite"} {global.attack = "hit"} {global.stamp = "spark"}  { global.color = "yellow"}} 
if numb = 85 {{sprite_index = metagross;} {name = "metagross"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 86 {{sprite_index = ninjask;} {name = "ninjask"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 87 {{sprite_index = poliwag;} {name = "poliwag"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 88 {{sprite_index = psyduck;} {name = "psyduck"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 89 {{sprite_index = regigigas;} {name = "regigigas"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 90 {{sprite_index = rotom;} {name = "rotom"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 91 {{sprite_index = rotomfan;} {name = "rotomfan"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 92 {{sprite_index = rotomfrost;} {name = "rotomfrost"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 93 {{sprite_index = rotomheat;} {name = "rotomheat"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 94 {{sprite_index = rotomwash;} {name = "rotomwash"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 95 {{sprite_index = rotommow;} {name = "rotommow"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 96 {{sprite_index = sawk;} {name = "sawk"} {global.attack = "hit"} {global.stamp = "fist"}  { global.color = ""}} 
if numb = 97 {{sprite_index = scolipede;} {name = "scolipede"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 98 {{sprite_index = shedinja;} {name = "shedinja"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 99 {{sprite_index = simisage;} {name = "simisage"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 100 {{sprite_index = sigilyph;} {name = "sigilyph"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 101 {{sprite_index = tentacruel;} {name = "tentacruel"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 102 {{sprite_index = angrybirdred;} {name = "angrybirdred"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "red"}} 
if numb = 103 {{sprite_index = angrybirdwhite;} {name = "angrybirdwhite"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "white"}} 
if numb = 104 {{sprite_index = angrybirdyellow;} {name = "angrybirdyellow"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "yellow"}} 
if numb = 105 {{sprite_index = frosty;} {name = "frosty"} {global.attack = "shoot"} {global.stamp = "orb"}  { global.color = "white"}} 
if numb = 106 {{sprite_index = professorlayton;} {name = "professorlayton"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 107 {{sprite_index = navi;} {name = "navi"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "light blue"}} 
if numb = 108 {{sprite_index = nyancat;} {name = "nyancat"} {global.attack = "boost"} {global.stamp = "wave"}  { global.color = "rainbow"}} 
if numb = 109 {{sprite_index = squirtle;} {name = "squirtle"} {global.attack = "shoot"} {global.stamp = "beam"}  { global.color = "blue"}} 
if numb = 110 {{sprite_index = volcarona;} {name = "volcarona"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 111 {{sprite_index = voltorb;} {name = "voltorb"} {global.attack = "explosion"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 112 {{sprite_index = wobbuffet;} {name = "wobbuffet"} {global.attack = "hit"} {global.stamp = "hand"}  { global.color = "pink"}} 
if numb = 113 {{sprite_index = tentacool;} {name = "tentacool"} {global.attack = "hit"} {global.stamp = "whip"}  { global.color = "blue"}} 
if numb = 114 {{sprite_index = shuckle;} {name = "shuckle"} {global.attack = "hit"} {global.stamp = "whip"}  { global.color = "blue"}} 
if numb = 115 {{sprite_index = sneakypebbles;} {name = "sneakypebbles"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 116 {{sprite_index = natu;} {name = "natu"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 117 {{sprite_index = trapinch;} {name = "trapinch"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 118 {{sprite_index = cofagrigus;} {name = "cofagrigus"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 119 {{sprite_index = mienshao;} {name = "mienshao"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 120 {{sprite_index = baitfish;} {name = "baitfish"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 121 {{sprite_index = mudkip;} {name = "mudkip"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 122 {{sprite_index = zangoose;} {name = "zangoose"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 123 {{sprite_index = audino;} {name = "audino"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 124 {{sprite_index = vibrava;} {name = "vibrava"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 125 {{sprite_index = insidetheflyingmachine;} {name = "insidetheflyingmachine"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 126 {{sprite_index = azelf;} {name = "azelf"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 127 {{sprite_index = cancer;} {name = "cancer"} {global.attack = "shoot"} {global.stamp = "stick"}  { global.color = "red"}} 
if numb = 128 {{sprite_index = cryogonal;} {name = "cryogonal"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 129 {{sprite_index = flygon;} {name = "flygon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 130 {{sprite_index = pinkiepie;} {name = "pinkiepie"} {global.attack = "explosion"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 131 {{sprite_index = uxie;} {name = "uxie"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 132 {{sprite_index = throh;} {name = "throh"} {global.attack = "hit"} {global.stamp = "hand"}  { global.color = ""}} 
if numb = 133 {{sprite_index = swanna;} {name = "swanna"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 134 {{sprite_index = geno;} {name = "geno"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 135 {{sprite_index = mesprit;} {name = "mesprit"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 136 {{sprite_index = marshtomp;} {name = "marshtomp"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 137 {{sprite_index = pokemonegg;} {name = "pokemonegg"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 138 {{sprite_index = pyramidhead;} {name = "pyramidhead"} {global.attack = "hit"} {global.stamp = "sword"}  { global.color = "gray"}} 
if numb = 139 {{sprite_index = absol;} {name = "absol"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 140 {{sprite_index = sanic;} {name = "sanic"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "blue"}} 
if numb = 141 {{sprite_index = saniclil;} {name = "saniclil"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "blue"}} 
if numb = 142 {{sprite_index = poisonmushroom;} {name = "poisonmushroom"} {global.attack = "boost"} {global.stamp = "dust"}  { global.color = "purple"}} 
if numb = 143 {{sprite_index = druddigon;} {name = "druddigon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 144 {{sprite_index = gardevoir;} {name = "gardevoir"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 145 {{sprite_index = twilightsparkle;} {name = "twilightsparkle"} {global.attack = "shoot"} {global.stamp = "spark"}  { global.color = "purple"}} 
if numb = 146 {{sprite_index = doge;} {name = "doge"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 147 {{sprite_index = nito;} {name = "nito"} {global.attack = "hit"} {global.stamp = "sword"}  { global.color = "white"}} 
if numb = 148 {{sprite_index = seaththescaleless;} {name = "seaththescaleless"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 149 {{sprite_index = uboa;} {name = "uboa"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 150 {{sprite_index = penetrator;} {name = "penetrator"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 151 {{sprite_index = towerknight;} {name = "towerknight"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 152 {{sprite_index = rainbowdash;} {name = "rainbowdash"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 153 {{sprite_index = zerotwo;} {name = "zerotwo"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 154 {{sprite_index = adjudicator;} {name = "adjudicator"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 155 {{sprite_index = smough;} {name = "smough"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 156 {{sprite_index = ornstein;} {name = "ornstein"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 157 {{sprite_index = madotsuki;} {name = "madotsuki"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 158 {{sprite_index = kirby;} {name = "kirby"} {global.attack = "copycat"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 159 {{sprite_index = luvdisc;} {name = "luvdisc"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 160 {{sprite_index = honedge;} {name = "honedge"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 161 {{sprite_index = trevenant;} {name = "trevenant"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 162 {{sprite_index = xerneas;} {name = "xerneas"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 163 {{sprite_index = slenderman;} {name = "slenderman"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 164 {{sprite_index = chikorita;} {name = "chikorita"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 165 {{sprite_index = honchkrow;} {name = "honchkrow"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 166 {{sprite_index = applejack;} {name = "applejack"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 167 {{sprite_index = muricaneagle;} {name = "muricaneagle"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 168 {{sprite_index = duckhunt;} {name = "duckhunt"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 169 {{sprite_index = duckhunt2;} {name = "duckhunt2"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 170 {{sprite_index = duckhunt3;} {name = "duckhunt3"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 171 {{sprite_index = wacky;} {name = "wacky"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 172 {{sprite_index = rarity;} {name = "rarity"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 173 {{sprite_index = wooper;} {name = "wooper"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 174 {{sprite_index = hypno;} {name = "hypno"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 175 {{sprite_index = talonflame;} {name = "talonflame"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 176 {{sprite_index = isaac;} {name = "isaac"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 177 {{sprite_index = crustle;} {name = "crustle"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 178 {{sprite_index = gigalith;} {name = "gigalith"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 179 {{sprite_index = meatboy;} {name = "meatboy"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 180 {{sprite_index = fluttershy;} {name = "fluttershy"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 181 {{sprite_index = geralt;} {name = "geralt"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 182 {{sprite_index = megaampharos;} {name = "megaampharos"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 183 {{sprite_index = nosepass;} {name = "nosepass"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 184 {{sprite_index = mew;} {name = "mew"} {global.attack = "random"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 185 {{sprite_index = dialga;} {name = "dialga"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 186 {{sprite_index = ampharos;} {name = "ampharos"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 187 {{sprite_index = nyarlathoep;} {name = "nyarlathoep"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 188 {{sprite_index = latias;} {name = "latias"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 189 {{sprite_index = cthulhu;} {name = "cthulhu"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 190 {{sprite_index = latios;} {name = "latios"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 191 {{sprite_index = stantler;} {name = "stantler"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 192 {{sprite_index = yogsothoth;} {name = "yogsothoth"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 193 {{sprite_index = pingu;} {name = "pingu"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 194 {{sprite_index = palkia;} {name = "palkia"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 195 {{sprite_index = shoggoth;} {name = "shoggoth"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 196 {{sprite_index = smeargle;} {name = "smeargle"} {global.attack = "random"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 197 {{sprite_index = bayleaf;} {name = "bayleaf"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 198 {{sprite_index = megablaziken;} {name = "megablaziken"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 199 {{sprite_index = ghroth;} {name = "ghroth"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 200 {{sprite_index = megamawile;} {name = "megamawile"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 201 {{sprite_index = tailow;} {name = "tailow"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 202 {{sprite_index = weedle;} {name = "weedle"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 203 {{sprite_index = swellow;} {name = "swellow"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 204 {{sprite_index = koffing;} {name = "koffing"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 205 {{sprite_index = snorunt;} {name = "snorunt"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 206 {{sprite_index = linux;} {name = "linux"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 207 {{sprite_index = sableye;} {name = "sableye"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 208 {{sprite_index = spike;} {name = "spike"} {global.attack = "bite"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 209 {{sprite_index = elderthing;} {name = "elderthing"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 210 {{sprite_index = shadowlurkerm;} {name = "shadowlurkerm"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 211 {{sprite_index = ostrava;} {name = "ostrava"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 212 {{sprite_index = havel;} {name = "havel"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 213 {{sprite_index = ferroseed;} {name = "ferroseed"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 214 {{sprite_index = meganium;} {name = "meganium"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 215 {{sprite_index = sudowoodo;} {name = "sudowoodo"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 216 {{sprite_index = gulpin;} {name = "gulpin"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 217 {{sprite_index = rambi;} {name = "rambi"} {global.attack = "charge"} {global.stamp = ""}  { global.color = ""}} 
if numb = 218 {{sprite_index = princesscelestia;} {name = "princesscelestia"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 219 {{sprite_index = marvelouschester;} {name = "marvelouschester"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 220 {{sprite_index = snover;} {name = "snover"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 221 {{sprite_index = artorias;} {name = "artorias"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 222 {{sprite_index = abomasnow;} {name = "abomasnow"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 223 {{sprite_index = tangrowth;} {name = "tangrowth"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "navy"}} 
if numb = 224 {{sprite_index = haxorus;} {name = "haxorus"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 225 {{sprite_index = surskit;} {name = "surskit"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 226 {{sprite_index = oneofthefourwings;} {name = "oneofthefourwings"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 227 {{sprite_index = maneatermildred;} {name = "maneatermildred"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 228 {{sprite_index = megaman;} {name = "megaman"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 229 {{sprite_index = squiddle;} {name = "squiddle"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 230 {{sprite_index = sawsbuckwinter;} {name = "sawsbuckwinter"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 231 {{sprite_index = porygonz;} {name = "porygonz"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 232 {{sprite_index = ciarin;} {name = "ciarin"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 233 {{sprite_index = sawsbuckspring;} {name = "sawsbuckspring"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 234 {{sprite_index = sawsbucksummer;} {name = "sawsbucksummer"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 235 {{sprite_index = sawsbuckautumn;} {name = "sawsbuckautumn"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 236 {{sprite_index = stunfisk;} {name = "stunfisk"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 237 {{sprite_index = starly;} {name = "starly"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 238 {{sprite_index = lautrec;} {name = "lautrec"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 239 {{sprite_index = musharna;} {name = "musharna"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 240 {{sprite_index = munna;} {name = "munna"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 241 {{sprite_index = porygon2;} {name = "porygon2"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 242 {{sprite_index = doran;} {name = "doran"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 243 {{sprite_index = sunkern;} {name = "sunkern"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 244 {{sprite_index = porygon;} {name = "porygon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 245 {{sprite_index = sunflora;} {name = "sunflora"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 246 {{sprite_index = scizor;} {name = "scizor"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 247 {{sprite_index = foongus;} {name = "foongus"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 248 {{sprite_index = amoongus;} {name = "amoongus"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 249 {{sprite_index = silcoon;} {name = "silcoon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 250 {{sprite_index = cascoon;} {name = "cascoon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 251 {{sprite_index = duskull;} {name = "duskull"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 252 {{sprite_index = probopass;} {name = "probopass"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 253 {{sprite_index = lampent;} {name = "lampent"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 254 {{sprite_index = girafarig;} {name = "girafarig"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 255 {{sprite_index = murkrow;} {name = "murkrow"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 256 {{sprite_index = maractus;} {name = "maractus"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 257 {{sprite_index = jellyfish;} {name = "jellyfish"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 258 {{sprite_index = rapidash;} {name = "rapidash"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 259 {{sprite_index = rufflet;} {name = "rufflet"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 260 {{sprite_index = peliper;} {name = "peliper"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 261 {{sprite_index = quote;} {name = "quote"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 262 {{sprite_index = curlybrace;} {name = "curlybrace"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 263 {{sprite_index = cyndaquil;} {name = "cyndaquil"} {global.attack = "fire"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 264 {{sprite_index = piranhaplant;} {name = "piranhaplant"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 265 {{sprite_index = braviary;} {name = "braviary"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 266 {{sprite_index = conkeldurr;} {name = "conkeldurr"} {global.attack = "stick"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 267 {{sprite_index = yamask;} {name = "yamask"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 268 {{sprite_index = croagunk;} {name = "croagunk"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 269 {{sprite_index = lumineon;} {name = "lumineon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 270 {{sprite_index = scraggy;} {name = "scraggy"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = ""}} 
if numb = 271 {{sprite_index = toxicroak;} {name = "toxicroak"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 272 {{sprite_index = vanillish;} {name = "vanillish"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 273 {{sprite_index = princessluna;} {name = "princessluna"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 274 {{sprite_index = staryu;} {name = "staryu"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 275 {{sprite_index = scrafty;} {name = "scrafty"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = ""}} 
if numb = 276 {{sprite_index = raven;} {name = "raven"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 277 {{sprite_index = starmie;} {name = "starmie"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 278 {{sprite_index = sneasel;} {name = "sneasel"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 279 {{sprite_index = vanilluxe;} {name = "vanilluxe"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 280 {{sprite_index = zoroark;} {name = "zoroark"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 281 {{sprite_index = dusknoir;} {name = "dusknoir"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 282 {{sprite_index = tentaquil;} {name = "tentaquil"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 283 {{sprite_index = mienfoo;} {name = "mienfoo"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 284 {{sprite_index = strongbad;} {name = "strongbad"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 285 {{sprite_index = dante;} {name = "dante"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 286 {{sprite_index = torchic;} {name = "torchic"} {global.attack = "fire"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 287 {{sprite_index = cradily;} {name = "cradily"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 288 {{sprite_index = catinthehat;} {name = "catinthehat"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 289 {{sprite_index = homestar;} {name = "homestar"} {global.attack = "stick"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 290 {{sprite_index = foliat;} {name = "foliat"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 291 {{sprite_index = lileep;} {name = "lileep"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 292 {{sprite_index = trogdor;} {name = "trogdor"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 293 {{sprite_index = florabri;} {name = "florabri"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 294 {{sprite_index = timburr;} {name = "timburr"} {global.attack = "stick"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 295 {{sprite_index = florresum;} {name = "florresum"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 296 {{sprite_index = omanyte;} {name = "omanyte"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 297 {{sprite_index = masquerain;} {name = "masquerain"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 298 {{sprite_index = registeel;} {name = "registeel"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "silver"}} 
if numb = 299 {{sprite_index = swampert;} {name = "swampert"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 300 {{sprite_index = spiritomb;} {name = "spiritomb"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 301 {{sprite_index = regice;} {name = "regice"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 302 {{sprite_index = sonichu;} {name = "sonichu"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 303 {{sprite_index = regirock;} {name = "regirock"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 304 {{sprite_index = ferrothorn;} {name = "ferrothorn"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 305 {{sprite_index = substitute;} {name = "substitute"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 306 {{sprite_index = rosechu;} {name = "rosechu"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 307 {{sprite_index = leghorse;} {name = "leghorse"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 308 {{sprite_index = vanillite;} {name = "vanillite"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 309 {{sprite_index = ghostpokemon;} {name = "ghostpokemon"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 310 {{sprite_index = gurdurr;} {name = "gurdurr"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 311 {{sprite_index = creeper;} {name = "creeper"} {global.attack = "explosion"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 312 {{sprite_index = enderman;} {name = "enderman"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 313 {{sprite_index = silverfish;} {name = "silverfish"} {global.attack = "charge"} {global.stamp = ""}  { global.color = "grey"}} 
if numb = 314 {{sprite_index = slimecube;} {name = "slimecube"} {global.attack = "charge"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 315 {{sprite_index = magmacube;} {name = "magmacube"} {global.attack = "charge"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 316 {{sprite_index = wither;} {name = "wither"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 317 {{sprite_index = beholder;} {name = "beholder"} {global.attack = "random"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 318 {{sprite_index = beholdereyeoffrost;} {name = "beholdereyeoffrost"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 319 {{sprite_index = beholdereyeofchaos;} {name = "beholdereyeofchaos"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 320 {{sprite_index = swablu;} {name = "swablu"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 321 {{sprite_index = vivillionmeadow;} {name = "vivillionmeadow"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 322 {{sprite_index = missingno;} {name = "missingno"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 323 {{sprite_index = unowna;} {name = "unowna"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 324 {{sprite_index = unownb;} {name = "unownb"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 325 {{sprite_index = unownc;} {name = "unownc"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 326 {{sprite_index = unownd;} {name = "unownd"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 327 {{sprite_index = unowne;} {name = "unowne"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 328 {{sprite_index = unownf;} {name = "unownf"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 329 {{sprite_index = unowng;} {name = "unowng"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 330 {{sprite_index = unownh;} {name = "unownh"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 331 {{sprite_index = unowni;} {name = "unowni"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 332 {{sprite_index = unownj;} {name = "unownj"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 333 {{sprite_index = unownk;} {name = "unownk"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 334 {{sprite_index = unownl;} {name = "unownl"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 335 {{sprite_index = unownm;} {name = "unownm"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 336 {{sprite_index = unownn;} {name = "unownn"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 337 {{sprite_index = unowno;} {name = "unowno"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 338 {{sprite_index = unownp;} {name = "unownp"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 339 {{sprite_index = unownq;} {name = "unownq"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 340 {{sprite_index = unownr;} {name = "unownr"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 341 {{sprite_index = unowns;} {name = "unowns"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 342 {{sprite_index = unownt;} {name = "unownt"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 343 {{sprite_index = unownu;} {name = "unownu"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 344 {{sprite_index = unownv;} {name = "unownv"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 345 {{sprite_index = unownw;} {name = "unownw"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 346 {{sprite_index = unownx;} {name = "unownx"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 347 {{sprite_index = unowny;} {name = "unowny"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 348 {{sprite_index = unownz;} {name = "unownz"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 349 {{sprite_index = unownexclamation;} {name = "unownexclamation"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 350 {{sprite_index = unownquestion;} {name = "unownquestion"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 351 {{sprite_index = avion;} {name = "avion"} {global.attack = "charge"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 352 {{sprite_index = gwyn;} {name = "gwyn"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 353 {{sprite_index = manus;} {name = "manus"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 354 {{sprite_index = quelaag;} {name = "quelaag"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 355 {{sprite_index = shadowlurkerf;} {name = "shadowlurkerf"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 356 {{sprite_index = agumon;} {name = "agumon"} {global.attack = "fire"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 357 {{sprite_index = kingallant;} {name = "kingallant"} {global.attack = "charge"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 358 {{sprite_index = blissey;} {name = "blissey"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 359 {{sprite_index = oldmonk;} {name = "oldmonk"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 360 {{sprite_index = gengar;} {name = "gengar"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 361 {{sprite_index = stormking;} {name = "stormking"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 362 {{sprite_index = leechmoger;} {name = "leechmoger"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 363 {{sprite_index = maideninblack;} {name = "maideninblack"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 364 {{sprite_index = xatu;} {name = "xatu"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 365 {{sprite_index = boneclaw;} {name = "boneclaw"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 366 {{sprite_index = troutmaskreplica;} {name = "troutmaskreplica"} {global.attack = "charge"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 367 {{sprite_index = satori;} {name = "satori"} {global.attack = "copycat"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 368 {{sprite_index = demoman;} {name = "demoman"} {global.attack = "grenade"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 369 {{sprite_index = pyro;} {name = "pyro"} {global.attack = "fire"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 370 {{sprite_index = spy;} {name = "spy"} {global.attack = "copycat"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 371 {{sprite_index = medic;} {name = "medic"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "grey"}} 
if numb = 372 {{sprite_index = skout;} {name = "skout"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 373 {{sprite_index = soldier;} {name = "soldier"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 374 {{sprite_index = heavy;} {name = "heavy"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 375 {{sprite_index = isaacclarke;} {name = "isaacclarke"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 376 {{sprite_index = limbokid;} {name = "limbokid"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 377 {{sprite_index = magnezone;} {name = "magnezone"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 378 {{sprite_index = cj;} {name = "cj"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 379 {{sprite_index = sven;} {name = "sven"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "grey"}} 
if numb = 380 {{sprite_index = vivec;} {name = "vivec"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 381 {{sprite_index = dagothur;} {name = "dagothur"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "grey"}} 
if numb = 382 {{sprite_index = biker;} {name = "biker"} {global.attack = "boomerang"} {global.stamp = ""}  { global.color = "grey"}} 
if numb = 383 {{sprite_index = jacket;} {name = "jacket"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "grey"}} 
if numb = 384 {{sprite_index = slugma;} {name = "slugma"} {global.attack = "fire"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 385 {{sprite_index = haunter;} {name = "haunter"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 386 {{sprite_index = weepinbell;} {name = "weepinbell"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 387 {{sprite_index = maxwell;} {name = "maxwell"} {global.attack = "random"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 388 {{sprite_index = aboleth;} {name = "aboleth"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 389 {{sprite_index = astralstalker;} {name = "astralstalker"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "light green"}} 
if numb = 390 {{sprite_index = runeknight;} {name = "runeknight"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 391 {{sprite_index = eagleman;} {name = "eagleman"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 392 {{sprite_index = bigdaddy;} {name = "bigdaddy"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 393 {{sprite_index = garbodor;} {name = "garbodor"} {global.attack = "mines"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 394 {{sprite_index = johnnybravo;} {name = "johnnybravo"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 395 {{sprite_index = reimu;} {name = "reimu"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 396 {{sprite_index = clefairy;} {name = "clefairy"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 397 {{sprite_index = mima;} {name = "mima"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 398 {{sprite_index = arcanine;} {name = "arcanine"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 399 {{sprite_index = zatchbell;} {name = "zatchbell"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 400 {{sprite_index = sanicthingkenoffast;} {name = "sanicthingkenoffast"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 401 {{sprite_index = plaguedoctor;} {name = "plaguedoctor"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 402 {{sprite_index = tia;} {name = "tia"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 403 {{sprite_index = kanchome;} {name = "kanchome"} {global.attack = "copycat"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 404 {{sprite_index = mayorofcantown;} {name = "mayorofcantown"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 405 {{sprite_index = umagon;} {name = "umagon"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 406 {{sprite_index = honeydew;} {name = "honeydew"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 407 {{sprite_index = mrkrabs;} {name = "mrkrabs"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 408 {{sprite_index = sissel;} {name = "sissel"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 409 {{sprite_index = orangestarinfintry;} {name = "orangestarinfintry"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 410 {{sprite_index = fawful;} {name = "fawful"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "light green"}} 
if numb = 411 {{sprite_index = constanza;} {name = "constanza"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 412 {{sprite_index = brago;} {name = "brago"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 413 {{sprite_index = blu;} {name = "blu"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 414 {{sprite_index = jingitaxias;} {name = "jingitaxias"} {global.attack = "copycat"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 415 {{sprite_index = roadrunner;} {name = "roadrunner"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 416 {{sprite_index = dragonite;} {name = "dragonite"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 417 {{sprite_index = umagonshudoruk;} {name = "umagonshudoruk"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 418 {{sprite_index = umagongoshudoruk;} {name = "umagongoshudoruk"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 419 {{sprite_index = umagondioemuru;} {name = "umagondioemuru"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 420 {{sprite_index = roggenrola;} {name = "roggenrola"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 421 {{sprite_index = zeon;} {name = "zeon"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 422 {{sprite_index = solosis;} {name = "solosis"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 423 {{sprite_index = duosion;} {name = "duosion"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 424 {{sprite_index = spoink;} {name = "spoink"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 425 {{sprite_index = billcipher;} {name = "billcipher"} {global.attack = "random"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 426 {{sprite_index = skipper;} {name = "skipper"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 427 {{sprite_index = private;} {name = "private"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 428 {{sprite_index = rico;} {name = "rico"} {global.attack = "explosion"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 429 {{sprite_index = kowalski;} {name = "kowalski"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 430 {{sprite_index = hans;} {name = "hans"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 431 {{sprite_index = drsloth;} {name = "drsloth"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 432 {{sprite_index = owl;} {name = "owl"} {global.attack = "beam"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 433 {{sprite_index = masterchief;} {name = "masterchief"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 434 {{sprite_index = crobat;} {name = "crobat"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 435 {{sprite_index = zubat;} {name = "zubat"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 436 {{sprite_index = jcdenton;} {name = "jcdenton"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 437 {{sprite_index = bomberman;} {name = "bomberman"} {global.attack = "grenade"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 438 {{sprite_index = coolspot;} {name = "coolspot"} {global.attack = "spark"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 439 {{sprite_index = panty;} {name = "panty"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 440 {{sprite_index = stocking;} {name = "stocking"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 441 {{sprite_index = frankerz;} {name = "frankerz"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 442 {{sprite_index = rance;} {name = "rance"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 443 {{sprite_index = chie;} {name = "chie"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 444 {{sprite_index = cormano;} {name = "cormano"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 445 {{sprite_index = shake;} {name = "shake"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 446 {{sprite_index = sweetbro;} {name = "sweetbro"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 447 {{sprite_index = midna;} {name = "midna"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 448 {{sprite_index = hellajeff;} {name = "hellajeff"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 449 {{sprite_index = meatwad;} {name = "meatwad"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 450 {{sprite_index = raiden;} {name = "raiden"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 451 {{sprite_index = emi;} {name = "emi"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 452 {{sprite_index = gerome;} {name = "gerome"} {global.attack = "explosion"} {global.stamp = ""}  { global.color = "rainbow"}} 
if numb = 453 {{sprite_index = gordonfreeman;} {name = "gordonfreeman"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 454 {{sprite_index = pacman;} {name = "pacman"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 455 {{sprite_index = beckett;} {name = "beckett"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 456 {{sprite_index = blackrose;} {name = "blackrose"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 457 {{sprite_index = met;} {name = "met"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 458 {{sprite_index = spaceinvader;} {name = "spaceinvader"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 459 {{sprite_index = litwick;} {name = "litwick"} {global.attack = "fire"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 460 {{sprite_index = solaire;} {name = "solaire"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 461 {{sprite_index = zekedunbar;} {name = "zekedunbar"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 462 {{sprite_index = malkavian;} {name = "malkavian"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 463 {{sprite_index = peashooter;} {name = "peashooter"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 464 {{sprite_index = pumkin;} {name = "pumkin"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 465 {{sprite_index = phoenixwright;} {name = "phoenixwright"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 466 {{sprite_index = scoobywerkstat;} {name = "scoobywerkstat"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 467 {{sprite_index = armordarmadillo;} {name = "armordarmadillo"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 468 {{sprite_index = megamanx;} {name = "megamanx"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 469 {{sprite_index = jetstreamsam;} {name = "jetstreamsam"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 470 {{sprite_index = gene;} {name = "gene"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "pink"}} 
if numb = 471 {{sprite_index = jotarokujo;} {name = "jotarokujo"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 472 {{sprite_index = megamanexe;} {name = "megamanexe"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "orange"}} 
if numb = 473 {{sprite_index = leila;} {name = "leila"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 474 {{sprite_index = danmandel;} {name = "danmandel"} {global.attack = "punch"} {global.stamp = ""}  { global.color = ""}} 
if numb = 475 {{sprite_index = elisepearson;} {name = "elisepearson"} {global.attack = "punch"} {global.stamp = ""}  { global.color = ""}} 
if numb = 476 {{sprite_index = chrispearson;} {name = "chrispearson"} {global.attack = "punch"} {global.stamp = ""}  { global.color = ""}} 
if numb = 477 {{sprite_index = sif;} {name = "sif"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "silver"}} 
if numb = 478 {{sprite_index = strayhumanity;} {name = "strayhumanity"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 479 {{sprite_index = crestfallenwarrior;} {name = "crestfallenwarrior"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 480 {{sprite_index = caprademon;} {name = "caprademon"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 481 {{sprite_index = gwyndolin;} {name = "gwyndolin"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 482 {{sprite_index = nier;} {name = "nier"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 483 {{sprite_index = weiss;} {name = "weiss"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "red"}} 
if numb = 484 {{sprite_index = ryu;} {name = "ryu"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "light blue"}} 
if numb = 485 {{sprite_index = zangief;} {name = "zangief"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = ""}} 
if numb = 486 {{sprite_index = monokuma;} {name = "monokuma"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 487 {{sprite_index = shade;} {name = "shade"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 488 {{sprite_index = chacha;} {name = "chacha"} {global.attack = "stick"} {global.stamp = ""}  { global.color = "light green"}} 
if numb = 489 {{sprite_index = lucas;} {name = "lucas"} {global.attack = "stick"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 490 {{sprite_index = kenmasters;} {name = "kenmasters"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 491 {{sprite_index = aigis;} {name = "aigis"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 492 {{sprite_index = sniper;} {name = "sniper"} {global.attack = "bullet"} {global.stamp = ""}  { global.color = "black"}} 
if numb = 493 {{sprite_index = rikafurude;} {name = "rikafurude"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "purple"}} 
if numb = 494 {{sprite_index = chernoalpha;} {name = "chernoalpha"} {global.attack = "punch"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 495 {{sprite_index = strikereureka;} {name = "strikereureka"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 496 {{sprite_index = burmyplant;} {name = "burmyplant"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 497 {{sprite_index = wormadamplant;} {name = "wormadamplant"} {global.attack = "whip"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 498 {{sprite_index = wormadamtrash;} {name = "wormadamtrash"} {global.attack = "powder"} {global.stamp = ""}  { global.color = "gray"}} 
if numb = 499 {{sprite_index = wormadamsand;} {name = "wormadamsand"} {global.attack = "mines"} {global.stamp = ""}  { global.color = "brown"}} 
if numb = 500 {{sprite_index = yotsuba;} {name = "yotsuba"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "green"}} 
if numb = 501 {{sprite_index = cubone;} {name = "cubone"} {global.attack = "stick"} {global.stamp = ""}  { global.color = "white"}} 
if numb = 502 {{sprite_index = meowth;} {name = "meowth"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 503 {{sprite_index = beat;} {name = "beat"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "blue"}} 
if numb = 504 {{sprite_index = isabelle;} {name = "isabelle"} {global.attack = "tackle"} {global.stamp = ""}  { global.color = "yellow"}} 
if numb = 505 {{sprite_index = balrog;} {name = "balrog"} {global.attack = ""} {global.stamp = ""}  { global.color = ""}} 
if numb = 506 {{sprite_index = takamaru;} {name = "takamaru"} {global.attack = "sword"} {global.stamp = ""}  { global.color = "white"}} 


