global.ability = "shoot"

numb = floor(random(180));

if numb = 0 {{sprite_index = thegreentie;} {name = "thegreentie"}} 
if numb = 1 {{sprite_index = businessbanana;} {name = "businessbanana"}} 
if numb = 2 {{sprite_index = dennot;} {name = "dennot"}} 
if numb = 3 {{sprite_index = mario;} {name = "mario"}} 
if numb = 4 {{sprite_index = luigi;} {name = "luigi"}} 
if numb = 5 {{sprite_index = bowser;} {name = "bowser"}} 
if numb = 6 {{sprite_index = peach;} {name = "peach"}} 
if numb = 7 {{sprite_index = drmario;} {name = "drmario"}} 
if numb = 8 {{sprite_index = yoshi;} {name = "yoshi"}} 
if numb = 9 {{sprite_index = pit;} {name = "pit"}} 
if numb = 10 {{sprite_index = captainfalcon;} {name = "captainfalcon"}} 
if numb = 11 {{sprite_index = mrgameandwatch;} {name = "mrgameandwatch"}} 
if numb = 12 {{sprite_index = rob;} {name = "rob"}} 
if numb = 13 {{sprite_index = pikachu;} {name = "pikachu"}} 
if numb = 14 {{sprite_index = bulbasaur;} {name = "bulbasaur"}} 
if numb = 15 {{sprite_index = ivysaur;} {name = "ivysaur"}} 
if numb = 16 {{sprite_index = venusaur;} {name = "venusaur"}} 
if numb = 17 {{sprite_index = charmander;} {name = "charmander"}} 
if numb = 18 {{sprite_index = charmeleon;} {name = "charmeleon"}} 
if numb = 19 {{sprite_index = charizard;} {name = "charizard"}} 
if numb = 20 {{sprite_index = link;} {name = "link"}} 
if numb = 21 {{sprite_index = zelda;} {name = "zelda"}} 
if numb = 22 {{sprite_index = sheik;} {name = "sheik"}} 
if numb = 23 {{sprite_index = ganondorf;} {name = "ganondorf"}} 
if numb = 24 {{sprite_index = sonic;} {name = "sonic"}} 
if numb = 25 {{sprite_index = wario;} {name = "wario"}} 
if numb = 26 {{sprite_index = pikminred;} {name = "pikminred"}} 
if numb = 27 {{sprite_index = pikminyellow;} {name = "pikminyellow"}} 
if numb = 28 {{sprite_index = pikminblue;} {name = "pikminblue"}} 
if numb = 29 {{sprite_index = pikminwhite;} {name = "pikminwhite"}} 
if numb = 30 {{sprite_index = pikminpurple;} {name = "pikminpurple"}} 
if numb = 31 {{sprite_index = engineer;} {name = "engineer"}} 
if numb = 32 {{sprite_index = steve;} {name = "steve"}} 
if numb = 33 {{sprite_index = magickared;} {name = "magickared"}} 
if numb = 34 {{sprite_index = magickablue;} {name = "magickablue"}} 
if numb = 35 {{sprite_index = magickayellow;} {name = "magickayellow"}} 
if numb = 36 {{sprite_index = magickagreen;} {name = "magickagreen"}} 
if numb = 37 {{sprite_index = santaclaus;} {name = "santaclaus"}} 
if numb = 38 {{sprite_index = blossom;} {name = "blossom"}} 
if numb = 39 {{sprite_index = bubbles;} {name = "bubbles"}} 
if numb = 40 {{sprite_index = buttercup;} {name = "buttercup"}} 
if numb = 41 {{sprite_index = eddy;} {name = "eddy"}} 
if numb = 42 {{sprite_index = edd;} {name = "edd"}} 
if numb = 43 {{sprite_index = ed;} {name = "ed"}} 
if numb = 44 {{sprite_index = courage;} {name = "courage"}} 
if numb = 45 {{sprite_index = gir;} {name = "gir"}} 
if numb = 46 {{sprite_index = spongebob;} {name = "spongebob"}} 
if numb = 47 {{sprite_index = captainknuckles;} {name = "captainknuckles"}} 
if numb = 48 {{sprite_index = flapjack;} {name = "flapjack"}} 
if numb = 49 {{sprite_index = chowder;} {name = "chowder"}} 
if numb = 50 {{sprite_index = shnitzel;} {name = "shnitzel"}} 
if numb = 51 {{sprite_index = waluigi;} {name = "waluigi"}} 
if numb = 52 {{sprite_index = galvantula;} {name = "galvantula"}} 
if numb = 53 {{sprite_index = electivire;} {name = "electivire"}} 
if numb = 54 {{sprite_index = reuniclus;} {name = "reuniclus"}} 
if numb = 55 {{sprite_index = pikminrock;} {name = "pikminrock"}} 
if numb = 56 {{sprite_index = pikminwinged;} {name = "pikminwinged"}} 
if numb = 57 {{sprite_index = spinda;} {name = "spinda"}} 
if numb = 58 {{sprite_index = mrdickens;} {name = "mrdickens"}} 
if numb = 59 {{sprite_index = castform;} {name = "castform"}} 
if numb = 60 {{sprite_index = castformsunny;} {name = "castformsunny"}} 
if numb = 61 {{sprite_index = castformrainy;} {name = "castformrainy"}} 
if numb = 62 {{sprite_index = castformsnowy;} {name = "castformsnowy"}} 
if numb = 63 {{sprite_index = beheeyem;} {name = "beheeyem"}} 
if numb = 64 {{sprite_index = celebi;} {name = "celebi"}} 
if numb = 65 {{sprite_index = deoxys;} {name = "deoxys"}} 
if numb = 66 {{sprite_index = deoxysattack;} {name = "deoxysattack"}} 
if numb = 67 {{sprite_index = deoxysdefense;} {name = "deoxysdefense"}} 
if numb = 68 {{sprite_index = deoxysspeed;} {name = "deoxysspeed"}} 
if numb = 69 {{sprite_index = diglet;} {name = "diglet"}} 
if numb = 70 {{sprite_index = ditto;} {name = "ditto"}} 
if numb = 71 {{sprite_index = drifloon;} {name = "drifloon"}} 
if numb = 72 {{sprite_index = electrode;} {name = "electrode"}} 
if numb = 73 {{sprite_index = escavalier;} {name = "escavalier"}} 
if numb = 74 {{sprite_index = froslass;} {name = "froslass"}} 
if numb = 75 {{sprite_index = genescect;} {name = "genescect"}} 
if numb = 76 {{sprite_index = geodude;} {name = "geodude"}} 
if numb = 77 {{sprite_index = gastly;} {name = "gastly"}} 
if numb = 78 {{sprite_index = giratinaorigin;} {name = "giratinaorigin"}} 
if numb = 79 {{sprite_index = golurk;} {name = "golurk"}} 
if numb = 80 {{sprite_index = hydreigon;} {name = "hydreigon"}} 
if numb = 81 {{sprite_index = kyurem;} {name = "kyurem"}} 
if numb = 82 {{sprite_index = lunatone;} {name = "lunatone"}} 
if numb = 83 {{sprite_index = solrock;} {name = "solrock"}} 
if numb = 84 {{sprite_index = magnemite;} {name = "magnemite"}} 
if numb = 85 {{sprite_index = metagross;} {name = "metagross"}} 
if numb = 86 {{sprite_index = ninjask;} {name = "ninjask"}} 
if numb = 87 {{sprite_index = poliwag;} {name = "poliwag"}} 
if numb = 88 {{sprite_index = psyduck;} {name = "psyduck"}} 
if numb = 89 {{sprite_index = regigigas;} {name = "regigigas"}} 
if numb = 90 {{sprite_index = rotom;} {name = "rotom"}} 
if numb = 91 {{sprite_index = rotomfan;} {name = "rotomfan"}} 
if numb = 92 {{sprite_index = rotomfrost;} {name = "rotomfrost"}} 
if numb = 93 {{sprite_index = rotomheat;} {name = "rotomheat"}} 
if numb = 94 {{sprite_index = rotomwash;} {name = "rotomwash"}} 
if numb = 95 {{sprite_index = rotommow;} {name = "rotommow"}} 
if numb = 96 {{sprite_index = sawk;} {name = "sawk"}} 
if numb = 97 {{sprite_index = scolipede;} {name = "scolipede"}} 
if numb = 98 {{sprite_index = shedinja;} {name = "shedinja"}} 
if numb = 99 {{sprite_index = simisage;} {name = "simisage"}} 
if numb = 100 {{sprite_index = sigilyph;} {name = "sigilyph"}} 
if numb = 101 {{sprite_index = tentacruel;} {name = "tentacruel"}} 
if numb = 102 {{sprite_index = angrybirdred;} {name = "angrybirdred"}} 
if numb = 103 {{sprite_index = angrybirdwhite;} {name = "angrybirdwhite"}} 
if numb = 104 {{sprite_index = angrybirdyellow;} {name = "angrybirdyellow"}} 
if numb = 105 {{sprite_index = frosty;} {name = "frosty"}} 
if numb = 106 {{sprite_index = professorlayton;} {name = "professorlayton"}} 
if numb = 107 {{sprite_index = navi;} {name = "navi"}} 
if numb = 108 {{sprite_index = nyancat;} {name = "nyancat"}} 
if numb = 109 {{sprite_index = squirtle;} {name = "squirtle"}} 
if numb = 110 {{sprite_index = volcarona;} {name = "volcarona"}} 
if numb = 111 {{sprite_index = voltorb;} {name = "voltorb"}} 
if numb = 112 {{sprite_index = wobbuffet;} {name = "wobbuffet"}} 
if numb = 113 {{sprite_index = tentacool;} {name = "tentacool"}} 
if numb = 114 {{sprite_index = shuckle;} {name = "shuckle"}} 
if numb = 115 {{sprite_index = sneakypebbles;} {name = "sneakypebbles"}} 
if numb = 116 {{sprite_index = natu;} {name = "natu"}} 
if numb = 117 {{sprite_index = trapinch;} {name = "trapinch"}} 
if numb = 118 {{sprite_index = cofagrigus;} {name = "cofagrigus"}} 
if numb = 119 {{sprite_index = mienshao;} {name = "mienshao"}} 
if numb = 120 {{sprite_index = baitfish;} {name = "baitfish"}} 
if numb = 121 {{sprite_index = mudkip;} {name = "mudkip"}} 
if numb = 122 {{sprite_index = zangoose;} {name = "zangoose"}} 
if numb = 123 {{sprite_index = audino;} {name = "audino"}} 
if numb = 124 {{sprite_index = vibrava;} {name = "vibrava"}} 
if numb = 125 {{sprite_index = insidetheflyingmachine;} {name = "insidetheflyingmachine"}} 
if numb = 126 {{sprite_index = azelf;} {name = "azelf"}} 
if numb = 127 {{sprite_index = cancer;} {name = "cancer"}} 
if numb = 128 {{sprite_index = cryogonal;} {name = "crygonal"}} 
if numb = 129 {{sprite_index = flygon;} {name = "flygon"}} 
if numb = 130 {{sprite_index = pinkiepie;} {name = "pinkiepie"}} 
if numb = 131 {{sprite_index = uxie;} {name = "uxie"}} 
if numb = 132 {{sprite_index = throh;} {name = "throh"}} 
if numb = 133 {{sprite_index = swanna;} {name = "swanna"}} 
if numb = 134 {{sprite_index = geno;} {name = "geno"}} 
if numb = 135 {{sprite_index = mesprit;} {name = "mersprit"}} 
if numb = 136 {{sprite_index = marshtomp;} {name = "marshtomp"}} 
if numb = 137 {{sprite_index = pokemonegg;} {name = "pokemonegg"}} 
if numb = 138 {{sprite_index = pyramidhead;} {name = "pyramidhead"}} 
if numb = 139 {{sprite_index = absol;} {name = "absol"}} 
if numb = 140 {{sprite_index = sanic;} {name = "sanic"}} 
if numb = 141 {{sprite_index = saniclil;} {name = "saniclil"}} 
if numb = 142 {{sprite_index = poisonmushroom;} {name = "poisonmushroom"}} 
if numb = 143 {{sprite_index = druddigon;} {name = "druddigon"}} 
if numb = 144 {{sprite_index = gardevoir;} {name = "gardevoir"}} 
if numb = 145 {{sprite_index = twilightsparkle;} {name = "twilightsparkle"}} 
if numb = 146 {{sprite_index = doge;} {name = "doge"}} 
if numb = 147 {{sprite_index = nito;} {name = "nito"}} 
if numb = 148 {{sprite_index = seaththescaleless;} {name = "seaththescaleless"}} 
if numb = 149 {{sprite_index = uboa;} {name = "uboa"}} 
if numb = 150 {{sprite_index = penetrator;} {name = "penetrator"}} 
if numb = 151 {{sprite_index = towerknight;} {name = "towerknight"}} 
if numb = 152 {{sprite_index = rainbowdash;} {name = "rainbowdash"}} 
if numb = 153 {{sprite_index = zerotwo;} {name = "zerotwo"}} 
if numb = 154 {{sprite_index = adjudicator;} {name = "adjudicator"}} 
if numb = 155 {{sprite_index = smough;} {name = "smough"}} 
if numb = 156 {{sprite_index = ornstein;} {name = "ornstein"}} 
if numb = 157 {{sprite_index = madotsuki;} {name = "madotsuki"}} 
if numb = 158 {{sprite_index = kirby;} {name = "kirby"}} 
if numb = 159 {{sprite_index = luvdisc;} {name = "luvdisc"}} 
if numb = 160 {{sprite_index = honedge;} {name = "honedge"}} 
if numb = 161 {{sprite_index = oorotto;} {name = "oorotto"}} 
if numb = 162 {{sprite_index = xerneas;} {name = "xerneas"}} 
if numb = 163 {{sprite_index = slenderman;} {name = "slenderman"}} 
if numb = 164 {{sprite_index = chikorita;} {name = "chikorita"}} 
if numb = 165 {{sprite_index = honchkrow;} {name = "honchkrow"}} 
if numb = 166 {{sprite_index = applejack;} {name = "applejack"}} 
if numb = 167 {{sprite_index = muricaneagle;} {name = "muricaneagle"}} 
if numb = 168 {{sprite_index = duckhunt;} {name = "duckhunt"}} 
if numb = 169 {{sprite_index = duckhunt2;} {name = "duckhunt2"}} 
if numb = 170 {{sprite_index = duckhunt3;} {name = "duckhunt3"}} 
if numb = 171 {{sprite_index = wacky;} {name = "wacky"}} 
if numb = 172 {{sprite_index = rarity;} {name = "rarity"}} 
if numb = 173 {{sprite_index = wooper;} {name = "wooper"}} 
if numb = 174 {{sprite_index = hypno;} {name = "hypno"}} 
if numb = 175 {{sprite_index = talonflame;} {name = "talonflame"}} 
if numb = 176 {{sprite_index = isaac;} {name = "isaac"}} 
if numb = 177 {{sprite_index = crustle;} {name = "crustle"}} 
if numb = 178 {{sprite_index = gigalith;} {name = "gigalith"}} 
if numb = 179 {{sprite_index = meatboy;} {name = "meatboy"}} 
if numb = 180 {{sprite_index = fluttershy;} {name = "fluttershy"}} 


