if global.color = ""
    image_blend = c_red
if global.color = "aqua"
    image_blend = c_aqua
if global.color = "black"
    image_blend = c_black
if global.color = "blue"
    image_blend = c_blue
if global.color = "darkgray"
    image_blend = c_dkgray
if global.color = "fuchsia"
    image_blend = c_fuchsia
if global.color = "gray"
    image_blend = c_gray
if global.color = "green"
    image_blend = c_green
if global.color = "lime"
    image_blend = c_lime
if global.color = "lightgray"
    image_blend = c_ltgray
if global.color = "maroon"
    image_blend = c_maroon
if global.color = "navy"
    image_blend = c_navy
if global.color = "olive"
    image_blend = c_olive
if global.color = "orange"
    image_blend = c_orange
if global.color = "purple"
    image_blend = c_purple
if global.color = "red"
    image_blend = c_red
if global.color = "silver"
    image_blend = c_silver
if global.color = "teal"
    image_blend = c_teal
if global.color = "white"
    image_blend = c_white
if global.color = "yellow"
    image_blend = c_yellow
