if global.stamp = ""
    sprite_index = spr_atk_orb
if global.stamp = "orb"
    sprite_index = spr_atk_orb
if global.stamp = "sword"
    sprite_index = spr_atk_sword
if global.stamp = "stick"
    sprite_index = spr_atk_stick
if global.stamp = "whip"
    sprite_index = spr_atk_whip
if global.stamp = "spark"
    sprite_index = spr_atk_spark
if global.stamp = "beam"
    sprite_index = spr_atk_beam
if global.stamp = "hammer"
    sprite_index = spr_atk_hammer
if global.stamp = "knife"
    sprite_index = spr_atk_knife
if global.stamp = "spike"
    sprite_index = spr_atk_spike
if global.stamp = "hand"
    sprite_index = spr_atk_hand
if global.stamp = "fist"
    sprite_index = spr_atk_fist
if global.stamp = "kick"
    sprite_index = spr_atk_kick
if global.stamp = "dust"
    sprite_index = spr_atk_dust
if global.stamp = "wave"
    sprite_index = spr_atk_wave
if global.stamp = "fire"
    sprite_index = spr_atk_fire
if global.stamp = "mine"
    sprite_index = spr_atk_mine
if global.stamp = "bomb"
    sprite_index = spr_atk_bomb
if global.stamp = "grenade"
    sprite_index = spr_atk_grenade
if global.stamp = "powder"
    sprite_index = spr_atk_powder
if global.stamp = "bite"
    sprite_index = spr_atk_bite
if global.stamp = "shuriken"
    sprite_index = spr_atk_shuriken
if global.stamp = "arrow"
    sprite_index = spr_atk_arrow
