global.ability = "shoot"

global.numb = floor(random(130));

if global.numb = 1
{sprite_index = galvantula;} 
if global.numb = 2
{sprite_index = electivire;} 
if global.numb = 3
{sprite_index = reuniclus;} 
if global.numb = 4
{sprite_index = pikminrock;} 
if global.numb = 5
{sprite_index = pikminwinged;} 
if global.numb = 6
{sprite_index = spinda;} 
if global.numb = 7
{sprite_index = mrdickens;} 
if global.numb = 8
{sprite_index = castform;} 
if global.numb = 9
{sprite_index = castformsunny;} 
if global.numb = 10
{sprite_index = castformrainy;} 
if global.numb = 11
{sprite_index = castformsnowy;} 
if global.numb = 12
{sprite_index = beheeyem;} 
if global.numb = 13
{sprite_index = celebi;} 
if global.numb = 14
{sprite_index = deoxys;} 
if global.numb = 15
{sprite_index = deoxysattack;} 
if global.numb = 16
{sprite_index = deoxysdefense;} 
if global.numb = 17
{sprite_index = deoxysspeed;} 
if global.numb = 18
{sprite_index = diglet;} 
if global.numb = 19
{sprite_index = ditto;} 
if global.numb = 20
{sprite_index = drifloon;} 
if global.numb = 21
{sprite_index = electrode;} 
if global.numb = 22
{sprite_index = escaliver;} 
if global.numb = 23
{sprite_index = froslass;} 
if global.numb = 24
{sprite_index = genescect;} 
if global.numb = 25
{sprite_index = geodude;} 
if global.numb = 26
{sprite_index = gastly;} 
if global.numb = 27
{sprite_index = giratinaorigin;} 
if global.numb = 28
{sprite_index = golurk;} 
if global.numb = 29
{sprite_index = hydreigon;} 
if global.numb = 30
{sprite_index = kyurem;} 
if global.numb = 31
{sprite_index = lunatone;} 
if global.numb = 32
{sprite_index = solrock;} 
if global.numb = 33
{sprite_index = magnemite;} 
if global.numb = 34
{sprite_index = metagross;} 
if global.numb = 35
{sprite_index = ninjask;} 
if global.numb = 36
{sprite_index = poliwag;} 
if global.numb = 37
{sprite_index = psyduck;} 
if global.numb = 38
{sprite_index = regigigas;} 
if global.numb = 39
{sprite_index = rotom;} 
if global.numb = 40
{sprite_index = rotomfan;} 
if global.numb = 41
{sprite_index = rotomfrost;} 
if global.numb = 42
{sprite_index = rotomheat;} 
if global.numb = 43
{sprite_index = rotomwash;} 
if global.numb = 44
{sprite_index = rotommow;} 
if global.numb = 45
{sprite_index = sawk;} 
if global.numb = 46
{sprite_index = scolipede;} 
if global.numb = 47
{sprite_index = shedinja;} 
if global.numb = 48
{sprite_index = simisage;} 
if global.numb = 49
{sprite_index = sigilyph;} 
if global.numb = 50
{sprite_index = tentacruel;} 
if global.numb = 51
{sprite_index = angrybirdred;} 
if global.numb = 52
{sprite_index = angrybirdwhite;} 
if global.numb = 53
{sprite_index = angrybirdyellow;} 
if global.numb = 54
{sprite_index = frosty;} 
if global.numb = 55
{sprite_index = professorlayton;} 
if global.numb = 56
{sprite_index = navi;} 
if global.numb = 57
{sprite_index = nyancat;} 
if global.numb = 58
{sprite_index = squirtle;} 
if global.numb = 59
{sprite_index = volcarona;} 
if global.numb = 60
{sprite_index = voltorb;} 
if global.numb = 61
{sprite_index = wobbuffet;} 
if global.numb = 62
{sprite_index = tentacool;} 
if global.numb = 63
{sprite_index = shuckle;} 
if global.numb = 64
{sprite_index = sneakypebbles;} 
if global.numb = 65
{sprite_index = natu;} 
if global.numb = 66
{sprite_index = trapinch;} 
if global.numb = 67
{sprite_index = cofagrigus;} 
if global.numb = 68
{sprite_index = mienshao;} 
if global.numb = 69
{sprite_index = baitfish;} 
if global.numb = 70
{sprite_index = mudkip;} 
if global.numb = 71
{sprite_index = zangoose;} 
if global.numb = 72
{sprite_index = audino;} 
if global.numb = 73
{sprite_index = vibrava;} 
if global.numb = 74
{sprite_index = insidetheflyingmachine;} 
if global.numb = 75
{sprite_index = azelf;} 
if global.numb = 76
{sprite_index = cancer;} 
if global.numb = 77
{sprite_index = crygonal;} 
if global.numb = 78
{sprite_index = flygon;} 
if global.numb = 79
{sprite_index = pinkiepie;} 
if global.numb = 80
{sprite_index = uxie;} 
if global.numb = 81
{sprite_index = throh;} 
if global.numb = 82
{sprite_index = swanna;} 
if global.numb = 83
{sprite_index = geno;} 
if global.numb = 84
{sprite_index = mersprit;} 
if global.numb = 85
{sprite_index = marshtomp;} 
if global.numb = 86
{sprite_index = pokemonegg;} 
if global.numb = 87
{sprite_index = pyramidhead;} 
if global.numb = 88
{sprite_index = absol;} 
if global.numb = 89
{sprite_index = sanic;} 
if global.numb = 90
{sprite_index = saniclil;} 
if global.numb = 91
{sprite_index = poisonmushroom;} 
if global.numb = 92
{sprite_index = druddigon;} 
if global.numb = 93
{sprite_index = gardevoir;} 
if global.numb = 94
{sprite_index = twilightsparkle;} 
if global.numb = 95
{sprite_index = doge;} 
if global.numb = 96
{sprite_index = nito;} 
if global.numb = 97
{sprite_index = seaththescaleless;} 
if global.numb = 98
{sprite_index = uboa;} 
if global.numb = 99
{sprite_index = penetrator;} 
if global.numb = 100
{sprite_index = towerknight;} 
if global.numb = 101
{sprite_index = rainbowdash;} 
if global.numb = 102
{sprite_index = zerotwo;} 
if global.numb = 103
{sprite_index = adjudicator;} 
if global.numb = 104
{sprite_index = smough;} 
if global.numb = 105
{sprite_index = ornstein;} 
if global.numb = 106
{sprite_index = madotsuki;} 
if global.numb = 107
{sprite_index = kirby;} 
if global.numb = 108
{sprite_index = luvdisc;} 
if global.numb = 109
{sprite_index = honedge;} 
if global.numb = 110
{sprite_index = oorotto;} 
if global.numb = 111
{sprite_index = xerneas;} 
if global.numb = 112
{sprite_index = slenderman;} 
if global.numb = 113
{sprite_index = chikorita;} 
if global.numb = 114
{sprite_index = honchkrow;} 
if global.numb = 115
{sprite_index = applejack;} 
if global.numb = 116
{sprite_index = muricaneagle;} 
if global.numb = 117
{sprite_index = duckhunt;} 
if global.numb = 118
{sprite_index = duckhunt2;} 
if global.numb = 119
{sprite_index = duckhunt3;} 
if global.numb = 120
{sprite_index = wacky;} 
if global.numb = 121
{sprite_index = rarity;} 
if global.numb = 122
{sprite_index = wooper;} 
if global.numb = 123
{sprite_index = hypno;} 
if global.numb = 124
{sprite_index = talonflame;} 
if global.numb = 125
{sprite_index = isaac;} 
if global.numb = 126
{sprite_index = crustle;} 
if global.numb = 127
{sprite_index = gigalith;} 
if global.numb = 128
{sprite_index = meatboy;} 
if global.numb = 129
{sprite_index = fluttershy;} 


