global.ability = "shoot"

numb = floor(random(180));

if numb = 0 {{sprite_index = thegreentie;} {name = "thegreentie"} {attack = ""} {global.color = ""}} 
if numb = 1 {{sprite_index = businessbanana;} {name = "businessbanana"} {attack = ""} {global.color = ""}} 
if numb = 2 {{sprite_index = dennot;} {name = "dennot"} {attack = ""} {global.color = ""}} 
if numb = 3 {{sprite_index = mario;} {name = "mario"} {attack = ""} {global.color = ""}} 
if numb = 4 {{sprite_index = luigi;} {name = "luigi"} {attack = ""} {global.color = ""}} 
if numb = 5 {{sprite_index = bowser;} {name = "bowser"} {attack = ""} {global.color = ""}} 
if numb = 6 {{sprite_index = peach;} {name = "peach"} {attack = ""} {global.color = ""}} 
if numb = 7 {{sprite_index = drmario;} {name = "drmario"} {attack = ""} {global.color = ""}} 
if numb = 8 {{sprite_index = yoshi;} {name = "yoshi"} {attack = ""} {global.color = ""}} 
if numb = 9 {{sprite_index = pit;} {name = "pit"} {attack = ""} {global.color = ""}} 
if numb = 10 {{sprite_index = captainfalcon;} {name = "captainfalcon"} {attack = ""} {global.color = ""}} 
if numb = 11 {{sprite_index = mrgameandwatch;} {name = "mrgameandwatch"} {attack = ""} {global.color = ""}} 
if numb = 12 {{sprite_index = rob;} {name = "rob"} {attack = ""} {global.color = ""}} 
if numb = 13 {{sprite_index = pikachu;} {name = "pikachu"} {attack = ""} {global.color = ""}} 
if numb = 14 {{sprite_index = bulbasaur;} {name = "bulbasaur"} {attack = ""} {global.color = ""}} 
if numb = 15 {{sprite_index = ivysaur;} {name = "ivysaur"} {attack = ""} {global.color = ""}} 
if numb = 16 {{sprite_index = venusaur;} {name = "venusaur"} {attack = ""} {global.color = ""}} 
if numb = 17 {{sprite_index = charmander;} {name = "charmander"} {attack = ""} {global.color = ""}} 
if numb = 18 {{sprite_index = charmeleon;} {name = "charmeleon"} {attack = ""} {global.color = ""}} 
if numb = 19 {{sprite_index = charizard;} {name = "charizard"} {attack = ""} {global.color = ""}} 
if numb = 20 {{sprite_index = link;} {name = "link"} {attack = ""} {global.color = ""}} 
if numb = 21 {{sprite_index = zelda;} {name = "zelda"} {attack = ""} {global.color = ""}} 
if numb = 22 {{sprite_index = sheik;} {name = "sheik"} {attack = ""} {global.color = ""}} 
if numb = 23 {{sprite_index = ganondorf;} {name = "ganondorf"} {attack = ""} {global.color = ""}} 
if numb = 24 {{sprite_index = sonic;} {name = "sonic"} {attack = ""} {global.color = ""}} 
if numb = 25 {{sprite_index = wario;} {name = "wario"} {attack = ""} {global.color = ""}} 
if numb = 26 {{sprite_index = pikminred;} {name = "pikminred"} {attack = ""} {global.color = ""}} 
if numb = 27 {{sprite_index = pikminyellow;} {name = "pikminyellow"} {attack = ""} {global.color = ""}} 
if numb = 28 {{sprite_index = pikminblue;} {name = "pikminblue"} {attack = ""} {global.color = ""}} 
if numb = 29 {{sprite_index = pikminwhite;} {name = "pikminwhite"} {attack = ""} {global.color = ""}} 
if numb = 30 {{sprite_index = pikminpurple;} {name = "pikminpurple"} {attack = ""} {global.color = ""}} 
if numb = 31 {{sprite_index = engineer;} {name = "engineer"} {attack = ""} {global.color = ""}} 
if numb = 32 {{sprite_index = steve;} {name = "steve"} {attack = ""} {global.color = ""}} 
if numb = 33 {{sprite_index = magickared;} {name = "magickared"} {attack = ""} {global.color = ""}} 
if numb = 34 {{sprite_index = magickablue;} {name = "magickablue"} {attack = ""} {global.color = ""}} 
if numb = 35 {{sprite_index = magickayellow;} {name = "magickayellow"} {attack = ""} {global.color = ""}} 
if numb = 36 {{sprite_index = magickagreen;} {name = "magickagreen"} {attack = ""} {global.color = ""}} 
if numb = 37 {{sprite_index = santaclaus;} {name = "santaclaus"} {attack = ""} {global.color = ""}} 
if numb = 38 {{sprite_index = blossom;} {name = "blossom"} {attack = ""} {global.color = ""}} 
if numb = 39 {{sprite_index = bubbles;} {name = "bubbles"} {attack = ""} {global.color = ""}} 
if numb = 40 {{sprite_index = buttercup;} {name = "buttercup"} {attack = ""} {global.color = ""}} 
if numb = 41 {{sprite_index = eddy;} {name = "eddy"} {attack = ""} {global.color = ""}} 
if numb = 42 {{sprite_index = edd;} {name = "edd"} {attack = ""} {global.color = ""}} 
if numb = 43 {{sprite_index = ed;} {name = "ed"} {attack = ""} {global.color = ""}} 
if numb = 44 {{sprite_index = courage;} {name = "courage"} {attack = ""} {global.color = ""}} 
if numb = 45 {{sprite_index = gir;} {name = "gir"} {attack = ""} {global.color = ""}} 
if numb = 46 {{sprite_index = spongebob;} {name = "spongebob"} {attack = ""} {global.color = ""}} 
if numb = 47 {{sprite_index = captainknuckles;} {name = "captainknuckles"} {attack = ""} {global.color = ""}} 
if numb = 48 {{sprite_index = flapjack;} {name = "flapjack"} {attack = ""} {global.color = ""}} 
if numb = 49 {{sprite_index = chowder;} {name = "chowder"} {attack = ""} {global.color = ""}} 
if numb = 50 {{sprite_index = shnitzel;} {name = "shnitzel"} {attack = ""} {global.color = ""}} 
if numb = 51 {{sprite_index = waluigi;} {name = "waluigi"} {attack = ""} {global.color = ""}} 
if numb = 52 {{sprite_index = galvantula;} {name = "galvantula"} {attack = ""} {global.color = ""}} 
if numb = 53 {{sprite_index = electivire;} {name = "electivire"} {attack = ""} {global.color = ""}} 
if numb = 54 {{sprite_index = reuniclus;} {name = "reuniclus"} {attack = ""} {global.color = ""}} 
if numb = 55 {{sprite_index = pikminrock;} {name = "pikminrock"} {attack = ""} {global.color = ""}} 
if numb = 56 {{sprite_index = pikminwinged;} {name = "pikminwinged"} {attack = ""} {global.color = ""}} 
if numb = 57 {{sprite_index = spinda;} {name = "spinda"} {attack = ""} {global.color = ""}} 
if numb = 58 {{sprite_index = mrdickens;} {name = "mrdickens"} {attack = ""} {global.color = ""}} 
if numb = 59 {{sprite_index = castform;} {name = "castform"} {attack = ""} {global.color = ""}} 
if numb = 60 {{sprite_index = castformsunny;} {name = "castformsunny"} {attack = ""} {global.color = ""}} 
if numb = 61 {{sprite_index = castformrainy;} {name = "castformrainy"} {attack = ""} {global.color = ""}} 
if numb = 62 {{sprite_index = castformsnowy;} {name = "castformsnowy"} {attack = ""} {global.color = ""}} 
if numb = 63 {{sprite_index = beheeyem;} {name = "beheeyem"} {attack = ""} {global.color = ""}} 
if numb = 64 {{sprite_index = celebi;} {name = "celebi"} {attack = ""} {global.color = ""}} 
if numb = 65 {{sprite_index = deoxys;} {name = "deoxys"} {attack = ""} {global.color = ""}} 
if numb = 66 {{sprite_index = deoxysattack;} {name = "deoxysattack"} {attack = ""} {global.color = ""}} 
if numb = 67 {{sprite_index = deoxysdefense;} {name = "deoxysdefense"} {attack = ""} {global.color = ""}} 
if numb = 68 {{sprite_index = deoxysspeed;} {name = "deoxysspeed"} {attack = ""} {global.color = ""}} 
if numb = 69 {{sprite_index = diglet;} {name = "diglet"} {attack = ""} {global.color = ""}} 
if numb = 70 {{sprite_index = ditto;} {name = "ditto"} {attack = ""} {global.color = ""}} 
if numb = 71 {{sprite_index = drifloon;} {name = "drifloon"} {attack = ""} {global.color = ""}} 
if numb = 72 {{sprite_index = electrode;} {name = "electrode"} {attack = ""} {global.color = ""}} 
if numb = 73 {{sprite_index = escaliver;} {name = "escaliver"} {attack = ""} {global.color = ""}} 
if numb = 74 {{sprite_index = froslass;} {name = "froslass"} {attack = ""} {global.color = ""}} 
if numb = 75 {{sprite_index = genescect;} {name = "genescect"} {attack = ""} {global.color = ""}} 
if numb = 76 {{sprite_index = geodude;} {name = "geodude"} {attack = ""} {global.color = ""}} 
if numb = 77 {{sprite_index = gastly;} {name = "gastly"} {attack = ""} {global.color = ""}} 
if numb = 78 {{sprite_index = giratinaorigin;} {name = "giratinaorigin"} {attack = ""} {global.color = ""}} 
if numb = 79 {{sprite_index = golurk;} {name = "golurk"} {attack = ""} {global.color = ""}} 
if numb = 80 {{sprite_index = hydreigon;} {name = "hydreigon"} {attack = ""} {global.color = ""}} 
if numb = 81 {{sprite_index = kyurem;} {name = "kyurem"} {attack = ""} {global.color = ""}} 
if numb = 82 {{sprite_index = lunatone;} {name = "lunatone"} {attack = ""} {global.color = ""}} 
if numb = 83 {{sprite_index = solrock;} {name = "solrock"} {attack = ""} {global.color = ""}} 
if numb = 84 {{sprite_index = magnemite;} {name = "magnemite"} {attack = ""} {global.color = ""}} 
if numb = 85 {{sprite_index = metagross;} {name = "metagross"} {attack = ""} {global.color = ""}} 
if numb = 86 {{sprite_index = ninjask;} {name = "ninjask"} {attack = ""} {global.color = ""}} 
if numb = 87 {{sprite_index = poliwag;} {name = "poliwag"} {attack = ""} {global.color = ""}} 
if numb = 88 {{sprite_index = psyduck;} {name = "psyduck"} {attack = ""} {global.color = ""}} 
if numb = 89 {{sprite_index = regigigas;} {name = "regigigas"} {attack = ""} {global.color = ""}} 
if numb = 90 {{sprite_index = rotom;} {name = "rotom"} {attack = ""} {global.color = ""}} 
if numb = 91 {{sprite_index = rotomfan;} {name = "rotomfan"} {attack = ""} {global.color = ""}} 
if numb = 92 {{sprite_index = rotomfrost;} {name = "rotomfrost"} {attack = ""} {global.color = ""}} 
if numb = 93 {{sprite_index = rotomheat;} {name = "rotomheat"} {attack = ""} {global.color = ""}} 
if numb = 94 {{sprite_index = rotomwash;} {name = "rotomwash"} {attack = ""} {global.color = ""}} 
if numb = 95 {{sprite_index = rotommow;} {name = "rotommow"} {attack = ""} {global.color = ""}} 
if numb = 96 {{sprite_index = sawk;} {name = "sawk"} {attack = ""} {global.color = ""}} 
if numb = 97 {{sprite_index = scolipede;} {name = "scolipede"} {attack = ""} {global.color = ""}} 
if numb = 98 {{sprite_index = shedinja;} {name = "shedinja"} {attack = ""} {global.color = ""}} 
if numb = 99 {{sprite_index = simisage;} {name = "simisage"} {attack = ""} {global.color = ""}} 
if numb = 100 {{sprite_index = sigilyph;} {name = "sigilyph"} {attack = ""} {global.color = ""}} 
if numb = 101 {{sprite_index = tentacruel;} {name = "tentacruel"} {attack = ""} {global.color = ""}} 
if numb = 102 {{sprite_index = angrybirdred;} {name = "angrybirdred"} {attack = ""} {global.color = ""}} 
if numb = 103 {{sprite_index = angrybirdwhite;} {name = "angrybirdwhite"} {attack = ""} {global.color = ""}} 
if numb = 104 {{sprite_index = angrybirdyellow;} {name = "angrybirdyellow"} {attack = ""} {global.color = ""}} 
if numb = 105 {{sprite_index = frosty;} {name = "frosty"} {attack = ""} {global.color = ""}} 
if numb = 106 {{sprite_index = professorlayton;} {name = "professorlayton"} {attack = ""} {global.color = ""}} 
if numb = 107 {{sprite_index = navi;} {name = "navi"} {attack = ""} {global.color = ""}} 
if numb = 108 {{sprite_index = nyancat;} {name = "nyancat"} {attack = ""} {global.color = ""}} 
if numb = 109 {{sprite_index = squirtle;} {name = "squirtle"} {attack = ""} {global.color = ""}} 
if numb = 110 {{sprite_index = volcarona;} {name = "volcarona"} {attack = ""} {global.color = ""}} 
if numb = 111 {{sprite_index = voltorb;} {name = "voltorb"} {attack = ""} {global.color = ""}} 
if numb = 112 {{sprite_index = wobbuffet;} {name = "wobbuffet"} {attack = ""} {global.color = ""}} 
if numb = 113 {{sprite_index = tentacool;} {name = "tentacool"} {attack = ""} {global.color = ""}} 
if numb = 114 {{sprite_index = shuckle;} {name = "shuckle"} {attack = ""} {global.color = ""}} 
if numb = 115 {{sprite_index = sneakypebbles;} {name = "sneakypebbles"} {attack = ""} {global.color = ""}} 
if numb = 116 {{sprite_index = natu;} {name = "natu"} {attack = ""} {global.color = ""}} 
if numb = 117 {{sprite_index = trapinch;} {name = "trapinch"} {attack = ""} {global.color = ""}} 
if numb = 118 {{sprite_index = cofagrigus;} {name = "cofagrigus"} {attack = ""} {global.color = ""}} 
if numb = 119 {{sprite_index = mienshao;} {name = "mienshao"} {attack = ""} {global.color = ""}} 
if numb = 120 {{sprite_index = baitfish;} {name = "baitfish"} {attack = ""} {global.color = ""}} 
if numb = 121 {{sprite_index = mudkip;} {name = "mudkip"} {attack = ""} {global.color = ""}} 
if numb = 122 {{sprite_index = zangoose;} {name = "zangoose"} {attack = ""} {global.color = ""}} 
if numb = 123 {{sprite_index = audino;} {name = "audino"} {attack = ""} {global.color = ""}} 
if numb = 124 {{sprite_index = vibrava;} {name = "vibrava"} {attack = ""} {global.color = ""}} 
if numb = 125 {{sprite_index = insidetheflyingmachine;} {name = "insidetheflyingmachine"} {attack = ""} {global.color = ""}} 
if numb = 126 {{sprite_index = azelf;} {name = "azelf"} {attack = ""} {global.color = ""}} 
if numb = 127 {{sprite_index = cancer;} {name = "cancer"} {attack = "bullet"} {global.color = "red"}} 
if numb = 128 {{sprite_index = crygonal;} {name = "crygonal"} {attack = ""} {global.color = ""}} 
if numb = 129 {{sprite_index = flygon;} {name = "flygon"} {attack = ""} {global.color = ""}} 
if numb = 130 {{sprite_index = pinkiepie;} {name = "pinkiepie"} {attack = "explosion"} {global.color = "pink"}} 
if numb = 131 {{sprite_index = uxie;} {name = "uxie"} {attack = ""} {global.color = ""}} 
if numb = 132 {{sprite_index = throh;} {name = "throh"} {attack = ""} {global.color = ""}} 
if numb = 133 {{sprite_index = swanna;} {name = "swanna"} {attack = ""} {global.color = ""}} 
if numb = 134 {{sprite_index = geno;} {name = "geno"} {attack = ""} {global.color = ""}} 
if numb = 135 {{sprite_index = mersprit;} {name = "mersprit"} {attack = ""} {global.color = ""}} 
if numb = 136 {{sprite_index = marshtomp;} {name = "marshtomp"} {attack = ""} {global.color = ""}} 
if numb = 137 {{sprite_index = pokemonegg;} {name = "pokemonegg"} {attack = ""} {global.color = ""}} 
if numb = 138 {{sprite_index = pyramidhead;} {name = "pyramidhead"} {attack = "sword"} {global.color = "gray"}} 
if numb = 139 {{sprite_index = absol;} {name = "absol"} {attack = ""} {global.color = ""}} 
if numb = 140 {{sprite_index = sanic;} {name = "sanic"} {attack = "charge"} {global.color = "blue"}} 
if numb = 141 {{sprite_index = saniclil;} {name = "saniclil"} {attack = "charge"} {global.color = "blue"}} 
if numb = 142 {{sprite_index = poisonmushroom;} {name = "poisonmushroom"} {attack = ""} {global.color = ""}} 
if numb = 143 {{sprite_index = druddigon;} {name = "druddigon"} {attack = ""} {global.color = ""}} 
if numb = 144 {{sprite_index = gardevoir;} {name = "gardevoir"} {attack = ""} {global.color = ""}} 
if numb = 145 {{sprite_index = twilightsparkle;} {name = "twilightsparkle"} {attack = "spark"} {global.color = "purple"}} 
if numb = 146 {{sprite_index = doge;} {name = "doge"} {attack = ""} {global.color = ""}} 
if numb = 147 {{sprite_index = nito;} {name = "nito"} {attack = "sword"} {global.color = "white"}} 
if numb = 148 {{sprite_index = seaththescaleless;} {name = "seaththescaleless"} {attack = "beam"} {global.color = "light blue"}} 
if numb = 149 {{sprite_index = uboa;} {name = "uboa"} {attack = ""} {global.color = ""}} 
if numb = 150 {{sprite_index = penetrator;} {name = "penetrator"} {attack = "sword"} {global.color = "light blue"}} 
if numb = 151 {{sprite_index = towerknight;} {name = "towerknight"} {attack = "sword"} {global.color = "gray"}} 
if numb = 152 {{sprite_index = rainbowdash;} {name = "rainbowdash"} {attack = "tackle"} {global.color = "light blue"}} 
if numb = 153 {{sprite_index = zerotwo;} {name = "zerotwo"} {attack = ""} {global.color = ""}} 
if numb = 154 {{sprite_index = adjudicator;} {name = "adjudicator"} {attack = "sword"} {global.color = "gray"}} 
if numb = 155 {{sprite_index = smough;} {name = "smough"} {attack = ""} {global.color = ""}} 
if numb = 156 {{sprite_index = ornstein;} {name = "ornstein"} {attack = "sword"} {global.color = "yellow"}} 
if numb = 157 {{sprite_index = madotsuki;} {name = "madotsuki"} {attack = ""} {global.color = ""}} 
if numb = 158 {{sprite_index = kirby;} {name = "kirby"} {attack = ""} {global.color = ""}} 
if numb = 159 {{sprite_index = luvdisc;} {name = "luvdisc"} {attack = ""} {global.color = ""}} 
if numb = 160 {{sprite_index = honedge;} {name = "honedge"} {attack = "sword"} {global.color = "gray"}} 
if numb = 161 {{sprite_index = oorotto;} {name = "oorotto"} {attack = "whip"} {global.color = "green"}} 
if numb = 162 {{sprite_index = xerneas;} {name = "xerneas"} {attack = "beam"} {global.color = "pink"}} 
if numb = 163 {{sprite_index = slenderman;} {name = "slenderman"} {attack = "whip"} {global.color = "black"}} 
if numb = 164 {{sprite_index = chikorita;} {name = "chikorita"} {attack = "whip"} {global.color = "green"}} 
if numb = 165 {{sprite_index = honchkrow;} {name = "honchkrow"} {attack = "beam"} {global.color = "black"}} 
if numb = 166 {{sprite_index = applejack;} {name = "applejack"} {attack = "punch"} {global.color = "orange"}} 
if numb = 167 {{sprite_index = muricaneagle;} {name = "muricaneagle"} {attack = ""} {global.color = ""}} 
if numb = 168 {{sprite_index = duckhunt;} {name = "duckhunt"} {attack = ""} {global.color = ""}} 
if numb = 169 {{sprite_index = duckhunt2;} {name = "duckhunt2"} {attack = ""} {global.color = ""}} 
if numb = 170 {{sprite_index = duckhunt3;} {name = "duckhunt3"} {attack = ""} {global.color = ""}} 
if numb = 171 {{sprite_index = wacky;} {name = "wacky"} {attack = ""} {global.color = ""}} 
if numb = 172 {{sprite_index = rarity;} {name = "rarity"} {attack = "spark"} {global.color = "white"}} 
if numb = 173 {{sprite_index = wooper;} {name = "wooper"} {attack = ""} {global.color = ""}} 
if numb = 174 {{sprite_index = hypno;} {name = "hypno"} {attack = "beam"} {global.color = "pink"}} 
if numb = 175 {{sprite_index = talonflame;} {name = "talonflame"} {attack = ""} {global.color = ""}} 
if numb = 176 {{sprite_index = isaac;} {name = "isaac"} {attack = "bullet"} {global.color = "light blue"}} 
if numb = 177 {{sprite_index = crustle;} {name = "crustle"} {attack = ""} {global.color = ""}} 
if numb = 178 {{sprite_index = gigalith;} {name = "gigalith"} {attack = ""} {global.color = ""}} 
if numb = 179 {{sprite_index = meatboy;} {name = "meatboy"} {attack = ""} {global.color = ""}} 
if numb = 180 {{sprite_index = fluttershy;} {name = "fluttershy"} {attack = "powder"} {global.color = "yellow"}} 


