global.ability = "shoot"
numb = floor(random(180));


if numb = 0 { global.spr_thegreentie = sprite_add("group\thegreentie.png",2,1,1,0,0); sprite_index = global.spr_thegreentie; name = "thegreentie"; } 
if numb = 1 { global.spr_businessbanana = sprite_add("group\businessbanana.png",2,1,1,0,0); sprite_index = global.spr_businessbanana; name = "businessbanana"; } 
if numb = 2 { global.spr_dennot = sprite_add("group\dennot.png",2,1,1,0,0); sprite_index = global.spr_dennot; name = "dennot"; } 
if numb = 3 { global.spr_mario = sprite_add("group\mario.png",2,1,1,0,0); sprite_index = global.spr_mario; name = "mario"; } 
if numb = 4 { global.spr_luigi = sprite_add("group\luigi.png",2,1,1,0,0); sprite_index = global.spr_luigi; name = "luigi"; } 
if numb = 5 { global.spr_bowser = sprite_add("group\bowser.png",2,1,1,0,0); sprite_index = global.spr_bowser; name = "bowser"; } 
if numb = 6 { global.spr_peach = sprite_add("group\peach.png",2,1,1,0,0); sprite_index = global.spr_peach; name = "peach"; } 
if numb = 7 { global.spr_drmario = sprite_add("group\drmario.png",2,1,1,0,0); sprite_index = global.spr_drmario; name = "drmario"; } 
if numb = 8 { global.spr_yoshi = sprite_add("group\yoshi.png",2,1,1,0,0); sprite_index = global.spr_yoshi; name = "yoshi"; } 
if numb = 9 { global.spr_pit = sprite_add("group\pit.png",2,1,1,0,0); sprite_index = global.spr_pit; name = "pit"; } 
if numb = 10 { global.spr_captainfalcon = sprite_add("group\captainfalcon.png",2,1,1,0,0); sprite_index = global.spr_captainfalcon; name = "captainfalcon"; } 
if numb = 11 { global.spr_mrgameandwatch = sprite_add("group\mrgameandwatch.png",2,1,1,0,0); sprite_index = global.spr_mrgameandwatch; name = "mrgameandwatch"; } 
if numb = 12 { global.spr_rob = sprite_add("group\rob.png",2,1,1,0,0); sprite_index = global.spr_rob; name = "rob"; } 
if numb = 13 { global.spr_pikachu = sprite_add("group\pikachu.png",2,1,1,0,0); sprite_index = global.spr_pikachu; name = "pikachu"; } 
if numb = 14 { global.spr_bulbasaur = sprite_add("group\bulbasaur.png",2,1,1,0,0); sprite_index = global.spr_bulbasaur; name = "bulbasaur"; } 
if numb = 15 { global.spr_ivysaur = sprite_add("group\ivysaur.png",2,1,1,0,0); sprite_index = global.spr_ivysaur; name = "ivysaur"; } 
if numb = 16 { global.spr_venusaur = sprite_add("group\venusaur.png",2,1,1,0,0); sprite_index = global.spr_venusaur; name = "venusaur"; } 
if numb = 17 { global.spr_charmander = sprite_add("group\charmander.png",2,1,1,0,0); sprite_index = global.spr_charmander; name = "charmander"; } 
if numb = 18 { global.spr_charmeleon = sprite_add("group\charmeleon.png",2,1,1,0,0); sprite_index = global.spr_charmeleon; name = "charmeleon"; } 
if numb = 19 { global.spr_charizard = sprite_add("group\charizard.png",2,1,1,0,0); sprite_index = global.spr_charizard; name = "charizard"; } 
if numb = 20 { global.spr_link = sprite_add("group\link.png",2,1,1,0,0); sprite_index = global.spr_link; name = "link"; } 
if numb = 21 { global.spr_zelda = sprite_add("group\zelda.png",2,1,1,0,0); sprite_index = global.spr_zelda; name = "zelda"; } 
if numb = 22 { global.spr_sheik = sprite_add("group\sheik.png",2,1,1,0,0); sprite_index = global.spr_sheik; name = "sheik"; } 
if numb = 23 { global.spr_ganondorf = sprite_add("group\ganondorf.png",2,1,1,0,0); sprite_index = global.spr_ganondorf; name = "ganondorf"; } 
if numb = 24 { global.spr_sonic = sprite_add("group\sonic.png",2,1,1,0,0); sprite_index = global.spr_sonic; name = "sonic"; } 
if numb = 25 { global.spr_wario = sprite_add("group\wario.png",2,1,1,0,0); sprite_index = global.spr_wario; name = "wario"; } 
if numb = 26 { global.spr_pikminred = sprite_add("group\pikminred.png",2,1,1,0,0); sprite_index = global.spr_pikminred; name = "pikminred"; } 
if numb = 27 { global.spr_pikminyellow = sprite_add("group\pikminyellow.png",2,1,1,0,0); sprite_index = global.spr_pikminyellow; name = "pikminyellow"; } 
if numb = 28 { global.spr_pikminblue = sprite_add("group\pikminblue.png",2,1,1,0,0); sprite_index = global.spr_pikminblue; name = "pikminblue"; } 
if numb = 29 { global.spr_pikminwhite = sprite_add("group\pikminwhite.png",2,1,1,0,0); sprite_index = global.spr_pikminwhite; name = "pikminwhite"; } 
if numb = 30 { global.spr_pikminpurple = sprite_add("group\pikminpurple.png",2,1,1,0,0); sprite_index = global.spr_pikminpurple; name = "pikminpurple"; } 
if numb = 31 { global.spr_engineer = sprite_add("group\engineer.png",2,1,1,0,0); sprite_index = global.spr_engineer; name = "engineer"; } 
if numb = 32 { global.spr_steve = sprite_add("group\steve.png",2,1,1,0,0); sprite_index = global.spr_steve; name = "steve"; } 
if numb = 33 { global.spr_magickared = sprite_add("group\magickared.png",2,1,1,0,0); sprite_index = global.spr_magickared; name = "magickared"; } 
if numb = 34 { global.spr_magickablue = sprite_add("group\magickablue.png",2,1,1,0,0); sprite_index = global.spr_magickablue; name = "magickablue"; } 
if numb = 35 { global.spr_magickayellow = sprite_add("group\magickayellow.png",2,1,1,0,0); sprite_index = global.spr_magickayellow; name = "magickayellow"; } 
if numb = 36 { global.spr_magickagreen = sprite_add("group\magickagreen.png",2,1,1,0,0); sprite_index = global.spr_magickagreen; name = "magickagreen"; } 
if numb = 37 { global.spr_santaclaus = sprite_add("group\santaclaus.png",2,1,1,0,0); sprite_index = global.spr_santaclaus; name = "santaclaus"; } 
if numb = 38 { global.spr_blossom = sprite_add("group\blossom.png",2,1,1,0,0); sprite_index = global.spr_blossom; name = "blossom"; } 
if numb = 39 { global.spr_bubbles = sprite_add("group\bubbles.png",2,1,1,0,0); sprite_index = global.spr_bubbles; name = "bubbles"; } 
if numb = 40 { global.spr_buttercup = sprite_add("group\buttercup.png",2,1,1,0,0); sprite_index = global.spr_buttercup; name = "buttercup"; } 
if numb = 41 { global.spr_eddy = sprite_add("group\eddy.png",2,1,1,0,0); sprite_index = global.spr_eddy; name = "eddy"; } 
if numb = 42 { global.spr_edd = sprite_add("group\edd.png",2,1,1,0,0); sprite_index = global.spr_edd; name = "edd"; } 
if numb = 43 { global.spr_ed = sprite_add("group\ed.png",2,1,1,0,0); sprite_index = global.spr_ed; name = "ed"; } 
if numb = 44 { global.spr_courage = sprite_add("group\courage.png",2,1,1,0,0); sprite_index = global.spr_courage; name = "courage"; } 
if numb = 45 { global.spr_gir = sprite_add("group\gir.png",2,1,1,0,0); sprite_index = global.spr_gir; name = "gir"; } 
if numb = 46 { global.spr_spongebob = sprite_add("group\spongebob.png",2,1,1,0,0); sprite_index = global.spr_spongebob; name = "spongebob"; } 
if numb = 47 { global.spr_captainknuckles = sprite_add("group\captainknuckles.png",2,1,1,0,0); sprite_index = global.spr_captainknuckles; name = "captainknuckles"; } 
if numb = 48 { global.spr_flapjack = sprite_add("group\flapjack.png",2,1,1,0,0); sprite_index = global.spr_flapjack; name = "flapjack"; } 
if numb = 49 { global.spr_chowder = sprite_add("group\chowder.png",2,1,1,0,0); sprite_index = global.spr_chowder; name = "chowder"; } 
if numb = 50 { global.spr_shnitzel = sprite_add("group\shnitzel.png",2,1,1,0,0); sprite_index = global.spr_shnitzel; name = "shnitzel"; } 
if numb = 51 { global.spr_waluigi = sprite_add("group\waluigi.png",2,1,1,0,0); sprite_index = global.spr_waluigi; name = "waluigi"; } 
if numb = 52 { global.spr_galvantula = sprite_add("group\galvantula.png",2,1,1,0,0); sprite_index = global.spr_galvantula; name = "galvantula"; } 
if numb = 53 { global.spr_electivire = sprite_add("group\electivire.png",2,1,1,0,0); sprite_index = global.spr_electivire; name = "electivire"; } 
if numb = 54 { global.spr_reuniclus = sprite_add("group\reuniclus.png",2,1,1,0,0); sprite_index = global.spr_reuniclus; name = "reuniclus"; } 
if numb = 55 { global.spr_pikminrock = sprite_add("group\pikminrock.png",2,1,1,0,0); sprite_index = global.spr_pikminrock; name = "pikminrock"; } 
if numb = 56 { global.spr_pikminwinged = sprite_add("group\pikminwinged.png",2,1,1,0,0); sprite_index = global.spr_pikminwinged; name = "pikminwinged"; } 
if numb = 57 { global.spr_spinda = sprite_add("group\spinda.png",2,1,1,0,0); sprite_index = global.spr_spinda; name = "spinda"; } 
if numb = 58 { global.spr_mrdickens = sprite_add("group\mrdickens.png",2,1,1,0,0); sprite_index = global.spr_mrdickens; name = "mrdickens"; } 
if numb = 59 { global.spr_castform = sprite_add("group\castform.png",2,1,1,0,0); sprite_index = global.spr_castform; name = "castform"; } 
if numb = 60 { global.spr_castformsunny = sprite_add("group\castformsunny.png",2,1,1,0,0); sprite_index = global.spr_castformsunny; name = "castformsunny"; } 
if numb = 61 { global.spr_castformrainy = sprite_add("group\castformrainy.png",2,1,1,0,0); sprite_index = global.spr_castformrainy; name = "castformrainy"; } 
if numb = 62 { global.spr_castformsnowy = sprite_add("group\castformsnowy.png",2,1,1,0,0); sprite_index = global.spr_castformsnowy; name = "castformsnowy"; } 
if numb = 63 { global.spr_beheeyem = sprite_add("group\beheeyem.png",2,1,1,0,0); sprite_index = global.spr_beheeyem; name = "beheeyem"; } 
if numb = 64 { global.spr_celebi = sprite_add("group\celebi.png",2,1,1,0,0); sprite_index = global.spr_celebi; name = "celebi"; } 
if numb = 65 { global.spr_deoxys = sprite_add("group\deoxys.png",2,1,1,0,0); sprite_index = global.spr_deoxys; name = "deoxys"; } 
if numb = 66 { global.spr_deoxysattack = sprite_add("group\deoxysattack.png",2,1,1,0,0); sprite_index = global.spr_deoxysattack; name = "deoxysattack"; } 
if numb = 67 { global.spr_deoxysdefense = sprite_add("group\deoxysdefense.png",2,1,1,0,0); sprite_index = global.spr_deoxysdefense; name = "deoxysdefense"; } 
if numb = 68 { global.spr_deoxysspeed = sprite_add("group\deoxysspeed.png",2,1,1,0,0); sprite_index = global.spr_deoxysspeed; name = "deoxysspeed"; } 
if numb = 69 { global.spr_diglet = sprite_add("group\diglet.png",2,1,1,0,0); sprite_index = global.spr_diglet; name = "diglet"; } 
if numb = 70 { global.spr_ditto = sprite_add("group\ditto.png",2,1,1,0,0); sprite_index = global.spr_ditto; name = "ditto"; } 
if numb = 71 { global.spr_drifloon = sprite_add("group\drifloon.png",2,1,1,0,0); sprite_index = global.spr_drifloon; name = "drifloon"; } 
if numb = 72 { global.spr_electrode = sprite_add("group\electrode.png",2,1,1,0,0); sprite_index = global.spr_electrode; name = "electrode"; } 
if numb = 73 { global.spr_escavalier = sprite_add("group\escavalier.png",2,1,1,0,0); sprite_index = global.spr_escavalier; name = "escavalier"; } 
if numb = 74 { global.spr_froslass = sprite_add("group\froslass.png",2,1,1,0,0); sprite_index = global.spr_froslass; name = "froslass"; } 
if numb = 75 { global.spr_genescect = sprite_add("group\genescect.png",2,1,1,0,0); sprite_index = global.spr_genescect; name = "genescect"; } 
if numb = 76 { global.spr_geodude = sprite_add("group\geodude.png",2,1,1,0,0); sprite_index = global.spr_geodude; name = "geodude"; } 
if numb = 77 { global.spr_gastly = sprite_add("group\gastly.png",2,1,1,0,0); sprite_index = global.spr_gastly; name = "gastly"; } 
if numb = 78 { global.spr_giratinaorigin = sprite_add("group\giratinaorigin.png",2,1,1,0,0); sprite_index = global.spr_giratinaorigin; name = "giratinaorigin"; } 
if numb = 79 { global.spr_golurk = sprite_add("group\golurk.png",2,1,1,0,0); sprite_index = global.spr_golurk; name = "golurk"; } 
if numb = 80 { global.spr_hydreigon = sprite_add("group\hydreigon.png",2,1,1,0,0); sprite_index = global.spr_hydreigon; name = "hydreigon"; } 
if numb = 81 { global.spr_kyurem = sprite_add("group\kyurem.png",2,1,1,0,0); sprite_index = global.spr_kyurem; name = "kyurem"; } 
if numb = 82 { global.spr_lunatone = sprite_add("group\lunatone.png",2,1,1,0,0); sprite_index = global.spr_lunatone; name = "lunatone"; } 
if numb = 83 { global.spr_solrock = sprite_add("group\solrock.png",2,1,1,0,0); sprite_index = global.spr_solrock; name = "solrock"; } 
if numb = 84 { global.spr_magnemite = sprite_add("group\magnemite.png",2,1,1,0,0); sprite_index = global.spr_magnemite; name = "magnemite"; } 
if numb = 85 { global.spr_metagross = sprite_add("group\metagross.png",2,1,1,0,0); sprite_index = global.spr_metagross; name = "metagross"; } 
if numb = 86 { global.spr_ninjask = sprite_add("group\ninjask.png",2,1,1,0,0); sprite_index = global.spr_ninjask; name = "ninjask"; } 
if numb = 87 { global.spr_poliwag = sprite_add("group\poliwag.png",2,1,1,0,0); sprite_index = global.spr_poliwag; name = "poliwag"; } 
if numb = 88 { global.spr_psyduck = sprite_add("group\psyduck.png",2,1,1,0,0); sprite_index = global.spr_psyduck; name = "psyduck"; } 
if numb = 89 { global.spr_regigigas = sprite_add("group\regigigas.png",2,1,1,0,0); sprite_index = global.spr_regigigas; name = "regigigas"; } 
if numb = 90 { global.spr_rotom = sprite_add("group\rotom.png",2,1,1,0,0); sprite_index = global.spr_rotom; name = "rotom"; } 
if numb = 91 { global.spr_rotomfan = sprite_add("group\rotomfan.png",2,1,1,0,0); sprite_index = global.spr_rotomfan; name = "rotomfan"; } 
if numb = 92 { global.spr_rotomfrost = sprite_add("group\rotomfrost.png",2,1,1,0,0); sprite_index = global.spr_rotomfrost; name = "rotomfrost"; } 
if numb = 93 { global.spr_rotomheat = sprite_add("group\rotomheat.png",2,1,1,0,0); sprite_index = global.spr_rotomheat; name = "rotomheat"; } 
if numb = 94 { global.spr_rotomwash = sprite_add("group\rotomwash.png",2,1,1,0,0); sprite_index = global.spr_rotomwash; name = "rotomwash"; } 
if numb = 95 { global.spr_rotommow = sprite_add("group\rotommow.png",2,1,1,0,0); sprite_index = global.spr_rotommow; name = "rotommow"; } 
if numb = 96 { global.spr_sawk = sprite_add("group\sawk.png",2,1,1,0,0); sprite_index = global.spr_sawk; name = "sawk"; } 
if numb = 97 { global.spr_scolipede = sprite_add("group\scolipede.png",2,1,1,0,0); sprite_index = global.spr_scolipede; name = "scolipede"; } 
if numb = 98 { global.spr_shedinja = sprite_add("group\shedinja.png",2,1,1,0,0); sprite_index = global.spr_shedinja; name = "shedinja"; } 
if numb = 99 { global.spr_simisage = sprite_add("group\simisage.png",2,1,1,0,0); sprite_index = global.spr_simisage; name = "simisage"; } 
if numb = 100 { global.spr_sigilyph = sprite_add("group\sigilyph.png",2,1,1,0,0); sprite_index = global.spr_sigilyph; name = "sigilyph"; } 
if numb = 101 { global.spr_tentacruel = sprite_add("group\tentacruel.png",2,1,1,0,0); sprite_index = global.spr_tentacruel; name = "tentacruel"; } 
if numb = 102 { global.spr_angrybirdred = sprite_add("group\angrybirdred.png",2,1,1,0,0); sprite_index = global.spr_angrybirdred; name = "angrybirdred"; } 
if numb = 103 { global.spr_angrybirdwhite = sprite_add("group\angrybirdwhite.png",2,1,1,0,0); sprite_index = global.spr_angrybirdwhite; name = "angrybirdwhite"; } 
if numb = 104 { global.spr_angrybirdyellow = sprite_add("group\angrybirdyellow.png",2,1,1,0,0); sprite_index = global.spr_angrybirdyellow; name = "angrybirdyellow"; } 
if numb = 105 { global.spr_frosty = sprite_add("group\frosty.png",2,1,1,0,0); sprite_index = global.spr_frosty; name = "frosty"; } 
if numb = 106 { global.spr_professorlayton = sprite_add("group\professorlayton.png",2,1,1,0,0); sprite_index = global.spr_professorlayton; name = "professorlayton"; } 
if numb = 107 { global.spr_navi = sprite_add("group\navi.png",2,1,1,0,0); sprite_index = global.spr_navi; name = "navi"; } 
if numb = 108 { global.spr_nyancat = sprite_add("group\nyancat.png",2,1,1,0,0); sprite_index = global.spr_nyancat; name = "nyancat"; } 
if numb = 109 { global.spr_squirtle = sprite_add("group\squirtle.png",2,1,1,0,0); sprite_index = global.spr_squirtle; name = "squirtle"; } 
if numb = 110 { global.spr_volcarona = sprite_add("group\volcarona.png",2,1,1,0,0); sprite_index = global.spr_volcarona; name = "volcarona"; } 
if numb = 111 { global.spr_voltorb = sprite_add("group\voltorb.png",2,1,1,0,0); sprite_index = global.spr_voltorb; name = "voltorb"; } 
if numb = 112 { global.spr_wobbuffet = sprite_add("group\wobbuffet.png",2,1,1,0,0); sprite_index = global.spr_wobbuffet; name = "wobbuffet"; } 
if numb = 113 { global.spr_tentacool = sprite_add("group\tentacool.png",2,1,1,0,0); sprite_index = global.spr_tentacool; name = "tentacool"; } 
if numb = 114 { global.spr_shuckle = sprite_add("group\shuckle.png",2,1,1,0,0); sprite_index = global.spr_shuckle; name = "shuckle"; } 
if numb = 115 { global.spr_sneakypebbles = sprite_add("group\sneakypebbles.png",2,1,1,0,0); sprite_index = global.spr_sneakypebbles; name = "sneakypebbles"; } 
if numb = 116 { global.spr_natu = sprite_add("group\natu.png",2,1,1,0,0); sprite_index = global.spr_natu; name = "natu"; } 
if numb = 117 { global.spr_trapinch = sprite_add("group\trapinch.png",2,1,1,0,0); sprite_index = global.spr_trapinch; name = "trapinch"; } 
if numb = 118 { global.spr_cofagrigus = sprite_add("group\cofagrigus.png",2,1,1,0,0); sprite_index = global.spr_cofagrigus; name = "cofagrigus"; } 
if numb = 119 { global.spr_mienshao = sprite_add("group\mienshao.png",2,1,1,0,0); sprite_index = global.spr_mienshao; name = "mienshao"; } 
if numb = 120 { global.spr_baitfish = sprite_add("group\baitfish.png",2,1,1,0,0); sprite_index = global.spr_baitfish; name = "baitfish"; } 
if numb = 121 { global.spr_mudkip = sprite_add("group\mudkip.png",2,1,1,0,0); sprite_index = global.spr_mudkip; name = "mudkip"; } 
if numb = 122 { global.spr_zangoose = sprite_add("group\zangoose.png",2,1,1,0,0); sprite_index = global.spr_zangoose; name = "zangoose"; } 
if numb = 123 { global.spr_audino = sprite_add("group\audino.png",2,1,1,0,0); sprite_index = global.spr_audino; name = "audino"; } 
if numb = 124 { global.spr_vibrava = sprite_add("group\vibrava.png",2,1,1,0,0); sprite_index = global.spr_vibrava; name = "vibrava"; } 
if numb = 125 { global.spr_insidetheflyingmachine = sprite_add("group\insidetheflyingmachine.png",2,1,1,0,0); sprite_index = global.spr_insidetheflyingmachine; name = "insidetheflyingmachine"; } 
if numb = 126 { global.spr_azelf = sprite_add("group\azelf.png",2,1,1,0,0); sprite_index = global.spr_azelf; name = "azelf"; } 
if numb = 127 { global.spr_cancer = sprite_add("group\cancer.png",2,1,1,0,0); sprite_index = global.spr_cancer; name = "cancer"; } 
if numb = 128 { global.spr_cryogonal = sprite_add("group\cryogonal.png",2,1,1,0,0); sprite_index = global.spr_cryogonal; name = "cryogonal"; } 
if numb = 129 { global.spr_flygon = sprite_add("group\flygon.png",2,1,1,0,0); sprite_index = global.spr_flygon; name = "flygon"; } 
if numb = 130 { global.spr_pinkiepie = sprite_add("group\pinkiepie.png",2,1,1,0,0); sprite_index = global.spr_pinkiepie; name = "pinkiepie"; } 
if numb = 131 { global.spr_uxie = sprite_add("group\uxie.png",2,1,1,0,0); sprite_index = global.spr_uxie; name = "uxie"; } 
if numb = 132 { global.spr_throh = sprite_add("group\throh.png",2,1,1,0,0); sprite_index = global.spr_throh; name = "throh"; } 
if numb = 133 { global.spr_swanna = sprite_add("group\swanna.png",2,1,1,0,0); sprite_index = global.spr_swanna; name = "swanna"; } 
if numb = 134 { global.spr_geno = sprite_add("group\geno.png",2,1,1,0,0); sprite_index = global.spr_geno; name = "geno"; } 
if numb = 135 { global.spr_mesprit = sprite_add("group\mesprit.png",2,1,1,0,0); sprite_index = global.spr_mesprit; name = "mesprit"; } 
if numb = 136 { global.spr_marshtomp = sprite_add("group\marshtomp.png",2,1,1,0,0); sprite_index = global.spr_marshtomp; name = "marshtomp"; } 
if numb = 137 { global.spr_pokemonegg = sprite_add("group\pokemonegg.png",2,1,1,0,0); sprite_index = global.spr_pokemonegg; name = "pokemonegg"; } 
if numb = 138 { global.spr_pyramidhead = sprite_add("group\pyramidhead.png",2,1,1,0,0); sprite_index = global.spr_pyramidhead; name = "pyramidhead"; } 
if numb = 139 { global.spr_absol = sprite_add("group\absol.png",2,1,1,0,0); sprite_index = global.spr_absol; name = "absol"; } 
if numb = 140 { global.spr_sanic = sprite_add("group\sanic.png",2,1,1,0,0); sprite_index = global.spr_sanic; name = "sanic"; } 
if numb = 141 { global.spr_saniclil = sprite_add("group\saniclil.png",2,1,1,0,0); sprite_index = global.spr_saniclil; name = "saniclil"; } 
if numb = 142 { global.spr_poisonmushroom = sprite_add("group\poisonmushroom.png",2,1,1,0,0); sprite_index = global.spr_poisonmushroom; name = "poisonmushroom"; } 
if numb = 143 { global.spr_druddigon = sprite_add("group\druddigon.png",2,1,1,0,0); sprite_index = global.spr_druddigon; name = "druddigon"; } 
if numb = 144 { global.spr_gardevoir = sprite_add("group\gardevoir.png",2,1,1,0,0); sprite_index = global.spr_gardevoir; name = "gardevoir"; } 
if numb = 145 { global.spr_twilightsparkle = sprite_add("group\twilightsparkle.png",2,1,1,0,0); sprite_index = global.spr_twilightsparkle; name = "twilightsparkle"; } 
if numb = 146 { global.spr_doge = sprite_add("group\doge.png",2,1,1,0,0); sprite_index = global.spr_doge; name = "doge"; } 
if numb = 147 { global.spr_nito = sprite_add("group\nito.png",2,1,1,0,0); sprite_index = global.spr_nito; name = "nito"; } 
if numb = 148 { global.spr_seaththescaleless = sprite_add("group\seaththescaleless.png",2,1,1,0,0); sprite_index = global.spr_seaththescaleless; name = "seaththescaleless"; } 
if numb = 149 { global.spr_uboa = sprite_add("group\uboa.png",2,1,1,0,0); sprite_index = global.spr_uboa; name = "uboa"; } 
if numb = 150 { global.spr_penetrator = sprite_add("group\penetrator.png",2,1,1,0,0); sprite_index = global.spr_penetrator; name = "penetrator"; } 
if numb = 151 { global.spr_towerknight = sprite_add("group\towerknight.png",2,1,1,0,0); sprite_index = global.spr_towerknight; name = "towerknight"; } 
if numb = 152 { global.spr_rainbowdash = sprite_add("group\rainbowdash.png",2,1,1,0,0); sprite_index = global.spr_rainbowdash; name = "rainbowdash"; } 
if numb = 153 { global.spr_zerotwo = sprite_add("group\zerotwo.png",2,1,1,0,0); sprite_index = global.spr_zerotwo; name = "zerotwo"; } 
if numb = 154 { global.spr_adjudicator = sprite_add("group\adjudicator.png",2,1,1,0,0); sprite_index = global.spr_adjudicator; name = "adjudicator"; } 
if numb = 155 { global.spr_smough = sprite_add("group\smough.png",2,1,1,0,0); sprite_index = global.spr_smough; name = "smough"; } 
if numb = 156 { global.spr_ornstein = sprite_add("group\ornstein.png",2,1,1,0,0); sprite_index = global.spr_ornstein; name = "ornstein"; } 
if numb = 157 { global.spr_madotsuki = sprite_add("group\madotsuki.png",2,1,1,0,0); sprite_index = global.spr_madotsuki; name = "madotsuki"; } 
if numb = 158 { global.spr_kirby = sprite_add("group\kirby.png",2,1,1,0,0); sprite_index = global.spr_kirby; name = "kirby"; } 
if numb = 159 { global.spr_luvdisc = sprite_add("group\luvdisc.png",2,1,1,0,0); sprite_index = global.spr_luvdisc; name = "luvdisc"; } 
if numb = 160 { global.spr_honedge = sprite_add("group\honedge.png",2,1,1,0,0); sprite_index = global.spr_honedge; name = "honedge"; } 
if numb = 161 { global.spr_trevenant = sprite_add("group\trevenant.png",2,1,1,0,0); sprite_index = global.spr_trevenant; name = "trevenant"; } 
if numb = 162 { global.spr_xerneas = sprite_add("group\xerneas.png",2,1,1,0,0); sprite_index = global.spr_xerneas; name = "xerneas"; } 
if numb = 163 { global.spr_slenderman = sprite_add("group\slenderman.png",2,1,1,0,0); sprite_index = global.spr_slenderman; name = "slenderman"; } 
if numb = 164 { global.spr_chikorita = sprite_add("group\chikorita.png",2,1,1,0,0); sprite_index = global.spr_chikorita; name = "chikorita"; } 
if numb = 165 { global.spr_honchkrow = sprite_add("group\honchkrow.png",2,1,1,0,0); sprite_index = global.spr_honchkrow; name = "honchkrow"; } 
if numb = 166 { global.spr_applejack = sprite_add("group\applejack.png",2,1,1,0,0); sprite_index = global.spr_applejack; name = "applejack"; } 
if numb = 167 { global.spr_muricaneagle = sprite_add("group\muricaneagle.png",2,1,1,0,0); sprite_index = global.spr_muricaneagle; name = "muricaneagle"; } 
if numb = 168 { global.spr_duckhunt = sprite_add("group\duckhunt.png",2,1,1,0,0); sprite_index = global.spr_duckhunt; name = "duckhunt"; } 
if numb = 169 { global.spr_duckhunt2 = sprite_add("group\duckhunt2.png",2,1,1,0,0); sprite_index = global.spr_duckhunt2; name = "duckhunt2"; } 
if numb = 170 { global.spr_duckhunt3 = sprite_add("group\duckhunt3.png",2,1,1,0,0); sprite_index = global.spr_duckhunt3; name = "duckhunt3"; } 
if numb = 171 { global.spr_wacky = sprite_add("group\wacky.png",2,1,1,0,0); sprite_index = global.spr_wacky; name = "wacky"; } 
if numb = 172 { global.spr_rarity = sprite_add("group\rarity.png",2,1,1,0,0); sprite_index = global.spr_rarity; name = "rarity"; } 
if numb = 173 { global.spr_wooper = sprite_add("group\wooper.png",2,1,1,0,0); sprite_index = global.spr_wooper; name = "wooper"; } 
if numb = 174 { global.spr_hypno = sprite_add("group\hypno.png",2,1,1,0,0); sprite_index = global.spr_hypno; name = "hypno"; } 
if numb = 175 { global.spr_talonflame = sprite_add("group\talonflame.png",2,1,1,0,0); sprite_index = global.spr_talonflame; name = "talonflame"; } 
if numb = 176 { global.spr_isaac = sprite_add("group\isaac.png",2,1,1,0,0); sprite_index = global.spr_isaac; name = "isaac"; } 
if numb = 177 { global.spr_crustle = sprite_add("group\crustle.png",2,1,1,0,0); sprite_index = global.spr_crustle; name = "crustle"; } 
if numb = 178 { global.spr_gigalith = sprite_add("group\gigalith.png",2,1,1,0,0); sprite_index = global.spr_gigalith; name = "gigalith"; } 
if numb = 179 { global.spr_meatboy = sprite_add("group\meatboy.png",2,1,1,0,0); sprite_index = global.spr_meatboy; name = "meatboy"; } 
if numb = 180 { global.spr_fluttershy = sprite_add("group\fluttershy.png",2,1,1,0,0); sprite_index = global.spr_fluttershy; name = "fluttershy"; } 
if numb = 181 { global.spr_geralt = sprite_add("group\geralt.png",2,1,1,0,0); sprite_index = global.spr_geralt; name = "geralt"; } 
if numb = 182 { global.spr_megaampharos = sprite_add("group\megaampharos.png",2,1,1,0,0); sprite_index = global.spr_megaampharos; name = "megaampharos"; } 
if numb = 183 { global.spr_nosepass = sprite_add("group\nosepass.png",2,1,1,0,0); sprite_index = global.spr_nosepass; name = "nosepass"; } 
if numb = 184 { global.spr_mew = sprite_add("group\mew.png",2,1,1,0,0); sprite_index = global.spr_mew; name = "mew"; } 
if numb = 185 { global.spr_dialga = sprite_add("group\dialga.png",2,1,1,0,0); sprite_index = global.spr_dialga; name = "dialga"; } 
if numb = 186 { global.spr_ampharos = sprite_add("group\ampharos.png",2,1,1,0,0); sprite_index = global.spr_ampharos; name = "ampharos"; } 
if numb = 187 { global.spr_nyarlathoep = sprite_add("group\nyarlathoep.png",2,1,1,0,0); sprite_index = global.spr_nyarlathoep; name = "nyarlathoep"; } 
if numb = 188 { global.spr_latias = sprite_add("group\latias.png",2,1,1,0,0); sprite_index = global.spr_latias; name = "latias"; } 
if numb = 189 { global.spr_cthulhu = sprite_add("group\cthulhu.png",2,1,1,0,0); sprite_index = global.spr_cthulhu; name = "cthulhu"; } 
if numb = 190 { global.spr_latios = sprite_add("group\latios.png",2,1,1,0,0); sprite_index = global.spr_latios; name = "latios"; } 
if numb = 191 { global.spr_stantler = sprite_add("group\stantler.png",2,1,1,0,0); sprite_index = global.spr_stantler; name = "stantler"; } 
if numb = 192 { global.spr_yogsothoth = sprite_add("group\yogsothoth.png",2,1,1,0,0); sprite_index = global.spr_yogsothoth; name = "yogsothoth"; } 
if numb = 193 { global.spr_pingu = sprite_add("group\pingu.png",2,1,1,0,0); sprite_index = global.spr_pingu; name = "pingu"; } 
if numb = 194 { global.spr_palkia = sprite_add("group\palkia.png",2,1,1,0,0); sprite_index = global.spr_palkia; name = "palkia"; } 
if numb = 195 { global.spr_shoggoth = sprite_add("group\shoggoth.png",2,1,1,0,0); sprite_index = global.spr_shoggoth; name = "shoggoth"; } 
if numb = 196 { global.spr_smeargle = sprite_add("group\smeargle.png",2,1,1,0,0); sprite_index = global.spr_smeargle; name = "smeargle"; } 
if numb = 197 { global.spr_bayleaf = sprite_add("group\bayleaf.png",2,1,1,0,0); sprite_index = global.spr_bayleaf; name = "bayleaf"; } 
if numb = 198 { global.spr_megablaziken = sprite_add("group\megablaziken.png",2,1,1,0,0); sprite_index = global.spr_megablaziken; name = "megablaziken"; } 
if numb = 199 { global.spr_ghroth = sprite_add("group\ghroth.png",2,1,1,0,0); sprite_index = global.spr_ghroth; name = "ghroth"; } 
if numb = 200 { global.spr_megamawile = sprite_add("group\megamawile.png",2,1,1,0,0); sprite_index = global.spr_megamawile; name = "megamawile"; } 
if numb = 201 { global.spr_tailow = sprite_add("group\tailow.png",2,1,1,0,0); sprite_index = global.spr_tailow; name = "tailow"; } 
if numb = 202 { global.spr_weedle = sprite_add("group\weedle.png",2,1,1,0,0); sprite_index = global.spr_weedle; name = "weedle"; } 
if numb = 203 { global.spr_swellow = sprite_add("group\swellow.png",2,1,1,0,0); sprite_index = global.spr_swellow; name = "swellow"; } 
if numb = 204 { global.spr_koffing = sprite_add("group\koffing.png",2,1,1,0,0); sprite_index = global.spr_koffing; name = "koffing"; } 
if numb = 205 { global.spr_snorunt = sprite_add("group\snorunt.png",2,1,1,0,0); sprite_index = global.spr_snorunt; name = "snorunt"; } 
if numb = 206 { global.spr_linux = sprite_add("group\linux.png",2,1,1,0,0); sprite_index = global.spr_linux; name = "linux"; } 
if numb = 207 { global.spr_sableye = sprite_add("group\sableye.png",2,1,1,0,0); sprite_index = global.spr_sableye; name = "sableye"; } 
if numb = 208 { global.spr_spike = sprite_add("group\spike.png",2,1,1,0,0); sprite_index = global.spr_spike; name = "spike"; } 
if numb = 209 { global.spr_elderthing = sprite_add("group\elderthing.png",2,1,1,0,0); sprite_index = global.spr_elderthing; name = "elderthing"; } 
if numb = 210 { global.spr_shadowlurkerm = sprite_add("group\shadowlurkerm.png",2,1,1,0,0); sprite_index = global.spr_shadowlurkerm; name = "shadowlurkerm"; } 
if numb = 211 { global.spr_ostrava = sprite_add("group\ostrava.png",2,1,1,0,0); sprite_index = global.spr_ostrava; name = "ostrava"; } 
if numb = 212 { global.spr_havel = sprite_add("group\havel.png",2,1,1,0,0); sprite_index = global.spr_havel; name = "havel"; } 
if numb = 213 { global.spr_ferroseed = sprite_add("group\ferroseed.png",2,1,1,0,0); sprite_index = global.spr_ferroseed; name = "ferroseed"; } 
if numb = 214 { global.spr_meganium = sprite_add("group\meganium.png",2,1,1,0,0); sprite_index = global.spr_meganium; name = "meganium"; } 
if numb = 215 { global.spr_sudowoodo = sprite_add("group\sudowoodo.png",2,1,1,0,0); sprite_index = global.spr_sudowoodo; name = "sudowoodo"; } 
if numb = 216 { global.spr_gulpin = sprite_add("group\gulpin.png",2,1,1,0,0); sprite_index = global.spr_gulpin; name = "gulpin"; } 
if numb = 217 { global.spr_rambi = sprite_add("group\rambi.png",2,1,1,0,0); sprite_index = global.spr_rambi; name = "rambi"; } 
if numb = 218 { global.spr_princesscelestia = sprite_add("group\princesscelestia.png",2,1,1,0,0); sprite_index = global.spr_princesscelestia; name = "princesscelestia"; } 
if numb = 219 { global.spr_marvelouschester = sprite_add("group\marvelouschester.png",2,1,1,0,0); sprite_index = global.spr_marvelouschester; name = "marvelouschester"; } 
if numb = 220 { global.spr_snover = sprite_add("group\snover.png",2,1,1,0,0); sprite_index = global.spr_snover; name = "snover"; } 
if numb = 221 { global.spr_artorias = sprite_add("group\artorias.png",2,1,1,0,0); sprite_index = global.spr_artorias; name = "artorias"; } 
if numb = 222 { global.spr_abomasnow = sprite_add("group\abomasnow.png",2,1,1,0,0); sprite_index = global.spr_abomasnow; name = "abomasnow"; } 
if numb = 223 { global.spr_tangrowth = sprite_add("group\tangrowth.png",2,1,1,0,0); sprite_index = global.spr_tangrowth; name = "tangrowth"; } 
if numb = 224 { global.spr_haxorus = sprite_add("group\haxorus.png",2,1,1,0,0); sprite_index = global.spr_haxorus; name = "haxorus"; } 
if numb = 225 { global.spr_surskit = sprite_add("group\surskit.png",2,1,1,0,0); sprite_index = global.spr_surskit; name = "surskit"; } 
if numb = 226 { global.spr_oneofthefourwings = sprite_add("group\oneofthefourwings.png",2,1,1,0,0); sprite_index = global.spr_oneofthefourwings; name = "oneofthefourwings"; } 
if numb = 227 { global.spr_maneatermildred = sprite_add("group\maneatermildred.png",2,1,1,0,0); sprite_index = global.spr_maneatermildred; name = "maneatermildred"; } 
if numb = 228 { global.spr_megaman = sprite_add("group\megaman.png",2,1,1,0,0); sprite_index = global.spr_megaman; name = "megaman"; } 
if numb = 229 { global.spr_squiddle = sprite_add("group\squiddle.png",2,1,1,0,0); sprite_index = global.spr_squiddle; name = "squiddle"; } 
if numb = 230 { global.spr_sawsbuckwinter = sprite_add("group\sawsbuckwinter.png",2,1,1,0,0); sprite_index = global.spr_sawsbuckwinter; name = "sawsbuckwinter"; } 
if numb = 231 { global.spr_porygonz = sprite_add("group\porygonz.png",2,1,1,0,0); sprite_index = global.spr_porygonz; name = "porygonz"; } 
if numb = 232 { global.spr_ciarin = sprite_add("group\ciarin.png",2,1,1,0,0); sprite_index = global.spr_ciarin; name = "ciarin"; } 
if numb = 233 { global.spr_sawsbuckspring = sprite_add("group\sawsbuckspring.png",2,1,1,0,0); sprite_index = global.spr_sawsbuckspring; name = "sawsbuckspring"; } 
if numb = 234 { global.spr_sawsbucksummer = sprite_add("group\sawsbucksummer.png",2,1,1,0,0); sprite_index = global.spr_sawsbucksummer; name = "sawsbucksummer"; } 
if numb = 235 { global.spr_sawsbuckautumn = sprite_add("group\sawsbuckautumn.png",2,1,1,0,0); sprite_index = global.spr_sawsbuckautumn; name = "sawsbuckautumn"; } 
if numb = 236 { global.spr_stunfisk = sprite_add("group\stunfisk.png",2,1,1,0,0); sprite_index = global.spr_stunfisk; name = "stunfisk"; } 
if numb = 237 { global.spr_starly = sprite_add("group\starly.png",2,1,1,0,0); sprite_index = global.spr_starly; name = "starly"; } 
if numb = 238 { global.spr_lautrec = sprite_add("group\lautrec.png",2,1,1,0,0); sprite_index = global.spr_lautrec; name = "lautrec"; } 
if numb = 239 { global.spr_musharna = sprite_add("group\musharna.png",2,1,1,0,0); sprite_index = global.spr_musharna; name = "musharna"; } 
if numb = 240 { global.spr_munna = sprite_add("group\munna.png",2,1,1,0,0); sprite_index = global.spr_munna; name = "munna"; } 
if numb = 241 { global.spr_porygon2 = sprite_add("group\porygon2.png",2,1,1,0,0); sprite_index = global.spr_porygon2; name = "porygon2"; } 
if numb = 242 { global.spr_doran = sprite_add("group\doran.png",2,1,1,0,0); sprite_index = global.spr_doran; name = "doran"; } 
if numb = 243 { global.spr_sunkern = sprite_add("group\sunkern.png",2,1,1,0,0); sprite_index = global.spr_sunkern; name = "sunkern"; } 
if numb = 244 { global.spr_porygon = sprite_add("group\porygon.png",2,1,1,0,0); sprite_index = global.spr_porygon; name = "porygon"; } 
if numb = 245 { global.spr_sunflora = sprite_add("group\sunflora.png",2,1,1,0,0); sprite_index = global.spr_sunflora; name = "sunflora"; } 
if numb = 246 { global.spr_scizor = sprite_add("group\scizor.png",2,1,1,0,0); sprite_index = global.spr_scizor; name = "scizor"; } 
if numb = 247 { global.spr_foongus = sprite_add("group\foongus.png",2,1,1,0,0); sprite_index = global.spr_foongus; name = "foongus"; } 
if numb = 248 { global.spr_amoongus = sprite_add("group\amoongus.png",2,1,1,0,0); sprite_index = global.spr_amoongus; name = "amoongus"; } 
if numb = 249 { global.spr_silcoon = sprite_add("group\silcoon.png",2,1,1,0,0); sprite_index = global.spr_silcoon; name = "silcoon"; } 
if numb = 250 { global.spr_cascoon = sprite_add("group\cascoon.png",2,1,1,0,0); sprite_index = global.spr_cascoon; name = "cascoon"; } 
if numb = 251 { global.spr_duskull = sprite_add("group\duskull.png",2,1,1,0,0); sprite_index = global.spr_duskull; name = "duskull"; } 
if numb = 252 { global.spr_probopass = sprite_add("group\probopass.png",2,1,1,0,0); sprite_index = global.spr_probopass; name = "probopass"; } 
if numb = 253 { global.spr_lampent = sprite_add("group\lampent.png",2,1,1,0,0); sprite_index = global.spr_lampent; name = "lampent"; } 
if numb = 254 { global.spr_girafarig = sprite_add("group\girafarig.png",2,1,1,0,0); sprite_index = global.spr_girafarig; name = "girafarig"; } 
if numb = 255 { global.spr_murkrow = sprite_add("group\murkrow.png",2,1,1,0,0); sprite_index = global.spr_murkrow; name = "murkrow"; } 
if numb = 256 { global.spr_maractus = sprite_add("group\maractus.png",2,1,1,0,0); sprite_index = global.spr_maractus; name = "maractus"; } 
if numb = 257 { global.spr_jellyfish = sprite_add("group\jellyfish.png",2,1,1,0,0); sprite_index = global.spr_jellyfish; name = "jellyfish"; } 
if numb = 258 { global.spr_rapidash = sprite_add("group\rapidash.png",2,1,1,0,0); sprite_index = global.spr_rapidash; name = "rapidash"; } 
if numb = 259 { global.spr_rufflet = sprite_add("group\rufflet.png",2,1,1,0,0); sprite_index = global.spr_rufflet; name = "rufflet"; } 
if numb = 260 { global.spr_peliper = sprite_add("group\peliper.png",2,1,1,0,0); sprite_index = global.spr_peliper; name = "peliper"; } 
if numb = 261 { global.spr_quote = sprite_add("group\quote.png",2,1,1,0,0); sprite_index = global.spr_quote; name = "quote"; } 
if numb = 262 { global.spr_curlybrace = sprite_add("group\curlybrace.png",2,1,1,0,0); sprite_index = global.spr_curlybrace; name = "curlybrace"; } 
if numb = 263 { global.spr_cyndaquil = sprite_add("group\cyndaquil.png",2,1,1,0,0); sprite_index = global.spr_cyndaquil; name = "cyndaquil"; } 
if numb = 264 { global.spr_piranhaplant = sprite_add("group\piranhaplant.png",2,1,1,0,0); sprite_index = global.spr_piranhaplant; name = "piranhaplant"; } 
if numb = 265 { global.spr_braviary = sprite_add("group\braviary.png",2,1,1,0,0); sprite_index = global.spr_braviary; name = "braviary"; } 
if numb = 266 { global.spr_conkeldurr = sprite_add("group\conkeldurr.png",2,1,1,0,0); sprite_index = global.spr_conkeldurr; name = "conkeldurr"; } 
if numb = 267 { global.spr_yamask = sprite_add("group\yamask.png",2,1,1,0,0); sprite_index = global.spr_yamask; name = "yamask"; } 
if numb = 268 { global.spr_croagunk = sprite_add("group\croagunk.png",2,1,1,0,0); sprite_index = global.spr_croagunk; name = "croagunk"; } 
if numb = 269 { global.spr_lumineon = sprite_add("group\lumineon.png",2,1,1,0,0); sprite_index = global.spr_lumineon; name = "lumineon"; } 
if numb = 270 { global.spr_scraggy = sprite_add("group\scraggy.png",2,1,1,0,0); sprite_index = global.spr_scraggy; name = "scraggy"; } 
if numb = 271 { global.spr_toxicroak = sprite_add("group\toxicroak.png",2,1,1,0,0); sprite_index = global.spr_toxicroak; name = "toxicroak"; } 
if numb = 272 { global.spr_vanillish = sprite_add("group\vanillish.png",2,1,1,0,0); sprite_index = global.spr_vanillish; name = "vanillish"; } 
if numb = 273 { global.spr_princessluna = sprite_add("group\princessluna.png",2,1,1,0,0); sprite_index = global.spr_princessluna; name = "princessluna"; } 
if numb = 274 { global.spr_staryu = sprite_add("group\staryu.png",2,1,1,0,0); sprite_index = global.spr_staryu; name = "staryu"; } 
if numb = 275 { global.spr_scrafty = sprite_add("group\scrafty.png",2,1,1,0,0); sprite_index = global.spr_scrafty; name = "scrafty"; } 
if numb = 276 { global.spr_raven = sprite_add("group\raven.png",2,1,1,0,0); sprite_index = global.spr_raven; name = "raven"; } 
if numb = 277 { global.spr_starmie = sprite_add("group\starmie.png",2,1,1,0,0); sprite_index = global.spr_starmie; name = "starmie"; } 
if numb = 278 { global.spr_sneasel = sprite_add("group\sneasel.png",2,1,1,0,0); sprite_index = global.spr_sneasel; name = "sneasel"; } 
if numb = 279 { global.spr_vanilluxe = sprite_add("group\vanilluxe.png",2,1,1,0,0); sprite_index = global.spr_vanilluxe; name = "vanilluxe"; } 
if numb = 280 { global.spr_zoroark = sprite_add("group\zoroark.png",2,1,1,0,0); sprite_index = global.spr_zoroark; name = "zoroark"; } 
if numb = 281 { global.spr_dusknoir = sprite_add("group\dusknoir.png",2,1,1,0,0); sprite_index = global.spr_dusknoir; name = "dusknoir"; } 
if numb = 282 { global.spr_tentaquil = sprite_add("group\tentaquil.png",2,1,1,0,0); sprite_index = global.spr_tentaquil; name = "tentaquil"; } 
if numb = 283 { global.spr_mienfoo = sprite_add("group\mienfoo.png",2,1,1,0,0); sprite_index = global.spr_mienfoo; name = "mienfoo"; } 
if numb = 284 { global.spr_strongbad = sprite_add("group\strongbad.png",2,1,1,0,0); sprite_index = global.spr_strongbad; name = "strongbad"; } 
if numb = 285 { global.spr_dante = sprite_add("group\dante.png",2,1,1,0,0); sprite_index = global.spr_dante; name = "dante"; } 
if numb = 286 { global.spr_torchic = sprite_add("group\torchic.png",2,1,1,0,0); sprite_index = global.spr_torchic; name = "torchic"; } 
if numb = 287 { global.spr_cradily = sprite_add("group\cradily.png",2,1,1,0,0); sprite_index = global.spr_cradily; name = "cradily"; } 
if numb = 288 { global.spr_catinthehat = sprite_add("group\catinthehat.png",2,1,1,0,0); sprite_index = global.spr_catinthehat; name = "catinthehat"; } 
if numb = 289 { global.spr_homestar = sprite_add("group\homestar.png",2,1,1,0,0); sprite_index = global.spr_homestar; name = "homestar"; } 
if numb = 290 { global.spr_foliat = sprite_add("group\foliat.png",2,1,1,0,0); sprite_index = global.spr_foliat; name = "foliat"; } 
if numb = 291 { global.spr_lileep = sprite_add("group\lileep.png",2,1,1,0,0); sprite_index = global.spr_lileep; name = "lileep"; } 
if numb = 292 { global.spr_trogdor = sprite_add("group\trogdor.png",2,1,1,0,0); sprite_index = global.spr_trogdor; name = "trogdor"; } 
if numb = 293 { global.spr_florabri = sprite_add("group\florabri.png",2,1,1,0,0); sprite_index = global.spr_florabri; name = "florabri"; } 
if numb = 294 { global.spr_timburr = sprite_add("group\timburr.png",2,1,1,0,0); sprite_index = global.spr_timburr; name = "timburr"; } 
if numb = 295 { global.spr_florresum = sprite_add("group\florresum.png",2,1,1,0,0); sprite_index = global.spr_florresum; name = "florresum"; } 
if numb = 296 { global.spr_omanyte = sprite_add("group\omanyte.png",2,1,1,0,0); sprite_index = global.spr_omanyte; name = "omanyte"; } 
if numb = 297 { global.spr_masquerain = sprite_add("group\masquerain.png",2,1,1,0,0); sprite_index = global.spr_masquerain; name = "masquerain"; } 
if numb = 298 { global.spr_registeel = sprite_add("group\registeel.png",2,1,1,0,0); sprite_index = global.spr_registeel; name = "registeel"; } 
if numb = 299 { global.spr_swampert = sprite_add("group\swampert.png",2,1,1,0,0); sprite_index = global.spr_swampert; name = "swampert"; } 
if numb = 300 { global.spr_spiritomb = sprite_add("group\spiritomb.png",2,1,1,0,0); sprite_index = global.spr_spiritomb; name = "spiritomb"; } 
if numb = 301 { global.spr_regice = sprite_add("group\regice.png",2,1,1,0,0); sprite_index = global.spr_regice; name = "regice"; } 
if numb = 302 { global.spr_sonichu = sprite_add("group\sonichu.png",2,1,1,0,0); sprite_index = global.spr_sonichu; name = "sonichu"; } 
if numb = 303 { global.spr_regirock = sprite_add("group\regirock.png",2,1,1,0,0); sprite_index = global.spr_regirock; name = "regirock"; } 
if numb = 304 { global.spr_ferrothorn = sprite_add("group\ferrothorn.png",2,1,1,0,0); sprite_index = global.spr_ferrothorn; name = "ferrothorn"; } 
if numb = 305 { global.spr_substitute = sprite_add("group\substitute.png",2,1,1,0,0); sprite_index = global.spr_substitute; name = "substitute"; } 
if numb = 306 { global.spr_rosechu = sprite_add("group\rosechu.png",2,1,1,0,0); sprite_index = global.spr_rosechu; name = "rosechu"; } 
if numb = 307 { global.spr_leghorse = sprite_add("group\leghorse.png",2,1,1,0,0); sprite_index = global.spr_leghorse; name = "leghorse"; } 
if numb = 308 { global.spr_vanillite = sprite_add("group\vanillite.png",2,1,1,0,0); sprite_index = global.spr_vanillite; name = "vanillite"; } 
if numb = 309 { global.spr_ghostpokemon = sprite_add("group\ghostpokemon.png",2,1,1,0,0); sprite_index = global.spr_ghostpokemon; name = "ghostpokemon"; } 
if numb = 310 { global.spr_gurdurr = sprite_add("group\gurdurr.png",2,1,1,0,0); sprite_index = global.spr_gurdurr; name = "gurdurr"; } 
if numb = 311 { global.spr_creeper = sprite_add("group\creeper.png",2,1,1,0,0); sprite_index = global.spr_creeper; name = "creeper"; } 
if numb = 312 { global.spr_enderman = sprite_add("group\enderman.png",2,1,1,0,0); sprite_index = global.spr_enderman; name = "enderman"; } 
if numb = 313 { global.spr_silverfish = sprite_add("group\silverfish.png",2,1,1,0,0); sprite_index = global.spr_silverfish; name = "silverfish"; } 
if numb = 314 { global.spr_slimecube = sprite_add("group\slimecube.png",2,1,1,0,0); sprite_index = global.spr_slimecube; name = "slimecube"; } 
if numb = 315 { global.spr_magmacube = sprite_add("group\magmacube.png",2,1,1,0,0); sprite_index = global.spr_magmacube; name = "magmacube"; } 
if numb = 316 { global.spr_wither = sprite_add("group\wither.png",2,1,1,0,0); sprite_index = global.spr_wither; name = "wither"; } 
if numb = 317 { global.spr_beholder = sprite_add("group\beholder.png",2,1,1,0,0); sprite_index = global.spr_beholder; name = "beholder"; } 
if numb = 318 { global.spr_beholdereyeoffrost = sprite_add("group\beholdereyeoffrost.png",2,1,1,0,0); sprite_index = global.spr_beholdereyeoffrost; name = "beholdereyeoffrost"; } 
if numb = 319 { global.spr_beholdereyeofchaos = sprite_add("group\beholdereyeofchaos.png",2,1,1,0,0); sprite_index = global.spr_beholdereyeofchaos; name = "beholdereyeofchaos"; } 
if numb = 320 { global.spr_swablu = sprite_add("group\swablu.png",2,1,1,0,0); sprite_index = global.spr_swablu; name = "swablu"; } 
if numb = 321 { global.spr_vivillionmeadow = sprite_add("group\vivillionmeadow.png",2,1,1,0,0); sprite_index = global.spr_vivillionmeadow; name = "vivillionmeadow"; } 
if numb = 322 { global.spr_missingno = sprite_add("group\missingno.png",2,1,1,0,0); sprite_index = global.spr_missingno; name = "missingno"; } 
if numb = 323 { global.spr_unowna = sprite_add("group\unowna.png",2,1,1,0,0); sprite_index = global.spr_unowna; name = "unowna"; } 
if numb = 324 { global.spr_unownb = sprite_add("group\unownb.png",2,1,1,0,0); sprite_index = global.spr_unownb; name = "unownb"; } 
if numb = 325 { global.spr_unownc = sprite_add("group\unownc.png",2,1,1,0,0); sprite_index = global.spr_unownc; name = "unownc"; } 
if numb = 326 { global.spr_unownd = sprite_add("group\unownd.png",2,1,1,0,0); sprite_index = global.spr_unownd; name = "unownd"; } 
if numb = 327 { global.spr_unowne = sprite_add("group\unowne.png",2,1,1,0,0); sprite_index = global.spr_unowne; name = "unowne"; } 
if numb = 328 { global.spr_unownf = sprite_add("group\unownf.png",2,1,1,0,0); sprite_index = global.spr_unownf; name = "unownf"; } 
if numb = 329 { global.spr_unowng = sprite_add("group\unowng.png",2,1,1,0,0); sprite_index = global.spr_unowng; name = "unowng"; } 
if numb = 330 { global.spr_unownh = sprite_add("group\unownh.png",2,1,1,0,0); sprite_index = global.spr_unownh; name = "unownh"; } 
if numb = 331 { global.spr_unowni = sprite_add("group\unowni.png",2,1,1,0,0); sprite_index = global.spr_unowni; name = "unowni"; } 
if numb = 332 { global.spr_unownj = sprite_add("group\unownj.png",2,1,1,0,0); sprite_index = global.spr_unownj; name = "unownj"; } 
if numb = 333 { global.spr_unownk = sprite_add("group\unownk.png",2,1,1,0,0); sprite_index = global.spr_unownk; name = "unownk"; } 
if numb = 334 { global.spr_unownl = sprite_add("group\unownl.png",2,1,1,0,0); sprite_index = global.spr_unownl; name = "unownl"; } 
if numb = 335 { global.spr_unownm = sprite_add("group\unownm.png",2,1,1,0,0); sprite_index = global.spr_unownm; name = "unownm"; } 
if numb = 336 { global.spr_unownn = sprite_add("group\unownn.png",2,1,1,0,0); sprite_index = global.spr_unownn; name = "unownn"; } 
if numb = 337 { global.spr_unowno = sprite_add("group\unowno.png",2,1,1,0,0); sprite_index = global.spr_unowno; name = "unowno"; } 
if numb = 338 { global.spr_unownp = sprite_add("group\unownp.png",2,1,1,0,0); sprite_index = global.spr_unownp; name = "unownp"; } 
if numb = 339 { global.spr_unownq = sprite_add("group\unownq.png",2,1,1,0,0); sprite_index = global.spr_unownq; name = "unownq"; } 
if numb = 340 { global.spr_unownr = sprite_add("group\unownr.png",2,1,1,0,0); sprite_index = global.spr_unownr; name = "unownr"; } 
if numb = 341 { global.spr_unowns = sprite_add("group\unowns.png",2,1,1,0,0); sprite_index = global.spr_unowns; name = "unowns"; } 
if numb = 342 { global.spr_unownt = sprite_add("group\unownt.png",2,1,1,0,0); sprite_index = global.spr_unownt; name = "unownt"; } 
if numb = 343 { global.spr_unownu = sprite_add("group\unownu.png",2,1,1,0,0); sprite_index = global.spr_unownu; name = "unownu"; } 
if numb = 344 { global.spr_unownv = sprite_add("group\unownv.png",2,1,1,0,0); sprite_index = global.spr_unownv; name = "unownv"; } 
if numb = 345 { global.spr_unownw = sprite_add("group\unownw.png",2,1,1,0,0); sprite_index = global.spr_unownw; name = "unownw"; } 
if numb = 346 { global.spr_unownx = sprite_add("group\unownx.png",2,1,1,0,0); sprite_index = global.spr_unownx; name = "unownx"; } 
if numb = 347 { global.spr_unowny = sprite_add("group\unowny.png",2,1,1,0,0); sprite_index = global.spr_unowny; name = "unowny"; } 
if numb = 348 { global.spr_unownz = sprite_add("group\unownz.png",2,1,1,0,0); sprite_index = global.spr_unownz; name = "unownz"; } 
if numb = 349 { global.spr_unownexclamation = sprite_add("group\unownexclamation.png",2,1,1,0,0); sprite_index = global.spr_unownexclamation; name = "unownexclamation"; } 
if numb = 350 { global.spr_unownquestion = sprite_add("group\unownquestion.png",2,1,1,0,0); sprite_index = global.spr_unownquestion; name = "unownquestion"; } 
if numb = 351 { global.spr_avion = sprite_add("group\avion.png",2,1,1,0,0); sprite_index = global.spr_avion; name = "avion"; } 
if numb = 352 { global.spr_gwyn = sprite_add("group\gwyn.png",2,1,1,0,0); sprite_index = global.spr_gwyn; name = "gwyn"; } 
if numb = 353 { global.spr_manus = sprite_add("group\manus.png",2,1,1,0,0); sprite_index = global.spr_manus; name = "manus"; } 
if numb = 354 { global.spr_quelaag = sprite_add("group\quelaag.png",2,1,1,0,0); sprite_index = global.spr_quelaag; name = "quelaag"; } 
if numb = 355 { global.spr_shadowlurkerf = sprite_add("group\shadowlurkerf.png",2,1,1,0,0); sprite_index = global.spr_shadowlurkerf; name = "shadowlurkerf"; } 
if numb = 356 { global.spr_agumon = sprite_add("group\agumon.png",2,1,1,0,0); sprite_index = global.spr_agumon; name = "agumon"; } 
if numb = 357 { global.spr_kingallant = sprite_add("group\kingallant.png",2,1,1,0,0); sprite_index = global.spr_kingallant; name = "kingallant"; } 
if numb = 358 { global.spr_blissey = sprite_add("group\blissey.png",2,1,1,0,0); sprite_index = global.spr_blissey; name = "blissey"; } 
if numb = 359 { global.spr_oldmonk = sprite_add("group\oldmonk.png",2,1,1,0,0); sprite_index = global.spr_oldmonk; name = "oldmonk"; } 
if numb = 360 { global.spr_gengar = sprite_add("group\gengar.png",2,1,1,0,0); sprite_index = global.spr_gengar; name = "gengar"; } 
if numb = 361 { global.spr_stormking = sprite_add("group\stormking.png",2,1,1,0,0); sprite_index = global.spr_stormking; name = "stormking"; } 
if numb = 362 { global.spr_leechmoger = sprite_add("group\leechmoger.png",2,1,1,0,0); sprite_index = global.spr_leechmoger; name = "leechmoger"; } 
if numb = 363 { global.spr_maideninblack = sprite_add("group\maideninblack.png",2,1,1,0,0); sprite_index = global.spr_maideninblack; name = "maideninblack"; } 
if numb = 364 { global.spr_xatu = sprite_add("group\xatu.png",2,1,1,0,0); sprite_index = global.spr_xatu; name = "xatu"; } 
if numb = 365 { global.spr_boneclaw = sprite_add("group\boneclaw.png",2,1,1,0,0); sprite_index = global.spr_boneclaw; name = "boneclaw"; } 
if numb = 366 { global.spr_troutmaskreplica = sprite_add("group\troutmaskreplica.png",2,1,1,0,0); sprite_index = global.spr_troutmaskreplica; name = "troutmaskreplica"; } 
if numb = 367 { global.spr_satori = sprite_add("group\satori.png",2,1,1,0,0); sprite_index = global.spr_satori; name = "satori"; } 
if numb = 368 { global.spr_demoman = sprite_add("group\demoman.png",2,1,1,0,0); sprite_index = global.spr_demoman; name = "demoman"; } 
if numb = 369 { global.spr_pyro = sprite_add("group\pyro.png",2,1,1,0,0); sprite_index = global.spr_pyro; name = "pyro"; } 
if numb = 370 { global.spr_spy = sprite_add("group\spy.png",2,1,1,0,0); sprite_index = global.spr_spy; name = "spy"; } 
if numb = 371 { global.spr_medic = sprite_add("group\medic.png",2,1,1,0,0); sprite_index = global.spr_medic; name = "medic"; } 
if numb = 372 { global.spr_skout = sprite_add("group\skout.png",2,1,1,0,0); sprite_index = global.spr_skout; name = "skout"; } 
if numb = 373 { global.spr_soldier = sprite_add("group\soldier.png",2,1,1,0,0); sprite_index = global.spr_soldier; name = "soldier"; } 
if numb = 374 { global.spr_heavy = sprite_add("group\heavy.png",2,1,1,0,0); sprite_index = global.spr_heavy; name = "heavy"; } 
if numb = 375 { global.spr_isaacclarke = sprite_add("group\isaacclarke.png",2,1,1,0,0); sprite_index = global.spr_isaacclarke; name = "isaacclarke"; } 
if numb = 376 { global.spr_limbokid = sprite_add("group\limbokid.png",2,1,1,0,0); sprite_index = global.spr_limbokid; name = "limbokid"; } 
if numb = 377 { global.spr_magnezone = sprite_add("group\magnezone.png",2,1,1,0,0); sprite_index = global.spr_magnezone; name = "magnezone"; } 
if numb = 378 { global.spr_cj = sprite_add("group\cj.png",2,1,1,0,0); sprite_index = global.spr_cj; name = "cj"; } 
if numb = 379 { global.spr_sven = sprite_add("group\sven.png",2,1,1,0,0); sprite_index = global.spr_sven; name = "sven"; } 
if numb = 380 { global.spr_vivec = sprite_add("group\vivec.png",2,1,1,0,0); sprite_index = global.spr_vivec; name = "vivec"; } 
if numb = 381 { global.spr_dagothur = sprite_add("group\dagothur.png",2,1,1,0,0); sprite_index = global.spr_dagothur; name = "dagothur"; } 
if numb = 382 { global.spr_biker = sprite_add("group\biker.png",2,1,1,0,0); sprite_index = global.spr_biker; name = "biker"; } 
if numb = 383 { global.spr_jacket = sprite_add("group\jacket.png",2,1,1,0,0); sprite_index = global.spr_jacket; name = "jacket"; } 
if numb = 384 { global.spr_slugma = sprite_add("group\slugma.png",2,1,1,0,0); sprite_index = global.spr_slugma; name = "slugma"; } 
if numb = 385 { global.spr_haunter = sprite_add("group\haunter.png",2,1,1,0,0); sprite_index = global.spr_haunter; name = "haunter"; } 
if numb = 386 { global.spr_weepinbell = sprite_add("group\weepinbell.png",2,1,1,0,0); sprite_index = global.spr_weepinbell; name = "weepinbell"; } 
if numb = 387 { global.spr_maxwell = sprite_add("group\maxwell.png",2,1,1,0,0); sprite_index = global.spr_maxwell; name = "maxwell"; } 
if numb = 388 { global.spr_aboleth = sprite_add("group\aboleth.png",2,1,1,0,0); sprite_index = global.spr_aboleth; name = "aboleth"; } 
if numb = 389 { global.spr_astralstalker = sprite_add("group\astralstalker.png",2,1,1,0,0); sprite_index = global.spr_astralstalker; name = "astralstalker"; } 
if numb = 390 { global.spr_runeknight = sprite_add("group\runeknight.png",2,1,1,0,0); sprite_index = global.spr_runeknight; name = "runeknight"; } 
if numb = 391 { global.spr_eagleman = sprite_add("group\eagleman.png",2,1,1,0,0); sprite_index = global.spr_eagleman; name = "eagleman"; } 
if numb = 392 { global.spr_bigdaddy = sprite_add("group\bigdaddy.png",2,1,1,0,0); sprite_index = global.spr_bigdaddy; name = "bigdaddy"; } 
if numb = 393 { global.spr_garbodor = sprite_add("group\garbodor.png",2,1,1,0,0); sprite_index = global.spr_garbodor; name = "garbodor"; } 
if numb = 394 { global.spr_johnnybravo = sprite_add("group\johnnybravo.png",2,1,1,0,0); sprite_index = global.spr_johnnybravo; name = "johnnybravo"; } 
if numb = 395 { global.spr_reimu = sprite_add("group\reimu.png",2,1,1,0,0); sprite_index = global.spr_reimu; name = "reimu"; } 
if numb = 396 { global.spr_clefairy = sprite_add("group\clefairy.png",2,1,1,0,0); sprite_index = global.spr_clefairy; name = "clefairy"; } 
if numb = 397 { global.spr_mima = sprite_add("group\mima.png",2,1,1,0,0); sprite_index = global.spr_mima; name = "mima"; } 
if numb = 398 { global.spr_arcanine = sprite_add("group\arcanine.png",2,1,1,0,0); sprite_index = global.spr_arcanine; name = "arcanine"; } 
if numb = 399 { global.spr_zatchbell = sprite_add("group\zatchbell.png",2,1,1,0,0); sprite_index = global.spr_zatchbell; name = "zatchbell"; } 
if numb = 400 { global.spr_sanicthingkenoffast = sprite_add("group\sanicthingkenoffast.png",2,1,1,0,0); sprite_index = global.spr_sanicthingkenoffast; name = "sanicthingkenoffast"; } 
if numb = 401 { global.spr_plaguedoctor = sprite_add("group\plaguedoctor.png",2,1,1,0,0); sprite_index = global.spr_plaguedoctor; name = "plaguedoctor"; } 
if numb = 402 { global.spr_tia = sprite_add("group\tia.png",2,1,1,0,0); sprite_index = global.spr_tia; name = "tia"; } 
if numb = 403 { global.spr_kanchome = sprite_add("group\kanchome.png",2,1,1,0,0); sprite_index = global.spr_kanchome; name = "kanchome"; } 
if numb = 404 { global.spr_mayorofcantown = sprite_add("group\mayorofcantown.png",2,1,1,0,0); sprite_index = global.spr_mayorofcantown; name = "mayorofcantown"; } 
if numb = 405 { global.spr_umagon = sprite_add("group\umagon.png",2,1,1,0,0); sprite_index = global.spr_umagon; name = "umagon"; } 
if numb = 406 { global.spr_honeydew = sprite_add("group\honeydew.png",2,1,1,0,0); sprite_index = global.spr_honeydew; name = "honeydew"; } 
if numb = 407 { global.spr_mrkrabs = sprite_add("group\mrkrabs.png",2,1,1,0,0); sprite_index = global.spr_mrkrabs; name = "mrkrabs"; } 
if numb = 408 { global.spr_sissel = sprite_add("group\sissel.png",2,1,1,0,0); sprite_index = global.spr_sissel; name = "sissel"; } 
if numb = 409 { global.spr_orangestarinfintry = sprite_add("group\orangestarinfintry.png",2,1,1,0,0); sprite_index = global.spr_orangestarinfintry; name = "orangestarinfintry"; } 
if numb = 410 { global.spr_fawful = sprite_add("group\fawful.png",2,1,1,0,0); sprite_index = global.spr_fawful; name = "fawful"; } 
if numb = 411 { global.spr_constanza = sprite_add("group\constanza.png",2,1,1,0,0); sprite_index = global.spr_constanza; name = "constanza"; } 
if numb = 412 { global.spr_brago = sprite_add("group\brago.png",2,1,1,0,0); sprite_index = global.spr_brago; name = "brago"; } 
if numb = 413 { global.spr_blu = sprite_add("group\blu.png",2,1,1,0,0); sprite_index = global.spr_blu; name = "blu"; } 
if numb = 414 { global.spr_jingitaxias = sprite_add("group\jingitaxias.png",2,1,1,0,0); sprite_index = global.spr_jingitaxias; name = "jingitaxias"; } 
if numb = 415 { global.spr_roadrunner = sprite_add("group\roadrunner.png",2,1,1,0,0); sprite_index = global.spr_roadrunner; name = "roadrunner"; } 
if numb = 416 { global.spr_dragonite = sprite_add("group\dragonite.png",2,1,1,0,0); sprite_index = global.spr_dragonite; name = "dragonite"; } 
if numb = 417 { global.spr_umagonshudoruk = sprite_add("group\umagonshudoruk.png",2,1,1,0,0); sprite_index = global.spr_umagonshudoruk; name = "umagonshudoruk"; } 
if numb = 418 { global.spr_umagongoshudoruk = sprite_add("group\umagongoshudoruk.png",2,1,1,0,0); sprite_index = global.spr_umagongoshudoruk; name = "umagongoshudoruk"; } 
if numb = 419 { global.spr_umagondioemuru = sprite_add("group\umagondioemuru.png",2,1,1,0,0); sprite_index = global.spr_umagondioemuru; name = "umagondioemuru"; } 
if numb = 420 { global.spr_roggenrola = sprite_add("group\roggenrola.png",2,1,1,0,0); sprite_index = global.spr_roggenrola; name = "roggenrola"; } 
if numb = 421 { global.spr_zeon = sprite_add("group\zeon.png",2,1,1,0,0); sprite_index = global.spr_zeon; name = "zeon"; } 
if numb = 422 { global.spr_solosis = sprite_add("group\solosis.png",2,1,1,0,0); sprite_index = global.spr_solosis; name = "solosis"; } 
if numb = 423 { global.spr_duosion = sprite_add("group\duosion.png",2,1,1,0,0); sprite_index = global.spr_duosion; name = "duosion"; } 
if numb = 424 { global.spr_spoink = sprite_add("group\spoink.png",2,1,1,0,0); sprite_index = global.spr_spoink; name = "spoink"; } 
if numb = 425 { global.spr_billcipher = sprite_add("group\billcipher.png",2,1,1,0,0); sprite_index = global.spr_billcipher; name = "billcipher"; } 
if numb = 426 { global.spr_skipper = sprite_add("group\skipper.png",2,1,1,0,0); sprite_index = global.spr_skipper; name = "skipper"; } 
if numb = 427 { global.spr_private = sprite_add("group\private.png",2,1,1,0,0); sprite_index = global.spr_private; name = "private"; } 
if numb = 428 { global.spr_rico = sprite_add("group\rico.png",2,1,1,0,0); sprite_index = global.spr_rico; name = "rico"; } 
if numb = 429 { global.spr_kowalski = sprite_add("group\kowalski.png",2,1,1,0,0); sprite_index = global.spr_kowalski; name = "kowalski"; } 
if numb = 430 { global.spr_hans = sprite_add("group\hans.png",2,1,1,0,0); sprite_index = global.spr_hans; name = "hans"; } 
if numb = 431 { global.spr_drsloth = sprite_add("group\drsloth.png",2,1,1,0,0); sprite_index = global.spr_drsloth; name = "drsloth"; } 
if numb = 432 { global.spr_owl = sprite_add("group\owl.png",2,1,1,0,0); sprite_index = global.spr_owl; name = "owl"; } 
if numb = 433 { global.spr_masterchief = sprite_add("group\masterchief.png",2,1,1,0,0); sprite_index = global.spr_masterchief; name = "masterchief"; } 
if numb = 434 { global.spr_crobat = sprite_add("group\crobat.png",2,1,1,0,0); sprite_index = global.spr_crobat; name = "crobat"; } 
if numb = 435 { global.spr_zubat = sprite_add("group\zubat.png",2,1,1,0,0); sprite_index = global.spr_zubat; name = "zubat"; } 
if numb = 436 { global.spr_jcdenton = sprite_add("group\jcdenton.png",2,1,1,0,0); sprite_index = global.spr_jcdenton; name = "jcdenton"; } 
if numb = 437 { global.spr_bomberman = sprite_add("group\bomberman.png",2,1,1,0,0); sprite_index = global.spr_bomberman; name = "bomberman"; } 
if numb = 438 { global.spr_coolspot = sprite_add("group\coolspot.png",2,1,1,0,0); sprite_index = global.spr_coolspot; name = "coolspot"; } 
if numb = 439 { global.spr_panty = sprite_add("group\panty.png",2,1,1,0,0); sprite_index = global.spr_panty; name = "panty"; } 
if numb = 440 { global.spr_stocking = sprite_add("group\stocking.png",2,1,1,0,0); sprite_index = global.spr_stocking; name = "stocking"; } 
if numb = 441 { global.spr_frankerz = sprite_add("group\frankerz.png",2,1,1,0,0); sprite_index = global.spr_frankerz; name = "frankerz"; } 
if numb = 442 { global.spr_rance = sprite_add("group\rance.png",2,1,1,0,0); sprite_index = global.spr_rance; name = "rance"; } 
if numb = 443 { global.spr_chie = sprite_add("group\chie.png",2,1,1,0,0); sprite_index = global.spr_chie; name = "chie"; } 
if numb = 444 { global.spr_cormano = sprite_add("group\cormano.png",2,1,1,0,0); sprite_index = global.spr_cormano; name = "cormano"; } 
if numb = 445 { global.spr_shake = sprite_add("group\shake.png",2,1,1,0,0); sprite_index = global.spr_shake; name = "shake"; } 
if numb = 446 { global.spr_sweetbro = sprite_add("group\sweetbro.png",2,1,1,0,0); sprite_index = global.spr_sweetbro; name = "sweetbro"; } 
if numb = 447 { global.spr_midna = sprite_add("group\midna.png",2,1,1,0,0); sprite_index = global.spr_midna; name = "midna"; } 
if numb = 448 { global.spr_hellajeff = sprite_add("group\hellajeff.png",2,1,1,0,0); sprite_index = global.spr_hellajeff; name = "hellajeff"; } 
if numb = 449 { global.spr_meatwad = sprite_add("group\meatwad.png",2,1,1,0,0); sprite_index = global.spr_meatwad; name = "meatwad"; } 
if numb = 450 { global.spr_raiden = sprite_add("group\raiden.png",2,1,1,0,0); sprite_index = global.spr_raiden; name = "raiden"; } 
if numb = 451 { global.spr_emi = sprite_add("group\emi.png",2,1,1,0,0); sprite_index = global.spr_emi; name = "emi"; } 
if numb = 452 { global.spr_gerome = sprite_add("group\gerome.png",2,1,1,0,0); sprite_index = global.spr_gerome; name = "gerome"; } 
if numb = 453 { global.spr_gordonfreeman = sprite_add("group\gordonfreeman.png",2,1,1,0,0); sprite_index = global.spr_gordonfreeman; name = "gordonfreeman"; } 
if numb = 454 { global.spr_pacman = sprite_add("group\pacman.png",2,1,1,0,0); sprite_index = global.spr_pacman; name = "pacman"; } 
if numb = 455 { global.spr_beckett = sprite_add("group\beckett.png",2,1,1,0,0); sprite_index = global.spr_beckett; name = "beckett"; } 
if numb = 456 { global.spr_blackrose = sprite_add("group\blackrose.png",2,1,1,0,0); sprite_index = global.spr_blackrose; name = "blackrose"; } 
if numb = 457 { global.spr_met = sprite_add("group\met.png",2,1,1,0,0); sprite_index = global.spr_met; name = "met"; } 
if numb = 458 { global.spr_spaceinvader = sprite_add("group\spaceinvader.png",2,1,1,0,0); sprite_index = global.spr_spaceinvader; name = "spaceinvader"; } 
if numb = 459 { global.spr_litwick = sprite_add("group\litwick.png",2,1,1,0,0); sprite_index = global.spr_litwick; name = "litwick"; } 
if numb = 460 { global.spr_solaire = sprite_add("group\solaire.png",2,1,1,0,0); sprite_index = global.spr_solaire; name = "solaire"; } 
if numb = 461 { global.spr_zekedunbar = sprite_add("group\zekedunbar.png",2,1,1,0,0); sprite_index = global.spr_zekedunbar; name = "zekedunbar"; } 
if numb = 462 { global.spr_malkavian = sprite_add("group\malkavian.png",2,1,1,0,0); sprite_index = global.spr_malkavian; name = "malkavian"; } 
if numb = 463 { global.spr_peashooter = sprite_add("group\peashooter.png",2,1,1,0,0); sprite_index = global.spr_peashooter; name = "peashooter"; } 
if numb = 464 { global.spr_pumkin = sprite_add("group\pumkin.png",2,1,1,0,0); sprite_index = global.spr_pumkin; name = "pumkin"; } 
if numb = 465 { global.spr_phoenixwright = sprite_add("group\phoenixwright.png",2,1,1,0,0); sprite_index = global.spr_phoenixwright; name = "phoenixwright"; } 
if numb = 466 { global.spr_scoobywerkstat = sprite_add("group\scoobywerkstat.png",2,1,1,0,0); sprite_index = global.spr_scoobywerkstat; name = "scoobywerkstat"; } 
if numb = 467 { global.spr_armordarmadillo = sprite_add("group\armordarmadillo.png",2,1,1,0,0); sprite_index = global.spr_armordarmadillo; name = "armordarmadillo"; } 
if numb = 468 { global.spr_megamanx = sprite_add("group\megamanx.png",2,1,1,0,0); sprite_index = global.spr_megamanx; name = "megamanx"; } 
if numb = 469 { global.spr_jetstreamsam = sprite_add("group\jetstreamsam.png",2,1,1,0,0); sprite_index = global.spr_jetstreamsam; name = "jetstreamsam"; } 
if numb = 470 { global.spr_gene = sprite_add("group\gene.png",2,1,1,0,0); sprite_index = global.spr_gene; name = "gene"; } 
if numb = 471 { global.spr_jotarokujo = sprite_add("group\jotarokujo.png",2,1,1,0,0); sprite_index = global.spr_jotarokujo; name = "jotarokujo"; } 
if numb = 472 { global.spr_megamanexe = sprite_add("group\megamanexe.png",2,1,1,0,0); sprite_index = global.spr_megamanexe; name = "megamanexe"; } 
if numb = 473 { global.spr_leila = sprite_add("group\leila.png",2,1,1,0,0); sprite_index = global.spr_leila; name = "leila"; } 
if numb = 474 { global.spr_danmandel = sprite_add("group\danmandel.png",2,1,1,0,0); sprite_index = global.spr_danmandel; name = "danmandel"; } 
if numb = 475 { global.spr_elisepearson = sprite_add("group\elisepearson.png",2,1,1,0,0); sprite_index = global.spr_elisepearson; name = "elisepearson"; } 
if numb = 476 { global.spr_chrispearson = sprite_add("group\chrispearson.png",2,1,1,0,0); sprite_index = global.spr_chrispearson; name = "chrispearson"; } 
if numb = 477 { global.spr_sif = sprite_add("group\sif.png",2,1,1,0,0); sprite_index = global.spr_sif; name = "sif"; } 
if numb = 478 { global.spr_strayhumanity = sprite_add("group\strayhumanity.png",2,1,1,0,0); sprite_index = global.spr_strayhumanity; name = "strayhumanity"; } 
if numb = 479 { global.spr_crestfallenwarrior = sprite_add("group\crestfallenwarrior.png",2,1,1,0,0); sprite_index = global.spr_crestfallenwarrior; name = "crestfallenwarrior"; } 
if numb = 480 { global.spr_caprademon = sprite_add("group\caprademon.png",2,1,1,0,0); sprite_index = global.spr_caprademon; name = "caprademon"; } 
if numb = 481 { global.spr_gwyndolin = sprite_add("group\gwyndolin.png",2,1,1,0,0); sprite_index = global.spr_gwyndolin; name = "gwyndolin"; } 
if numb = 482 { global.spr_nier = sprite_add("group\nier.png",2,1,1,0,0); sprite_index = global.spr_nier; name = "nier"; } 
if numb = 483 { global.spr_weiss = sprite_add("group\weiss.png",2,1,1,0,0); sprite_index = global.spr_weiss; name = "weiss"; } 
if numb = 484 { global.spr_ryu = sprite_add("group\ryu.png",2,1,1,0,0); sprite_index = global.spr_ryu; name = "ryu"; } 
if numb = 485 { global.spr_zangief = sprite_add("group\zangief.png",2,1,1,0,0); sprite_index = global.spr_zangief; name = "zangief"; } 
if numb = 486 { global.spr_monokuma = sprite_add("group\monokuma.png",2,1,1,0,0); sprite_index = global.spr_monokuma; name = "monokuma"; } 
if numb = 487 { global.spr_shade = sprite_add("group\shade.png",2,1,1,0,0); sprite_index = global.spr_shade; name = "shade"; } 
if numb = 488 { global.spr_chacha = sprite_add("group\chacha.png",2,1,1,0,0); sprite_index = global.spr_chacha; name = "chacha"; } 
if numb = 489 { global.spr_lucas = sprite_add("group\lucas.png",2,1,1,0,0); sprite_index = global.spr_lucas; name = "lucas"; } 
if numb = 490 { global.spr_kenmasters = sprite_add("group\kenmasters.png",2,1,1,0,0); sprite_index = global.spr_kenmasters; name = "kenmasters"; } 
if numb = 491 { global.spr_aigis = sprite_add("group\aigis.png",2,1,1,0,0); sprite_index = global.spr_aigis; name = "aigis"; } 
if numb = 492 { global.spr_sniper = sprite_add("group\sniper.png",2,1,1,0,0); sprite_index = global.spr_sniper; name = "sniper"; } 
if numb = 493 { global.spr_rikafurude = sprite_add("group\rikafurude.png",2,1,1,0,0); sprite_index = global.spr_rikafurude; name = "rikafurude"; } 
if numb = 494 { global.spr_chernoalpha = sprite_add("group\chernoalpha.png",2,1,1,0,0); sprite_index = global.spr_chernoalpha; name = "chernoalpha"; } 
if numb = 495 { global.spr_strikereureka = sprite_add("group\strikereureka.png",2,1,1,0,0); sprite_index = global.spr_strikereureka; name = "strikereureka"; } 
if numb = 496 { global.spr_burmyplant = sprite_add("group\burmyplant.png",2,1,1,0,0); sprite_index = global.spr_burmyplant; name = "burmyplant"; } 
if numb = 497 { global.spr_wormadamplant = sprite_add("group\wormadamplant.png",2,1,1,0,0); sprite_index = global.spr_wormadamplant; name = "wormadamplant"; } 
if numb = 498 { global.spr_wormadamtrash = sprite_add("group\wormadamtrash.png",2,1,1,0,0); sprite_index = global.spr_wormadamtrash; name = "wormadamtrash"; } 
if numb = 499 { global.spr_wormadamsand = sprite_add("group\wormadamsand.png",2,1,1,0,0); sprite_index = global.spr_wormadamsand; name = "wormadamsand"; } 
if numb = 500 { global.spr_yotsuba = sprite_add("group\yotsuba.png",2,1,1,0,0); sprite_index = global.spr_yotsuba; name = "yotsuba"; } 
if numb = 501 { global.spr_cubone = sprite_add("group\cubone.png",2,1,1,0,0); sprite_index = global.spr_cubone; name = "cubone"; } 
if numb = 502 { global.spr_meowth = sprite_add("group\meowth.png",2,1,1,0,0); sprite_index = global.spr_meowth; name = "meowth"; } 
if numb = 503 { global.spr_beat = sprite_add("group\beat.png",2,1,1,0,0); sprite_index = global.spr_beat; name = "beat"; } 
if numb = 504 { global.spr_isabelle = sprite_add("group\isabelle.png",2,1,1,0,0); sprite_index = global.spr_isabelle; name = "isabelle"; } 
if numb = 505 { global.spr_balrog = sprite_add("group\balrog.png",2,1,1,0,0); sprite_index = global.spr_balrog; name = "balrog"; } 
if numb = 506 { global.spr_takamaru = sprite_add("group\takamaru.png",2,1,1,0,0); sprite_index = global.spr_takamaru; name = "takamaru"; } 


